Repository openedx/edx-platform, pull requests merged in 2018-09, with the labels that each got.

#18860 bump edx-sga to 0.8.3
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: awaiting prioritization, open-source-contribution

#18856 OC-5192 Fix: Convert DATA_DIR to a Path object when fetching its value from ENV_TOKENS
  cms/envs/aws.py
  lms/envs/aws.py
Labels: awaiting prioritization, open-source-contribution

#18837 Upgrade the ddt package to a version supports Python 3
  common/djangoapps/util/tests/test_keyword_sub_utils.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: awaiting prioritization, open-source-contribution

#18149 Expose attempt number to python custom grader
  common/lib/capa/capa/tests/test_responsetypes.py
  common/lib/xmodule/xmodule/capa_base.py
  common/lib/xmodule/xmodule/tests/test_capa_module.py
Labels: awaiting prioritization, open-source-contribution

#18855 LX-24 Extract static paths
  common/djangoapps/static_replace/__init__.py
  common/djangoapps/static_replace/test/test_static_replace.py
Labels: awaiting prioritization, open-source-contribution

#18557 OSPR: Improve Course Modes configuration
  cms/djangoapps/contentstore/views/tests/test_item.py
  cms/envs/aws.py
  common/djangoapps/course_modes/admin.py
  lms/envs/aws.py
  lms/envs/common.py
  openedx/core/djangoapps/verified_track_content/management/commands/swap_from_auto_track_cohort_pilot.py
  openedx/core/djangoapps/verified_track_content/partition_scheme.py
  openedx/core/djangoapps/verified_track_content/tests/test_partition_scheme.py
Labels: open-source-contribution, waiting on author

#18808 Fix incorrect course name displayed for CCX courses.
  lms/djangoapps/ccx/migrations/0006_set_display_name_as_override.py
  lms/djangoapps/ccx/tests/test_views.py
  lms/djangoapps/ccx/views.py
Labels: community manager review, open-source-contribution

#18840 OLX export: Reverted url_name from a constant to course run
  common/lib/xmodule/xmodule/modulestore/tests/test_cross_modulestore_import_export.py
  common/lib/xmodule/xmodule/modulestore/xml_exporter.py
  common/lib/xmodule/xmodule/tests/test_import.py
  common/lib/xmodule/xmodule/x_module.py
  common/lib/xmodule/xmodule/xml_module.py
Labels: architecture review, open-source-contribution

#18964 Handle exception while saving course display name.
  lms/djangoapps/ccx/migrations/0006_set_display_name_as_override.py
Labels: engineering review, open-source-contribution

#18966 Fix query counts on completion tests.
  openedx/tests/completion_integration/test_models.py
  requirements/edx-sandbox/base.txt
  requirements/edx/base.txt
  requirements/edx/coverage.in
  requirements/edx/coverage.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#18874 Upgrade the django-ipware Package to a version Supports Python 3
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, waiting on author

#18864 [OC-3682] Implement management commands to export/import content libraries
  cms/djangoapps/contentstore/management/commands/export_content_library.py
  cms/djangoapps/contentstore/management/commands/import_content_library.py
Labels: open-source-contribution, waiting on author
