Repository openedx/edx-platform, pull requests merged in 2018-04, with the labels that each got.

#17850 Fixed error: ImportError: No module named notmigrations
  common/djangoapps/util/db.py
Labels: awaiting prioritization, open-source-contribution

#17819 Fix styling of navtabs.
  lms/static/sass/_header.scss
  lms/templates/header/navbar-authenticated.html
Labels: awaiting prioritization, open-source-contribution

#17498 Added completion mode to discussion XBlock
  openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion/__init__.py
  openedx/tests/completion_integration/test_handlers.py
Labels: engineering review, open-source-contribution

#17698 Implement iter_all_for_block and iter_all_for_course for DjangoUserStateClient
  lms/djangoapps/courseware/tests/test_user_state_client.py
  lms/djangoapps/courseware/user_state_client.py
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#17986 Changed the author info.
  AUTHORS
Labels: community manager review, open-source-contribution

#17368 Remove physical constants and suffixes from calc.py
  common/lib/calc/calc/calc.py
  common/lib/calc/calc/tests/test_calc.py
  common/lib/calc/calc/tests/test_preview.py
Labels: awaiting prioritization, open-source-contribution

#17748 Set SWIFT_CONTENT_LENGTH_FROM_FD=False
  cms/envs/openstack.py
  lms/envs/openstack.py
  requirements/edx/openstack.txt
Labels: awaiting prioritization, open-source-contribution
