Repository openedx/edx-platform, pull requests merged in 2018-08, with the labels that each got.

#18638 Gate access to the CourseEnrollmentAdmin view with a waffle switch
  common/djangoapps/student/__init__.py
  common/djangoapps/student/admin.py
  common/djangoapps/student/tests/test_admin_views.py
Labels: awaiting prioritization, open-source-contribution

#16669 Add feature to send an e-mail to staff when a student enrolls
  common/djangoapps/enrollment/apps.py
  common/djangoapps/enrollment/handlers.py
  common/djangoapps/enrollment/tests/test_emails.py
  common/templates/emails/new_enrollment_email_body.txt
  common/templates/emails/new_enrollment_email_subject.txt
  lms/envs/aws.py
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#17699 Add CourseFields.other_course_settings to store custom fields
  cms/djangoapps/contentstore/tests/test_course_settings.py
  cms/djangoapps/models/settings/course_metadata.py
  cms/envs/common.py
  common/lib/xmodule/xmodule/course_module.py
Labels: engineering review, open-source-contribution

#17477 Improve CourseEnrollment admin search presentation
  common/djangoapps/student/admin.py
  common/djangoapps/student/tests/test_admin_views.py
Labels: awaiting prioritization, open-source-contribution

#18785 Fixing textline CSS issue
  common/lib/xmodule/xmodule/css/capa/display.scss
Labels: needs triage, open-source-contribution

#18344 Fixes for courseware anonymous access.
  common/lib/xmodule/xmodule/js/src/sequence/display.js
  common/lib/xmodule/xmodule/seq_module.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/templates/seq_module.html
Labels: awaiting prioritization, open-source-contribution
