Repository openedx/edx-platform, pull requests merged in 2018-12, with the labels that each got.

#18477 Missing translation EDUCATOR-1338
  cms/templates/js/show-textbook.underscore
Labels: awaiting prioritization, open-source-contribution

#18992 Put certificate data message into it's own block for overriding
  lms/templates/courseware/progress.html
Labels: awaiting prioritization, open-source-contribution

#19284 Access for unenrolled learners.
  cms/djangoapps/models/settings/course_metadata.py
  common/lib/xmodule/xmodule/course_module.py
  common/lib/xmodule/xmodule/html_module.py
  common/lib/xmodule/xmodule/modulestore/tests/django_utils.py
  common/lib/xmodule/xmodule/seq_module.py
  common/lib/xmodule/xmodule/tests/helpers.py
  common/lib/xmodule/xmodule/tests/test_html_module.py
  common/lib/xmodule/xmodule/tests/test_sequence.py
  common/lib/xmodule/xmodule/tests/test_vertical.py
  common/lib/xmodule/xmodule/vertical_block.py
  common/lib/xmodule/xmodule/x_module.py
  lms/djangoapps/course_api/blocks/transformers/milestones.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/views/index.py
  lms/static/sass/course/courseware/_courseware.scss
  openedx/features/course_experience/__init__.py
  openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/utils.py
  openedx/features/course_experience/views/course_home.py
  openedx/features/course_experience/views/course_outline.py
Labels: engineering review, open-source-contribution

#19413 Put certificate data message into it's own block for overriding
  lms/templates/courseware/progress.html
Labels: needs triage, open-source-contribution

#19089 Refactored XBlockAside rendering and added support for student view
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/views/item.py
  cms/djangoapps/contentstore/views/tests/test_item.py
  cms/static/js/views/modals/edit_xblock.js
  cms/static/js/views/xblock_editor.js
  cms/static/sass/elements/_modal-window.scss
  cms/static/sass/elements/_xblocks.scss
  common/static/common/js/xblock/core.js
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/courseware/student_field_overrides.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/lms_xblock/runtime.py
  openedx/core/lib/tests/test_xblock_utils.py
  openedx/core/lib/xblock_utils/__init__.py
Labels: awaiting prioritization, open-source-contribution

#19305 SE-183 Enable video content for anonymous and unenrolled learners
  common/lib/xmodule/xmodule/js/spec/video/video_save_state_plugin_spec.js
  common/lib/xmodule/xmodule/js/src/video/09_save_state_plugin.js
  common/lib/xmodule/xmodule/seq_module.py
  common/lib/xmodule/xmodule/video_module/video_module.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/lms_xblock/runtime.py
Labels: open-source-contribution, waiting on author

#17955 OSPR-2352 | Support for theming .underscore files
  common/djangoapps/pipeline_mako/templates/static_content.html
Labels: awaiting prioritization, open-source-contribution
