Repository openedx/edx-platform, pull requests merged in 2018-10, with the labels that each got.

#17216 Show browser support alert
  lms/envs/common.py
  lms/static/sass/_build-lms-v1.scss
  lms/static/sass/features/_unsupported-browser-alert.scss
  lms/templates/header/header.html
Labels: awaiting prioritization, open-source-contribution

#17351 Fixed issue where git logs aren't functioning
  lms/djangoapps/dashboard/git_import.py
  lms/djangoapps/dashboard/models.py
  lms/djangoapps/dashboard/sysadmin.py
  lms/djangoapps/dashboard/tests/test_sysadmin.py
Labels: open-source-contribution, waiting on author

#18882 edX-ACE support for email change messages
  common/djangoapps/student/message_types.py
  common/djangoapps/student/tests/test_email.py
  common/djangoapps/student/views/management.py
  common/templates/student/edx_ace/emailchange/email/body.html
  common/templates/student/edx_ace/emailchange/email/body.txt
  common/templates/student/edx_ace/emailchange/email/from_name.txt
  common/templates/student/edx_ace/emailchange/email/head.html
  common/templates/student/edx_ace/emailchange/email/subject.txt
  lms/templates/emails/email_change.txt
  openedx/core/djangoapps/user_api/accounts/tests/test_api.py
Labels: community manager review, open-source-contribution

#18336 Fixed code duplication in task listing api on instructor dashboard
  lms/djangoapps/instructor_task/tasks_helper/module_state.py
Labels: open-source-contribution, product review

#17682 Fixed override due date by limiting scope to selected users
  AUTHORS
  lms/djangoapps/course_api/blocks/api.py
  lms/djangoapps/course_api/blocks/tests/test_serializers.py
  lms/djangoapps/course_blocks/api.py
  lms/djangoapps/course_blocks/transformers/load_override_data.py
  lms/djangoapps/course_blocks/transformers/tests/test_load_override_data.py
Labels: awaiting prioritization, open-source-contribution

#18237 Add endpoint to get SAML providers for a user.
  common/djangoapps/third_party_auth/api/tests/test_views.py
  common/djangoapps/third_party_auth/api/urls.py
  common/djangoapps/third_party_auth/api/views.py
  lms/envs/aws.py
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#17449 Add enrollment status check for instructor
  lms/djangoapps/instructor/tests/test_api.py
  lms/djangoapps/instructor/views/api.py
  lms/djangoapps/instructor/views/api_urls.py
  lms/djangoapps/instructor/views/instructor_dashboard.py
  lms/static/js/instructor_dashboard/student_admin.js
  lms/templates/instructor/instructor_dashboard_2/student_admin.html
Labels: engineering review, open-source-contribution

#19107 Message related to certificate on courseware progress page are translated to platform language only
  lms/templates/courseware/progress.html
Labels: open-source-contribution, product review
