Repository openedx/edx-platform, pull requests merged in 2018-07, with the labels that each got.

#17332 Improve search error messages
  lms/static/js/discovery/discovery_factory.js
  lms/static/js/discovery/models/search_state.js
  lms/static/js/discovery/views/search_form.js
  lms/static/js/spec/discovery/discovery_factory_spec.js
  lms/static/js/spec/discovery/views/search_form_spec.js
  openedx/features/course_search/static/course_search/js/collections/search_collection.js
  openedx/features/course_search/static/course_search/js/views/search_results_view.js
  openedx/features/course_search/static/course_search/templates/search_error.underscore
Labels: awaiting prioritization, open-source-contribution

#17900 Fix course export issues
  cms/djangoapps/contentstore/views/import_export.py
  cms/djangoapps/contentstore/views/tests/test_import_export.py
  cms/envs/common.py
Labels: engineering review, open-source-contribution

#18512 Include original state in learner response report
  cms/djangoapps/contentstore/tasks.py
  cms/static/sass/views/_video-upload.scss
  common/lib/capa/capa/capa_problem.py
  common/lib/capa/capa/tests/test_capa_problem.py
  common/lib/xmodule/xmodule/capa_module.py
  lms/djangoapps/instructor_task/tasks_helper/grades.py
  lms/djangoapps/instructor_task/tests/test_tasks_helper.py
Labels: awaiting prioritization, open-source-contribution

#17634 Fixed bug involving users that could not be found using 'view this course as' functionality
  lms/djangoapps/courseware/masquerade.py
  lms/djangoapps/courseware/tests/test_masquerade.py
Labels: engineering review, open-source-contribution

#18536 Bump version of edx-search
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, waiting on author

#17824 UI to select a problem location for use in data download
  .babelrc
  cms/static/js/spec/video/transcripts/editor_spec.js
  cms/static/js/spec/video/transcripts/file_uploader_spec.js
  cms/static/js/spec/video/transcripts/message_manager_spec.js
  cms/static/js/spec/video/transcripts/videolist_spec.js
  cms/static/js/views/uploads.js
  cms/static/js/views/video/transcripts/file_uploader.js
  common/static/common/js/components/BlockBrowser/.eslintrc.js
  common/static/common/js/components/BlockBrowser/components/BlockBrowser/BlockBrowser.jsx
  common/static/common/js/components/BlockBrowser/components/BlockBrowser/BlockBrowser.test.jsx
  common/static/common/js/components/BlockBrowser/components/BlockBrowser/BlockBrowserContainer.jsx
  common/static/common/js/components/BlockBrowser/components/BlockBrowser/__snapshots__/BlockBrowser.test.jsx.snap
  common/static/common/js/components/BlockBrowser/components/BlockBrowser/test-block-tree.json
  common/static/common/js/components/BlockBrowser/data/actions/constants.js
  common/static/common/js/components/BlockBrowser/data/actions/courseBlocks.js
  common/static/common/js/components/BlockBrowser/data/api/client.js
  common/static/common/js/components/BlockBrowser/data/reducers/index.js
  common/static/common/js/components/BlockBrowser/data/selectors/index.js
  common/static/common/js/components/BlockBrowser/data/store.js
  common/static/common/js/components/BlockBrowser/index.jsx
  jest.config.js
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/.eslintrc.js
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/components/Main/Main.jsx
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/components/Main/Main.test.jsx
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/components/Main/MainContainer.jsx
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/components/Main/__snapshots__/Main.test.jsx.snap
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/index.jsx
  lms/djangoapps/support/static/support/jsx/entitlements/components/EntitlementForm/index.jsx
  lms/djangoapps/support/static/support/jsx/entitlements/data/reducers/form.js
  lms/djangoapps/support/static/support/jsx/logged_in_user.jsx
  lms/djangoapps/support/static/support/jsx/single_support_form.jsx
  lms/static/js/discovery/views/search_form.js
  lms/static/js/learner_dashboard/spec/program_details_sidebar_view_spec.js
  lms/static/js/learner_dashboard/views/unenroll_view.js
  lms/static/js/program_marketing.js
  lms/static/js/spec/discovery/discovery_factory_spec.js
  lms/static/js/student_account/enrollment.js
  lms/static/sass/course/instructor/_instructor_2.scss
  lms/templates/instructor/instructor_dashboard_2/data_download.html
  lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html
  package-lock.json
  package.json
  pavelib/js_test.py
  pavelib/paver_tests/test_js_test.py
  pavelib/utils/envs.py
  pavelib/utils/test/suites/__init__.py
  pavelib/utils/test/suites/js_suite.py
  setupTests.js
  webpack.common.config.js
Labels: engineering review, open-source-contribution

#18616 Add port to activation link to keep it from failing on devstack.
  AUTHORS
  cms/envs/devstack.py
Labels: community manager review, open-source-contribution

#18430 Allow using dev settings other than DEVSTACK
  pavelib/assets.py
  pavelib/paver_tests/test_servers.py
Labels: awaiting prioritization, open-source-contribution

#18657 Do not delete course enrollments
  common/djangoapps/student/migrations/0016_coursenrollment_course_on_delete_do_nothing.py
  common/djangoapps/student/models.py
  common/djangoapps/student/tests/test_models.py
Labels: awaiting prioritization, open-source-contribution
