Repository openedx/edx-platform, pull requests merged in 2019-06, with the labels that each got.

#20632 Remove the word "Student" from the progress title.
  lms/templates/courseware/progress.html
Labels: awaiting prioritization, needs triage, open-source-contribution

#19582 BB-732 Fix Django admin form for Course Enrollment
  common/djangoapps/student/admin.py
  common/djangoapps/student/tests/test_admin_views.py
Labels: needs triage, open-source-contribution

#20745 Campus.IL SE-1151 Strings used in models should always use gettext_lazy
  cms/djangoapps/course_creators/models.py
  openedx/core/djangoapps/api_admin/models.py
  openedx/core/djangoapps/credit/models.py
Labels: open-source-contribution, waiting on author

#20229 BB-1132 Decrease NAME_MIN_LENGTH to 1.
  common/djangoapps/student/forms.py
  common/test/acceptance/tests/lms/test_account_settings.py
  lms/djangoapps/verify_student/tests/test_views.py
  lms/djangoapps/verify_student/views.py
  openedx/core/djangoapps/user_api/accounts/__init__.py
  openedx/core/djangoapps/user_api/accounts/serializers.py
  openedx/core/djangoapps/user_api/accounts/tests/test_views.py
  openedx/core/djangoapps/user_authn/views/tests/test_register.py
Labels: needs triage, open-source-contribution

#20158 Change button text for creating account
  lms/templates/student_account/institution_register.underscore
Labels: engineering review, open-source-contribution

#20635 Remove the course name from the enroll button.
  lms/djangoapps/courseware/tests/test_about.py
  lms/djangoapps/courseware/tests/test_microsites.py
  lms/templates/courseware/course_about.html
Labels: awaiting prioritization, needs triage, open-source-contribution

#20785 INCR-344
  cms/djangoapps/api/apps.py
  cms/djangoapps/api/urls.py
  cms/djangoapps/api/v1/urls.py
  cms/djangoapps/api/v1/views/course_runs.py
  cms/djangoapps/pipeline_js/utils.py
Labels: engineering review, open-source-contribution

#20786 INCR-413: Run python-modernize and isort
  common/lib/xmodule/xmodule/modulestore/draft_and_published.py
  common/lib/xmodule/xmodule/modulestore/edit_info.py
  common/lib/xmodule/xmodule/modulestore/mixed.py
  common/lib/xmodule/xmodule/modulestore/modulestore_settings.py
  common/lib/xmodule/xmodule/modulestore/split_migrator.py
  common/lib/xmodule/xmodule/tests/xml/__init__.py
  common/lib/xmodule/xmodule/tests/xml/factories.py
  common/lib/xmodule/xmodule/tests/xml/test_inheritance.py
  common/lib/xmodule/xmodule/tests/xml/test_policy.py
Labels: awaiting prioritization, open-source-contribution

#19165 Message related to certificate on courseware progress page are translated to platform language only. Part 2 of 2.
  lms/djangoapps/courseware/views/views.py
Labels: engineering review, needs triage, open-source-contribution

#19958 Fix bug: re-render is triggered too many times in textbooks.
  cms/static/js/spec/views/textbook_spec.js
  cms/static/js/views/edit_textbook.js
  cms/static/js/views/list_textbooks.js
  cms/static/js/views/show_textbook.js
Labels: needs triage, open-source-contribution

#20814 INCR-477: Make compatible with Python 3.x
  lms/djangoapps/discussion/apps.py
  lms/djangoapps/discussion/django_comment_client/middleware.py
  lms/djangoapps/discussion/django_comment_client/permissions.py
  lms/djangoapps/discussion/django_comment_client/urls.py
  lms/djangoapps/discussion/django_comment_client/utils.py
  lms/djangoapps/discussion/tasks.py
  lms/djangoapps/discussion/urls.py
Labels: needs triage, open-source-contribution

#20530 INCR-245: Make compatible with Python 3.x without breaking Python 2.7…
  common/lib/capa/capa/safe_exec/safe_exec.py
  common/lib/capa/capa/safe_exec/tests/test_lazymod.py
  common/lib/capa/capa/safe_exec/tests/test_safe_exec.py
Labels: needs triage, open-source-contribution

#20833 INCR-480: Make compatible with Python 3.x and fixed line over length …
  lms/djangoapps/teams/__init__.py
  lms/djangoapps/teams/plugins.py
  lms/djangoapps/teams/search_indexes.py
  lms/djangoapps/teams/serializers.py
  lms/djangoapps/teams/views.py
Labels: awaiting prioritization, open-source-contribution

#20876 INCR-473: Make compatible with Python 3.x
  lms/djangoapps/instructor_task/subtasks.py
  lms/djangoapps/instructor_task/tasks_base.py
  lms/djangoapps/instructor_task/views.py
  lms/djangoapps/program_enrollments/management/commands/tests/test_expire_waiting_enrollments.py
  lms/djangoapps/program_enrollments/migrations/0005_canceled_not_withdrawn.py
  lms/djangoapps/program_enrollments/tests/test_tasks.py
Labels: needs triage, open-source-contribution

#20400 Split common/lib/chem into separate repository
  common/lib/chem/chem/__init__.py
  common/lib/chem/chem/chemcalc.py
  common/lib/chem/chem/chemtools.py
  common/lib/chem/chem/miller.py
  common/lib/chem/chem/tests.py
  common/lib/chem/setup.py
  docs/conf.py
  docs/docstrings/common_lib.rst
  requirements/edx-sandbox/base.in
  requirements/edx-sandbox/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/local.in
  requirements/edx/testing.txt
Labels: blocked by other work, needs triage, open-source-contribution

#20883 INCR-459: Run python-modernize and isort
  lms/djangoapps/course_blocks/api.py
  lms/djangoapps/course_blocks/usage_info.py
  lms/djangoapps/course_blocks/utils.py
  lms/djangoapps/course_goals/handlers.py
  lms/djangoapps/lms_xblock/migrations/0001_initial.py
Labels: needs triage, open-source-contribution

#20868 Incr 474
  lms/djangoapps/program_enrollments/management/commands/expire_waiting_enrollments.py
  lms/djangoapps/program_enrollments/models.py
  lms/djangoapps/program_enrollments/tasks.py
  lms/djangoapps/program_enrollments/utils.py
Labels: awaiting prioritization, open-source-contribution

#20871 Incr 475
  lms/djangoapps/discussion/notification_prefs/tests.py
  lms/djangoapps/program_enrollments/admin.py
  lms/djangoapps/program_enrollments/apps.py
Labels: needs triage, open-source-contribution

#20384 VideoModule to VideoBlock [SE-602]
  cms/djangoapps/contentstore/management/commands/tests/test_migrate_transcripts.py
  cms/djangoapps/contentstore/tests/test_contentstore.py
  cms/djangoapps/contentstore/views/tests/test_course_index.py
  cms/djangoapps/contentstore/views/tests/test_transcripts.py
  cms/envs/bok_choy.py
  cms/envs/common.py
  cms/envs/devstack.py
  cms/envs/production.py
  cms/static/sass/_shame.scss
  cms/static/sass/elements/_modal-window.scss
  cms/static/sass/elements/_xmodules.scss
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/editing_module.py
  common/lib/xmodule/xmodule/raw_module.py
  common/lib/xmodule/xmodule/static_content.py
  common/lib/xmodule/xmodule/tests/__init__.py
  common/lib/xmodule/xmodule/tests/test_video.py
  common/lib/xmodule/xmodule/tests/test_xblock_wrappers.py
  common/lib/xmodule/xmodule/video_module/bumper_utils.py
  common/lib/xmodule/xmodule/video_module/transcripts_utils.py
  common/lib/xmodule/xmodule/video_module/video_handlers.py
  common/lib/xmodule/xmodule/video_module/video_module.py
  common/lib/xmodule/xmodule/video_module/video_utils.py
  common/lib/xmodule/xmodule/video_module/video_xfields.py
  common/test/acceptance/pages/lms/video/video.py
  common/test/acceptance/pages/studio/video/video.py
  common/test/acceptance/tests/video/test_video_license.py
  common/test/acceptance/tests/video/test_video_module.py
  lms/djangoapps/courseware/management/commands/tests/test_dump_course.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/courseware/tests/test_video_handlers.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/courseware/tests/test_video_xml.py
  lms/envs/production.py
Labels: needs triage, open-source-contribution
