Repository openedx/edx-platform, pull requests merged in 2019-12, with the labels that each got.

#19941 Add api support to let users opt out of email updates
  lms/djangoapps/bulk_email/tests/test_views.py
  lms/djangoapps/bulk_email/urls.py
  lms/djangoapps/bulk_email/views.py
  lms/templates/bulk_email/unsubscribe.html
  lms/urls.py
  openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
  openedx/core/djangoapps/schedules/config.py
  openedx/core/djangoapps/schedules/resolvers.py
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
  openedx/core/djangolib/testing/utils.py
Labels: awaiting prioritization, open-source-contribution, waiting on author

#20684 Add last_login and date_joined to the student profile export
  lms/djangoapps/instructor/views/api.py
  lms/djangoapps/instructor_analytics/basic.py
Labels: engineering review, open-source-contribution

#22424 INCR-562 @require_certificate_permission parameters added
  lms/djangoapps/certificates/permissions.py
  lms/djangoapps/certificates/views/support.py
Labels: engineering review, open-source-contribution, waiting on author

#21166 [BB-1506] Use a callable as the default value for CourseEnrollment.mode
  common/djangoapps/course_modes/models.py
  common/djangoapps/student/migrations/0027_courseenrollment_mode_callable_default.py
  common/djangoapps/student/models.py
Labels: awaiting prioritization, open-source-contribution

#21197 BB-1744: Bump pymongo version and fix course export issue
  common/lib/xmodule/xmodule/contentstore/mongo.py
  common/lib/xmodule/xmodule/course_metadata_utils.py
  common/lib/xmodule/xmodule/modulestore/mongo/base.py
  common/lib/xmodule/xmodule/modulestore/mongo/draft.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/split.py
  common/lib/xmodule/xmodule/modulestore/tests/factories.py
  common/lib/xmodule/xmodule/modulestore/tests/test_mongo_call_count.py
  common/lib/xmodule/xmodule/modulestore/tests/test_split_mongo_mongo_connection.py
  common/lib/xmodule/xmodule/mongo_utils.py
  lms/djangoapps/dashboard/git_import.py
  lms/djangoapps/dashboard/sysadmin.py
  lms/djangoapps/verify_student/management/commands/tests/test_send_verification_expiry_email.py
  lms/djangoapps/verify_student/tests/test_services.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/paver.in
  requirements/edx/paver.txt
  requirements/edx/testing.txt
Labels: awaiting prioritization, open-source-contribution, waiting on author

#22607 fix uploaded image aspect ratio in tinymce
  common/static/css/tinymce-studio-content.css
Labels: awaiting prioritization, open-source-contribution

#22618 BB-1744: Remove flaky test related to MockS3Mixin [FOLLOW-UP]
  lms/djangoapps/verify_student/management/commands/tests/test_send_verification_expiry_email.py
Labels: needs triage, open-source-contribution

#21610 SE-1071 send user_logged_in signal from my_user_info
  lms/djangoapps/mobile_api/users/tests.py
  lms/djangoapps/mobile_api/users/views.py
Labels: engineering review, open-source-contribution

#22631 Safer CourseOverview.org filed matching
  openedx/core/djangoapps/content/course_overviews/models.py
Labels: awaiting prioritization, open-source-contribution
