Repository openedx/edx-platform, pull requests merged in 2019-02, with the labels that each got.

#19708 EDUCATOR-3930 fix video player speed adjustments
  common/lib/xmodule/xmodule/js/spec/video/video_player_spec.js
  common/lib/xmodule/xmodule/js/src/video/03_video_player.js
Labels: needs triage, open-source-contribution

#19631 tiny style modification
  lms/static/sass/_header.scss
Labels: awaiting prioritization, open-source-contribution

#19266 Bump xblock-drag-and-drop-v2 to v2.2.1 which includes i18n support in JS files
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: open-source-contribution, waiting on author

#19018 Add api support to let users opt out of email updates.
  lms/djangoapps/bulk_email/tests/test_views.py
  lms/djangoapps/bulk_email/urls.py
  lms/djangoapps/bulk_email/views.py
  lms/templates/bulk_email/unsubscribe.html
  lms/urls.py
  openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
  openedx/core/djangoapps/schedules/config.py
  openedx/core/djangoapps/schedules/resolvers.py
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
Labels: awaiting prioritization, open-source-contribution

#19385 Implement public cohort for anonymous and unenrolled users
  common/lib/xmodule/xmodule/tests/test_xblock_wrappers.py
  common/lib/xmodule/xmodule/x_module.py
  lms/djangoapps/course_blocks/transformers/library_content.py
  lms/djangoapps/course_blocks/utils.py
  lms/djangoapps/courseware/courses.py
  lms/djangoapps/courseware/models.py
  lms/djangoapps/courseware/tests/test_about.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/views/index.py
  lms/djangoapps/courseware/views/views.py
  lms/templates/courseware/course_about.html
  openedx/core/djangoapps/course_groups/tests/test_cohorts.py
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/views/course_home.py
  openedx/features/course_experience/views/course_home_messages.py
Labels: engineering review, open-source-contribution

#19773 Fixes flaky tests in schedules.tests.TestCourseUpdateResolver
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
Labels: awaiting prioritization, open-source-contribution

#19380 Add new Option to Show Answer Dropdown.
  cms/djangoapps/contentstore/features/problem-editor.py
  common/lib/xmodule/xmodule/capa_base.py
  common/lib/xmodule/xmodule/capa_base_constants.py
  common/lib/xmodule/xmodule/tests/test_capa_module.py
  common/test/acceptance/tests/studio/test_studio_problem_editor.py
Labels: open-source-contribution, waiting on author

#19763 INCR-40 use ipaddress instead of ipaddr
  openedx/core/djangoapps/embargo/forms.py
  openedx/core/djangoapps/embargo/models.py
  openedx/core/djangoapps/embargo/tests/test_forms.py
  openedx/core/djangoapps/embargo/tests/test_middleware.py
  openedx/core/djangoapps/embargo/tests/test_models.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, waiting on author

#19761 Fix Collapse All/Expand All translation
  openedx/features/course_experience/static/course_experience/js/CourseOutline.js
Labels: open-source-contribution, waiting on author

#19806 INCR-82 remove dependency on code_block_timer
  common/lib/xmodule/xmodule/modulestore/perf_tests/test_asset_import_export.py
  requirements/edx/development.in
  requirements/edx/development.txt
  scripts/dependencies/development.py
Labels: needs triage, open-source-contribution

#19409 Fix inconsistency in assumed data dir for course import
  openedx/core/lib/extract_tar.py
Labels: open-source-contribution, waiting on author

#19620 Old style exceptions --> new style for Python 3
  cms/djangoapps/contentstore/views/tabs.py
  common/djangoapps/course_modes/tests/test_views.py
  common/djangoapps/track/tests/test_util.py
  common/lib/capa/capa/xqueue_interface.py
  common/lib/sandbox-packages/loncapa/loncapa_check.py
  common/lib/symmath/symmath/formula.py
  common/lib/symmath/symmath/symmath_check.py
  common/lib/xmodule/xmodule/contentstore/content.py
  common/lib/xmodule/xmodule/modulestore/tests/factories.py
  lms/djangoapps/commerce/api/v0/views.py
  lms/djangoapps/courseware/management/commands/tests/test_dump_course.py
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/discussion_api/tests/utils.py
  lms/djangoapps/django_comment_client/base/views.py
  lms/djangoapps/edxnotes/tests.py
  lms/djangoapps/instructor/views/tools.py
  lms/djangoapps/mobile_api/tests/test_middleware.py
  lms/djangoapps/mobile_api/tests/test_model.py
  lms/djangoapps/shoppingcart/pdf.py
  openedx/core/djangoapps/external_auth/tests/test_ssl.py
  openedx/core/djangoapps/profile_images/tests/test_views.py
  openedx/core/djangoapps/user_api/accounts/tests/test_image_helpers.py
  pavelib/prereqs.py
  pavelib/quality.py
Labels: awaiting prioritization, open-source-contribution

#19628 INCR-29: Run python-modernize on common/lib/chem
  common/lib/chem/chem/chemcalc.py
  common/lib/chem/chem/chemtools.py
  common/lib/chem/chem/miller.py
  common/lib/chem/chem/tests.py
  common/lib/chem/setup.py
Labels: awaiting prioritization, open-source-contribution

#19052 Cohort discussion settings and roles management API
  lms/djangoapps/discussion_api/forms.py
  lms/djangoapps/discussion_api/serializers.py
  lms/djangoapps/discussion_api/tests/test_views.py
  lms/djangoapps/discussion_api/urls.py
  lms/djangoapps/discussion_api/views.py
Labels: awaiting prioritization, open-source-contribution

#19748 docs: s/javascript/JavaScript/
  docs/testing.rst
Labels: awaiting prioritization, open-source-contribution

#19622 Fix explicit tuple parameters for Python 3
  cms/djangoapps/contentstore/views/videos.py
  common/djangoapps/util/tests/test_date_utils.py
  common/test/acceptance/pages/studio/container.py
  common/test/acceptance/tests/studio/test_studio_container.py
  common/test/acceptance/tests/studio/test_studio_outline.py
  lms/djangoapps/instructor_analytics/csvs.py
  lms/djangoapps/teams/tests/test_models.py
  openedx/core/djangolib/tests/test_markup.py
Labels: awaiting prioritization, open-source-contribution

#19840 Missing named argument in formatting call
  lms/djangoapps/course_goals/models.py
Labels: awaiting prioritization, open-source-contribution

#19846 Fix date internationalization
  lms/templates/course.html
  lms/templates/courseware/course_about.html
Labels: awaiting prioritization, open-source-contribution

#19510 Bugfix: Text Input problem type expects numeric answer when correct answer starts with a number
  common/lib/xmodule/xmodule/js/spec/problem/edit_spec.js
  common/lib/xmodule/xmodule/js/src/problem/edit.js
Labels: awaiting prioritization, open-source-contribution, waiting on author

#19635 [BB-728] Add problem response report API
  lms/djangoapps/instructor/permissions.py
  lms/djangoapps/instructor/tests/test_api.py
  lms/djangoapps/instructor/urls.py
  lms/djangoapps/instructor/views/api.py
  lms/djangoapps/instructor/views/api_urls.py
  lms/djangoapps/instructor/views/instructor_dashboard.py
  lms/urls.py
Labels: engineering review, open-source-contribution

#19304 Convert (Email Change Confirmation) message to edx-ACE
  common/djangoapps/student/message_types.py
  common/djangoapps/student/tests/test_email.py
  common/djangoapps/student/views/management.py
  common/templates/student/edx_ace/emailchangeconfirmation/email/body.html
  common/templates/student/edx_ace/emailchangeconfirmation/email/body.txt
  common/templates/student/edx_ace/emailchangeconfirmation/email/from_name.txt
  common/templates/student/edx_ace/emailchangeconfirmation/email/head.html
  common/templates/student/edx_ace/emailchangeconfirmation/email/subject.txt
  common/test/test_sites/test_site/templates/emails/confirm_email_change.txt
  common/test/test_sites/test_site/templates/emails/email_change_subject.txt
  lms/templates/emails/confirm_email_change.txt
  lms/templates/emails/email_change_subject.txt
Labels: engineering review, open-source-contribution

#19852 Handle out-of-memory exception on Sysadmin Courses
  lms/djangoapps/dashboard/sysadmin.py
Labels: awaiting prioritization, open-source-contribution

#19880 SE-800 Wraps the email header in a block so it can be themed
  openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
Labels: engineering review, open-source-contribution

#19315 OSPR-2818 - Add Contact Us form customization options (BB-548)
  lms/djangoapps/branding/api.py
  lms/djangoapps/branding/tests/test_api.py
  lms/djangoapps/support/views/contact_us.py
Labels: engineering review, open-source-contribution, waiting on author

#19885 Set the default language of the courses through config files
  cms/envs/production.py
Labels: awaiting prioritization, open-source-contribution
