Repository openedx/edx-platform, pull requests merged in 2019-01, with the labels that each got.

#19396 Faster "npm install" without progress bar
  .npmrc
Labels: awaiting prioritization, needs triage, open-source-contribution

#18838 OC-5087 Create a staff-only API to list all course enrollments
  common/djangoapps/enrollment/forms.py
  common/djangoapps/enrollment/paginators.py
  common/djangoapps/enrollment/serializers.py
  common/djangoapps/enrollment/tests/fixtures/course-enrollments-api-list-valid-data.json
  common/djangoapps/enrollment/tests/test_views.py
  common/djangoapps/enrollment/urls.py
  common/djangoapps/enrollment/views.py
Labels: engineering review, open-source-contribution

#19329 BB-547 - Fix certificate api when retrieving certificates from deleted courses
  lms/djangoapps/certificates/api.py
  lms/djangoapps/certificates/tests/test_api.py
Labels: open-source-contribution, waiting on author

#19571 SE-614 Adds optional args to create_dot_application command
  openedx/core/djangoapps/oauth_dispatch/management/commands/create_dot_application.py
  openedx/core/djangoapps/oauth_dispatch/management/commands/tests/test_create_dot_application.py
Labels: engineering review, open-source-contribution

#19591 Use print() function in both Python 2 and Python 3
  cms/djangoapps/contentstore/management/commands/force_publish.py
  cms/djangoapps/contentstore/tests/test_courseware_index.py
  cms/djangoapps/contentstore/tests/test_import.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/tests/test_group_configurations.py
  common/djangoapps/student/models.py
  common/djangoapps/terrain/stubs/start.py
  common/djangoapps/xblock_django/management/commands/ensure_indexes.py
  common/lib/capa/capa/checker.py
  common/lib/capa/capa/tests/test_shuffle.py
  common/lib/chem/chem/tests.py
  common/lib/sandbox-packages/eia.py
  common/lib/xmodule/xmodule/contentstore/utils.py
  common/lib/xmodule/xmodule/modulestore/perf_tests/generate_asset_xml.py
  common/lib/xmodule/xmodule/modulestore/perf_tests/generate_report.py
  common/lib/xmodule/xmodule/modulestore/tests/factories.py
  common/lib/xmodule/xmodule/modulestore/xml_importer.py
  common/lib/xmodule/xmodule/tests/test_conditional.py
  common/lib/xmodule/xmodule/tests/test_course_module.py
  common/lib/xmodule/xmodule/tests/test_export.py
  common/lib/xmodule/xmodule/tests/test_import.py
  common/lib/xmodule/xmodule/tests/test_stringify.py
  lms/djangoapps/bulk_email/tests/test_tasks.py
  lms/djangoapps/certificates/management/commands/gen_cert_report.py
  lms/djangoapps/discussion/views.py
  lms/djangoapps/django_comment_client/base/views.py
  lms/djangoapps/experiments/utils.py
  lms/djangoapps/instructor/tests/test_api.py
  lms/djangoapps/instructor/tests/test_enrollment.py
  lms/djangoapps/instructor_analytics/tests/test_distributions.py
  lms/djangoapps/rss_proxy/tests/test_views.py
  lms/djangoapps/rss_proxy/views.py
  lms/djangoapps/shoppingcart/management/commands/retire_order.py
  lms/djangoapps/verify_student/management/commands/retry_failed_photo_verifications.py
  openedx/core/djangoapps/credentials/management/commands/tests/test_notify_credentials.py
  openedx/core/djangoapps/external_auth/tests/test_openid_provider.py
  openedx/core/djangoapps/heartbeat/tests/test_heartbeat.py
  openedx/core/djangoapps/theming/paver_helpers.py
  openedx/core/djangoapps/theming/tests/test_util.py
  openedx/core/djangoapps/util/management/commands/print_setting.py
  openedx/core/djangoapps/util/management/commands/reset_db.py
  openedx/core/djangoapps/verified_track_content/management/commands/swap_from_auto_track_cohort_pilot.py
  openedx/core/lib/xblock_builtin/xblock_discussion/tests.py
  openedx/features/course_duration_limits/access.py
  openedx/tests/xblock_integration/test_external_xblocks.py
  openedx/tests/xblock_integration/xblock_testcase.py
  pavelib/acceptance_test.py
  pavelib/bok_choy.py
  pavelib/i18n.py
  pavelib/paver_tests/test_paver_quality.py
  pavelib/prereqs.py
  pavelib/quality.py
  pavelib/tests.py
  pavelib/utils/test/bokchoy_utils.py
  pavelib/utils/test/suites/bokchoy_suite.py
  pavelib/utils/test/suites/suite.py
  pavelib/utils/test/utils.py
  scripts/show_events.py
  scripts/xblock/xblock_counts.py
Labels: open-source-contribution, waiting on author

#19253 Add OAuth2 and JWT support to XBlock handlers
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/courseware/tests/factories.py
  lms/djangoapps/courseware/tests/test_entrance_exam.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/courseware/tests/test_views.py
Labels: engineering review, open-source-contribution

#19106 Fix error when saving CourseEnrollment in admin
  common/djangoapps/course_modes/admin.py
  common/djangoapps/student/admin.py
  common/djangoapps/student/tests/test_admin_views.py
Labels: awaiting prioritization, open-source-contribution

#19699 annotate feature toggle require_course_email_auth
  lms/djangoapps/bulk_email/models.py
Labels: needs triage, open-source-contribution

#19680 INCR-2 Unpin glob2 and run make upgrade
  requirements/edx-sandbox/base.txt
  requirements/edx-sandbox/shared.txt
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/pip-tools.txt
  requirements/edx/testing.txt
Labels: INCR

#19686 INCR-11 Unpin mailsnake and run make upgrade
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: INCR

#19702 fixup require_course_email_auth annotation
  lms/djangoapps/bulk_email/models.py
Labels: needs triage, open-source-contribution

#19707 add feature toggle annotations for ENABLE_SYSADMIN_DASHBOARD
  lms/envs/common.py
Labels: needs triage, open-source-contribution

#19710 Hackathon - feature toggles - adds feature_toggle_creation_date to annotations
  feature_annotations.yaml
  lms/djangoapps/bulk_email/models.py
  lms/envs/common.py
  openedx/features/course_duration_limits/config.py
Labels: needs triage, open-source-contribution

#19700 INCR-13 Unpin pygraphviz and run make upgrade
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: INCR
