Repository openedx/edx-platform, pull requests merged in 2019-03, with the labels that each got.

#19837 Show enroll links on public courses only if self enrollment allowed
  lms/djangoapps/courseware/views/views.py
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/views/course_home_messages.py
Labels: engineering review, open-source-contribution

#19845 Make the studio login over the lms optional using a feature flag
  cms/envs/common.py
  cms/envs/production.py
  cms/templates/widgets/header.html
  cms/templates/widgets/user_dropdown.html
  lms/envs/test.py
  openedx/core/djangoapps/user_authn/views/logout.py
Labels: open-source-contribution, waiting on author

#19507 [BB-753] Fix issue with multiple responses for a single user returned by generate_report_data
  lms/djangoapps/instructor_task/tasks_helper/grades.py
  lms/djangoapps/instructor_task/tests/test_tasks_helper.py
Labels: engineering review, open-source-contribution

#19988 Fix bug: error messages are not shown in Course Team Management
  lms/static/js/instructor_dashboard/membership.js
  lms/static/js/spec/instructor_dashboard/membership_auth_spec.js
Labels: awaiting prioritization, open-source-contribution

#20006 [INCR-16] upgrade shapely
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/paver.txt
  requirements/edx/testing.txt
Labels: awaiting prioritization, open-source-contribution, waiting on author

#19621 ur'strings' are syntax errors in Python 3
  common/djangoapps/static_replace/__init__.py
  common/lib/calc/calc/preview.py
  common/lib/xmodule/xmodule/modulestore/store_utilities.py
  lms/djangoapps/grades/tests/test_signals.py
  openedx/core/lib/url_utils.py
Labels: engineering review, open-source-contribution

#19023 added fix for broken 'enroll in class' button on about course page
  lms/static/js/course_info.js
  lms/static/sass/multicourse/_course_about.scss
Labels: engineering review, open-source-contribution

#20027 Use ==/!= to compare str, bytes, and int literals
  cms/djangoapps/contentstore/views/tests/test_assets.py
  common/djangoapps/django_comment_common/migrations/0003_enable_forums.py
  common/djangoapps/terrain/ui_helpers.py
  common/lib/xmodule/xmodule/fields.py
  lms/djangoapps/grades/course_grade_factory.py
  scripts/xsslint/xsslint/visitors.py
Labels: open-source-contribution, waiting on author

#20059 [WIP] [INCR-14] Bump python-memcached for Python 3 support
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/paver.in
  requirements/edx/paver.txt
  requirements/edx/testing.txt
Labels: awaiting prioritization, open-source-contribution

#20081 INCR-107: Restrict pysqlite to python 2.7
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#20082 INCR-39: Remove django-memcached-hashring
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#20079 INCR-41: Replace pdfminer with pdfminer.six
  pavelib/prereqs.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#20080 [INCR-180] Python 3.x compatibility changes - openedx/core/djangoapps/theming/tests
  openedx/core/djangoapps/theming/tests/test_commands.py
  openedx/core/djangoapps/theming/tests/test_finders.py
  openedx/core/djangoapps/theming/tests/test_helpers.py
  openedx/core/djangoapps/theming/tests/test_microsites.py
  openedx/core/djangoapps/theming/tests/test_middleware.py
  openedx/core/djangoapps/theming/tests/test_storage.py
  openedx/core/djangoapps/theming/tests/test_theme_locales.py
  openedx/core/djangoapps/theming/tests/test_theme_style_overrides.py
  openedx/core/djangoapps/theming/tests/test_util.py
  openedx/core/djangoapps/theming/tests/test_views.py
Labels: needs triage, open-source-contribution

#20102 INCR-127: Migrating common/djangoapps/course_action_state
  common/djangoapps/course_action_state/managers.py
  common/djangoapps/course_action_state/migrations/0001_initial.py
  common/djangoapps/course_action_state/models.py
  common/djangoapps/course_action_state/tests/test_managers.py
  common/djangoapps/course_action_state/tests/test_rerun_manager.py
Labels: awaiting prioritization, open-source-contribution

#20104 INCR-179 Migrating openedx/features/journals
  openedx/features/journals/api.py
  openedx/features/journals/apps.py
  openedx/features/journals/tests/test_journal_xblock.py
  openedx/features/journals/tests/test_learner_dashboard.py
  openedx/features/journals/tests/test_marketing_views.py
  openedx/features/journals/tests/utils.py
  openedx/features/journals/urls.py
  openedx/features/journals/views/journal_xblock.py
  openedx/features/journals/views/learner_dashboard.py
  openedx/features/journals/views/marketing.py
Labels: awaiting prioritization, open-source-contribution

#20105 INCR-118: Run python-modernize on openedx/core/djangoapps/content/cou…
  openedx/core/djangoapps/content/course_overviews/migrations/0001_initial.py
  openedx/core/djangoapps/content/course_overviews/migrations/0002_add_course_catalog_fields.py
  openedx/core/djangoapps/content/course_overviews/migrations/0003_courseoverviewgeneratedhistory.py
  openedx/core/djangoapps/content/course_overviews/migrations/0004_courseoverview_org.py
  openedx/core/djangoapps/content/course_overviews/migrations/0005_delete_courseoverviewgeneratedhistory.py
  openedx/core/djangoapps/content/course_overviews/migrations/0006_courseoverviewimageset.py
  openedx/core/djangoapps/content/course_overviews/migrations/0007_courseoverviewimageconfig.py
  openedx/core/djangoapps/content/course_overviews/migrations/0008_remove_courseoverview_facebook_url.py
  openedx/core/djangoapps/content/course_overviews/migrations/0009_readd_facebook_url.py
  openedx/core/djangoapps/content/course_overviews/migrations/0010_auto_20160329_2317.py
  openedx/core/djangoapps/content/course_overviews/migrations/0011_courseoverview_marketing_url.py
  openedx/core/djangoapps/content/course_overviews/migrations/0012_courseoverview_eligible_for_financial_aid.py
  openedx/core/djangoapps/content/course_overviews/migrations/0013_courseoverview_language.py
  openedx/core/djangoapps/content/course_overviews/migrations/0014_courseoverview_certificate_available_date.py
Labels: awaiting prioritization, open-source-contribution

#20098 Cache courses list on sysadmin courses page
  lms/djangoapps/dashboard/sysadmin.py
Labels: awaiting prioritization, open-source-contribution
