Repository openedx/edx-platform, pull requests merged in 2019-09, with the labels that each got.

#21527 BOM-275
  lms/djangoapps/courseware/tests/test_navigation.py
Labels: needs triage, open-source-contribution

#21543 BOM-119
  lms/djangoapps/course_api/tests/test_views.py
Labels: awaiting prioritization, open-source-contribution

#21544 BOM-127
  lms/djangoapps/bulk_enroll/tests/test_views.py
  lms/djangoapps/bulk_enroll/views.py
Labels: open-source-contribution, waiting on author

#21571 BOM-156 | Fixes for response decoding (Python 3.5)
  lms/djangoapps/courseware/tests/test_about.py
Labels: open-source-contribution, waiting on author

#21596 BOM-423 | Fixes for Python 3 decoding
  lms/djangoapps/class_dashboard/tests/test_views.py
Labels: open-source-contribution, waiting on author

#21600 BOM-442 | Response decoding for RssProxyViewTests
  lms/djangoapps/rss_proxy/tests/test_views.py
Labels: needs triage, open-source-contribution

#21598 BOM-447 | Updates for TypeError in Python 3
  cms/djangoapps/contentstore/tests/test_orphan.py
Labels: needs triage, open-source-contribution

#21597 BOM-429 | decoding for CSV response
  lms/djangoapps/instructor_analytics/tests/test_csvs.py
Labels: open-source-contribution, waiting on author

#21677 SE-1553 conditionally run migration on CSMH Extended table
  lms/djangoapps/courseware/migrations/0011_csm_id_bigint.py
Labels: awaiting prioritization, open-source-contribution

#21697 Disable edxnotes for blockstore runtime.
  lms/djangoapps/edxnotes/decorators.py
  lms/djangoapps/edxnotes/tests.py
Labels: needs triage, open-source-contribution

#21286 Fix the progress graph y-axis - window resize formatting problem in Ironwood
  lms/templates/courseware/progress_graph.js
Labels: awaiting prioritization, open-source-contribution

#21633 SE-1463 add djangoapps.heartbeat to INSTALLED_APPS by default
  cms/envs/common.py
  lms/envs/common.py
Labels: engineering review, open-source-contribution, waiting on author
