Repository openedx/edx-platform, pull requests merged in 2019-11, with the labels that each got.

#22226 Fix static urls in pdf_viewer.html to correctly display pdf viewer fo…
  lms/templates/pdf_viewer.html
Labels: awaiting prioritization, open-source-contribution

#22262 Fix invocation of (edx.)HtmlUtils.ensureHtml
  lms/templates/login.html
Labels: awaiting prioritization, open-source-contribution

#22271 Improve load times of Django Admin - CourseMode
  common/djangoapps/course_modes/admin.py
Labels: open-source-contribution, waiting on author

#20186 BB-755 Check if username is already unicode.
  common/djangoapps/student/models.py
  common/djangoapps/student/tests/test_admin_views.py
Labels: engineering review, needs triage, open-source-contribution

#22368 Convert @require_certificate_permission to use user.has_perm
  lms/djangoapps/certificates/permissions.py
  lms/djangoapps/certificates/views/support.py
Labels: awaiting prioritization, open-source-contribution

#19610 Hide the re-index button for non-global staff
  cms/djangoapps/contentstore/views/course.py
Labels: needs triage, open-source-contribution, waiting on author

#22091 Activation email to ace
  cms/templates/emails/activation_email.txt
  cms/templates/emails/activation_email_subject.txt
  common/djangoapps/student/helpers.py
  common/djangoapps/student/message_types.py
  common/djangoapps/student/tasks.py
  common/djangoapps/student/tests/test_email.py
  common/djangoapps/student/tests/test_tasks.py
  common/djangoapps/student/views/management.py
  common/templates/student/edx_ace/accountactivation/email/body.html
  common/templates/student/edx_ace/accountactivation/email/body.txt
  common/templates/student/edx_ace/accountactivation/email/from_name.txt
  common/templates/student/edx_ace/accountactivation/email/head.html
  common/templates/student/edx_ace/accountactivation/email/subject.txt
  common/test/test_sites/test_site/templates/emails/activation_email.txt
  common/test/test_sites/test_site/templates/emails/activation_email_subject.txt
  lms/templates/emails/activation_email.txt
  lms/templates/emails/activation_email_subject.txt
  openedx/core/djangoapps/user_authn/views/login.py
Labels: awaiting prioritization, engineering review, open-source-contribution
