Repository openedx/edx-platform, pull requests merged in 2020-09, with the labels that each got.

#24399 [BD-29] [TNL-7261] Course Outline API: Beta User Support
  openedx/core/djangoapps/content/learning_sequences/api/outlines.py
  openedx/core/djangoapps/content/learning_sequences/api/processors/schedule.py
  openedx/core/djangoapps/content/learning_sequences/api/tests/test_data.py
  openedx/core/djangoapps/content/learning_sequences/api/tests/test_outlines.py
  openedx/core/djangoapps/content/learning_sequences/data.py
  openedx/core/djangoapps/content/learning_sequences/migrations/0005_coursecontext_days_early_for_beta.py
  openedx/core/djangoapps/content/learning_sequences/models.py
  openedx/core/djangoapps/content/learning_sequences/tasks.py
  openedx/core/djangoapps/content/learning_sequences/tests/test_views.py
  openedx/core/djangoapps/content/learning_sequences/views.py
Labels: blended, engineering review

#24055 Fix creation of LTIProviderConfig object in admin
  common/djangoapps/third_party_auth/models.py
Labels: engineering review, open-source-contribution

#24675 [BD-29] [TNL-7061] remove bypass home
  common/lib/xmodule/xmodule/course_module.py
  common/lib/xmodule/xmodule/tests/test_course_module.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/views/views.py
Labels: blended, engineering review

#24631 [BD-10] [DEPR-92] Remove edx-pattern-library package.
  package-lock.json
  package.json
Labels: blended, needs triage

#24237 Fix problem viewing when CSMH is disabled
  lms/djangoapps/courseware/migrations/0011_csm_id_bigint.py
Labels: cc-reviewer, open edx community review, open-source-contribution

#24197 Change isnumeric to isdigit in NumericValidator
  common/djangoapps/util/password_policy_validators.py
Labels: engineering review, open-source-contribution

#24818 [BD-18] Optimize paver settings call
  openedx/core/djangoapps/util/management/commands/print_setting.py
  pavelib/assets.py
  pavelib/paver_tests/test_servers.py
  pavelib/utils/envs.py
Labels: blended, needs triage

#24963 Fix documentation for ENABLE_LEARNER_RECORDS
  openedx/core/djangoapps/credentials/docs/site_config.rst
Labels: needs triage, open-source-contribution

#24867 [BB-2967] Remove report path from task output data
  common/static/common/js/components/BlockBrowser/data/reducers/index.js
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/components/Main/Main.jsx
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/components/Main/MainContainer.jsx
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/components/ReportStatus/ReportStatus.jsx
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/data/actions/constants.js
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/data/actions/problemResponses.js
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/data/api/client.js
  lms/djangoapps/instructor/static/instructor/ProblemBrowser/data/reducers/index.js
  lms/djangoapps/instructor_task/tasks_helper/grades.py
  lms/djangoapps/instructor_task/tasks_helper/utils.py
  lms/templates/instructor/instructor_dashboard_2/data_download.html
Labels: engineering review, open-source-contribution

#24969 Upgrade to 3.8.1
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: canvas, online campus

#24611 [BD-04] Convert LibraryContent XModule to XBlock
  cms/djangoapps/contentstore/views/item.py
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/library_content_module.py
  common/lib/xmodule/xmodule/library_tools.py
  common/lib/xmodule/xmodule/static_content.py
  common/lib/xmodule/xmodule/tests/test_course_module.py
  common/lib/xmodule/xmodule/tests/test_library_content.py
  lms/djangoapps/course_blocks/transformers/library_content.py
Labels: blended, waiting on author

#24952 [BD-21] Simplify hack to obtain waffle module names
  cms/djangoapps/contentstore/config/waffle.py
  cms/djangoapps/contentstore/views/item.py
  cms/djangoapps/contentstore/views/videos.py
  cms/djangoapps/models/settings/waffle.py
  common/djangoapps/student/admin.py
  common/djangoapps/student/views/dashboard.py
  lms/djangoapps/course_api/__init__.py
  lms/djangoapps/course_api/blocks/toggles.py
  lms/djangoapps/course_home_api/toggles.py
  lms/djangoapps/courseware/toggles.py
  lms/djangoapps/experiments/flags.py
  lms/djangoapps/experiments/tests/test_flags.py
  lms/djangoapps/experiments/utils.py
  lms/djangoapps/experiments/views_custom.py
  lms/djangoapps/grades/config/waffle.py
  lms/djangoapps/instructor_task/config/waffle.py
  lms/djangoapps/teams/waffle.py
  lms/djangoapps/verify_student/toggles.py
  openedx/core/djangoapps/models/config/waffle.py
  openedx/core/djangoapps/programs/__init__.py
  openedx/core/djangoapps/schedules/config.py
  openedx/core/djangoapps/user_api/accounts/toggles.py
  openedx/core/djangoapps/user_authn/config/waffle.py
  openedx/core/djangoapps/user_authn/views/register.py
  openedx/core/djangoapps/video_pipeline/config/waffle.py
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/core/djangoapps/waffle_utils/tests/test_init.py
  openedx/core/djangoapps/waffle_utils/tests/test_testutils.py
  openedx/core/djangoapps/waffle_utils/tests/test_views.py
  openedx/core/lib/request_utils.py
  openedx/features/course_experience/__init__.py
  openedx/features/discounts/applicability.py
  openedx/features/enterprise_support/utils.py
  openedx/features/learner_profile/toggles.py
Labels: blended, needs triage

#24749 [BD-29] [TNL-7139] Styling Update to Existing Course Content Search Page
  lms/static/sass/features/_course-search.scss
  openedx/features/course_search/static/course_search/js/spec/course_search_spec.js
  openedx/features/course_search/static/course_search/js/views/search_item_view.js
  openedx/features/course_search/static/course_search/js/views/search_results_view.js
  openedx/features/course_search/static/course_search/templates/course_search_item.underscore
  openedx/features/course_search/static/course_search/templates/course_search_results.underscore
Labels: blended, changes requested

#24815 [BD-21] Document feature toggles
  cms/djangoapps/contentstore/config/waffle.py
  cms/envs/common.py
  doc.rst.j2
  lms/djangoapps/bulk_email/models.py
  lms/djangoapps/course_api/__init__.py
  lms/djangoapps/course_api/blocks/toggles.py
  lms/djangoapps/courseware/toggles.py
  lms/djangoapps/discussion/config/settings.py
  lms/djangoapps/experiments/utils.py
  lms/djangoapps/experiments/views_custom.py
  lms/djangoapps/grades/api.py
  lms/djangoapps/grades/config/models.py
  lms/djangoapps/grades/config/waffle.py
  lms/djangoapps/grades/services.py
  lms/djangoapps/verify_student/toggles.py
  lms/envs/common.py
  openedx/core/djangoapps/user_api/accounts/toggles.py
  openedx/core/djangoapps/user_authn/config/waffle.py
  openedx/core/djangoapps/user_authn/views/register.py
  openedx/core/djangoapps/video_config/models.py
  openedx/core/djangoapps/video_pipeline/api.py
  openedx/core/djangoapps/video_pipeline/config/waffle.py
  openedx/core/djangoapps/video_pipeline/models.py
  openedx/core/djangoapps/video_pipeline/tests/test_api.py
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/features/course_duration_limits/models.py
  openedx/features/course_experience/__init__.py
  openedx/features/course_experience/waffle.py
  openedx/features/discounts/applicability.py
  openedx/features/learner_profile/toggles.py
Labels: blended, needs triage

#23296 Add USER_ACCOUNT_ACTIVATED signal
  common/djangoapps/student/models.py
  common/djangoapps/student/tests/test_activate_account.py
  openedx/core/djangoapps/signals/signals.py
Labels: engineering review, open-source-contribution

#25016 Replace all .(lms|cms).(\w+|_)?\.json to .(lms|cms).(\w+|_)?\.yml
  common/djangoapps/third_party_auth/migrations/0004_auto_20200919_0955.py
  common/djangoapps/third_party_auth/models.py
  docs/guides/frontend/static_assets.rst
  lms/djangoapps/branding/api.py
  lms/envs/common.py
  themes/README.rst
Labels: open-source-contribution, waiting on author

#24208 (Problem Input) should always be LTR
  common/lib/xmodule/xmodule/css/capa/display.scss
Labels: engineering review, open-source-contribution

#24207 Resolve errors in browser console caused by Instructor Dashboard
  lms/static/js/instructor_dashboard/instructor_dashboard.js
Labels: engineering review, open-source-contribution

#25067 upgrade edx-enterprise 3.8.18
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: blackboard

#24919 [BD-14] [SE-2931] Adjust user access API endpoints for Libraries v2
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/urls.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: blended, ready to merge

#24861 [BD-14] SE-2927: Add type field/constraint to to libraries v2.
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/constants.py
  openedx/core/djangoapps/content_libraries/libraries_index.py
  openedx/core/djangoapps/content_libraries/migrations/0003_contentlibrary_type.py
  openedx/core/djangoapps/content_libraries/models.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: blended, ready to merge

#23731 Move Celery check task to the high priority queue
  cms/envs/common.py
  cms/envs/production.py
  lms/envs/common.py
  lms/envs/production.py
  openedx/core/djangoapps/heartbeat/tasks.py
Labels: changes requested, open-source-contribution

#24991 [BB-2924] Added a constant to help modify countries list in drop-down
  lms/envs/common.py
Labels: cc-reviewer, open edx community review, open-source-contribution

#25089 LX-1578 Enable the i18n service for the Blockstore service
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
Labels: open edx community review, open-source-contribution
