Repository openedx/edx-platform, pull requests merged in 2020-05, with the labels that each got.

#23861 CRI-196 Quiet deprecation warnings from imp and courseware modules
  cms/envs/common.py
  lms/djangoapps/bulk_email/views.py
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#23922 Fix naive offset-naive/aware error in asset compilation [CRI-191]
  openedx/core/lib/xblock_pipeline/finder.py
Labels: needs triage, open-source-contribution

#23911 Missing translation function call
  common/lib/xmodule/xmodule/capa_base.py
Labels: awaiting prioritization, engineering review, open-source-contribution

#23907 Fix DeprecationWarning: Please use assertNotRegex instead
  cms/djangoapps/contentstore/views/tests/test_item.py
  cms/djangoapps/contentstore/views/tests/test_preview.py
  lms/djangoapps/commerce/tests/test_views.py
  lms/djangoapps/dashboard/tests/test_sysadmin.py
Labels: awaiting prioritization, open-source-contribution

#23908 Fix DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead
  cms/djangoapps/contentstore/management/commands/tests/test_cleanup_assets.py
Labels: awaiting prioritization, open-source-contribution

#23909 Fix DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/experiments/utils.py
  lms/djangoapps/lti_provider/outcomes.py
Labels: awaiting prioritization, open-source-contribution

#23924 Update the LibraryLocator attribute from 'course' to 'library'
  openedx/core/djangoapps/content/block_structure/tests/test_signals.py
Labels: awaiting prioritization, open-source-contribution

#23929 Fix RemovedInDjango30Warning: cookie_date() is deprecated in favor of http_date(), which follows the format of the latest RFC
  openedx/core/djangoapps/user_authn/cookies.py
Labels: awaiting prioritization, open-source-contribution, waiting on author

#23945 Fix DeprecationWarning: count is deprecated. Use Collection.count_documents instead
  common/lib/xmodule/xmodule/modulestore/mongo/draft.py
  common/lib/xmodule/xmodule/modulestore/tests/test_split_modulestore.py
Labels: awaiting prioritization, open-source-contribution

#21507 [BB-1637] Pass the referer from the client to the YouTube API
  common/lib/xmodule/xmodule/video_module/video_handlers.py
  lms/djangoapps/courseware/views/views.py
Labels: awaiting prioritization, open-source-contribution

#22539 Enable auto start for HLS if autoadvance is set
  common/lib/xmodule/xmodule/js/src/video/02_html5_hls_video.js
Labels: open-source-contribution, waiting on author

#22358 SE-1839 Allow overriding SEARCH_FILTER_GENERATOR
  lms/envs/production.py
Labels: engineering review, open-source-contribution

#23889 [BD-6] Add python 3.8 and django30 to tox.ini and remove django111, django20…
  requirements/edx/django111.txt
  requirements/edx/django21.txt
  requirements/edx/django30.txt
  tox.ini
Labels: needs triage, open-source-contribution

#23814 Check contentlibrary permissions only if user is logged in
  openedx/core/djangoapps/content_libraries/permissions.py
  openedx/core/tests/test_admin_view.py
Labels: awaiting prioritization, open-source-contribution

#23951 [BD-10] DEPR-67 Remove pattern library of programs.html
  lms/djangoapps/learner_dashboard/views.py
  lms/static/sass/_build-learner-dashboard.scss
  lms/static/sass/bootstrap/_legacy.scss
  lms/static/sass/bootstrap/elements/_program-card.scss
  lms/static/sass/bootstrap/lms-main.scss
  lms/static/sass/views/_program-list.scss
  lms/templates/learner_dashboard/programs.html
Labels: needs triage, open-source-contribution

#24026 [CRI-174] [BB-2402] Fix LTI issues due to duplicated Content-Length header
  lms/djangoapps/lti_provider/outcomes.py
Labels: needs triage, open-source-contribution

#23697 Sysadmin Dashboard ADR
  lms/djangoapps/dashboard/decisions/0001-sysadmin-dashboard.rst
Labels: open-source-contribution, waiting on author

#24027 [BD-10] Add uses_pattern_library property to EdxFragmentView
  openedx/core/djangoapps/plugin_api/views.py
Labels: needs triage, open-source-contribution

#24068 Added 'with' statement to close file before returning
  openedx/core/djangoapps/site_configuration/management/commands/create_or_update_site_configuration.py
Labels: awaiting prioritization, open-source-contribution
