Repository openedx/edx-platform, pull requests merged in 2020-07, with the labels that each got.

#24376 Juniper: Downgrade pycontracts to 1.8.12
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: community manager review, open-source-contribution

#24157 [BD-10] [DEPR-83][DEPR-81] Remove pattern library of course_home.py
  openedx/features/course_experience/views/course_home.py
Labels: needs triage, open-source-contribution

#24379 [BD-6] Use PyPi release of django-ratelimit
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: blended, needs triage

#24452 [BD-6] Upgrade packages [codejail]
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: blended, needs triage

#24218 [BD-4] Convert WordCloud XModule into WordCloud XBlock. [SE-2722]
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/static_content.py
  common/lib/xmodule/xmodule/tests/test_word_cloud.py
  common/lib/xmodule/xmodule/tests/test_xblock_wrappers.py
  common/lib/xmodule/xmodule/word_cloud_module.py
  lms/djangoapps/courseware/tests/test_word_cloud.py
Labels: blended, changes requested

#23910 SE-2589 fix AttributeError: 'LibraryLocatorV2' object has no attribute 'make_asset_key'
  common/lib/xmodule/xmodule/video_module/transcripts_utils.py
  common/lib/xmodule/xmodule/video_module/video_module.py
  lms/djangoapps/courseware/tests/test_video_handlers.py
Labels: changes requested, open-source-contribution

#24173 [BD-10] [DEPR-72] Remove pattern library of course_search.py
  lms/static/sass/features/_course-experience.scss
  openedx/features/course_search/templates/course_search/course-search-fragment.html
  openedx/features/course_search/views/course_search.py
Labels: blended

#24396 [BD-29] TNL-7260 LearningSequences Course Outline makes sequences with hide_after_due inaccessible after due date
  openedx/core/djangoapps/content/learning_sequences/api/data.py
  openedx/core/djangoapps/content/learning_sequences/api/outlines.py
  openedx/core/djangoapps/content/learning_sequences/api/processors/schedule.py
  openedx/core/djangoapps/content/learning_sequences/api/tests/test_data.py
  openedx/core/djangoapps/content/learning_sequences/api/tests/test_outlines.py
  openedx/core/djangoapps/content/learning_sequences/migrations/0002_coursesectionsequence_inaccessible_after_due.py
  openedx/core/djangoapps/content/learning_sequences/models.py
  openedx/core/djangoapps/content/learning_sequences/tasks.py
  openedx/core/djangoapps/content/learning_sequences/views.py
Labels: blended, changes requested

#24276 [BD-14] Limit number of blocks allowed in content libraries
  cms/djangoapps/contentstore/views/item.py
  cms/djangoapps/contentstore/views/tests/test_library.py
  cms/envs/common.py
  cms/envs/production.py
  lms/envs/common.py
  lms/envs/production.py
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
Labels: open-source-contribution, waiting on author

#24395 Fix profile image URLs for image storage on non-public S3 buckets
  openedx/core/djangoapps/user_api/accounts/image_helpers.py
Labels: awaiting prioritization, open-source-contribution

#24277 Fix broken tests due to invalid field name
  openedx/core/djangoapps/content_libraries/permissions.py
Labels: changes requested, open-source-contribution

#24233 [BD-10] [DEPR-65][DEPR-74] Remove pattern library of course_bookmarks.py
  lms/static/sass/bootstrap/_layouts.scss
  lms/static/sass/bootstrap/_legacy.scss
  lms/static/sass/bootstrap/elements/_pagination.scss
  lms/static/sass/bootstrap/lms-main.scss
  lms/static/sass/features/_bookmarks.scss
  openedx/features/course_bookmarks/templates/course_bookmarks/course-bookmarks.html
  openedx/features/course_bookmarks/views/course_bookmarks.py
Labels: blended

#24497 [BD-6] Upgrade codejail
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: blended, needs triage

#24462 [BD-6] Use updated version of acid xblock.
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: blended, needs triage

#24496 Fix profile image URLs for image storage on non-public S3 buckets
  openedx/core/djangoapps/user_api/accounts/image_helpers.py
Labels: needs triage, open-source-contribution

#24492 [BD-06] Update Rate XBlock version to support python 3.8.
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24393 [BD-29] TNL-7303 Add course license details to Courseware API
  openedx/core/djangoapps/courseware_api/serializers.py
  openedx/core/djangoapps/courseware_api/views.py
Labels: blended, needs triage

#24369 [BD-10] [DEPR-73] Remove pattern library of learner_achievements.
  openedx/features/learner_profile/views/learner_achievements.py
Labels: blended

#24525 [BD-29] [TNL-6993] [BB-2602] Fix failing non-indexable tests
  cms/djangoapps/contentstore/tests/test_courseware_index.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24176 Removed font reference from edx-pattern-library in styles.
  cms/static/fonts/OpenSans/OpenSans-Bold-webfont.ttf
  cms/static/fonts/OpenSans/OpenSans-Bold-webfont.woff
  cms/static/fonts/OpenSans/OpenSans-Bold-webfont.woff2
  cms/static/fonts/OpenSans/OpenSans-BoldItalic-webfont.ttf
  cms/static/fonts/OpenSans/OpenSans-BoldItalic-webfont.woff
  cms/static/fonts/OpenSans/OpenSans-BoldItalic-webfont.woff2
  cms/static/fonts/OpenSans/OpenSans-Italic-webfont.ttf
  cms/static/fonts/OpenSans/OpenSans-Italic-webfont.woff
  cms/static/fonts/OpenSans/OpenSans-Italic-webfont.woff2
  cms/static/fonts/OpenSans/OpenSans-Light-webfont.ttf
  cms/static/fonts/OpenSans/OpenSans-Light-webfont.woff
  cms/static/fonts/OpenSans/OpenSans-Light-webfont.woff2
  cms/static/fonts/OpenSans/OpenSans-LightItalic-webfont.ttf
  cms/static/fonts/OpenSans/OpenSans-LightItalic-webfont.woff
  cms/static/fonts/OpenSans/OpenSans-LightItalic-webfont.woff2
  cms/static/fonts/OpenSans/OpenSans-Regular-webfont.ttf
  cms/static/fonts/OpenSans/OpenSans-Regular-webfont.woff
  cms/static/fonts/OpenSans/OpenSans-Regular-webfont.woff2
  cms/static/fonts/OpenSans/OpenSans-Semibold-webfont.ttf
  cms/static/fonts/OpenSans/OpenSans-Semibold-webfont.woff
  cms/static/fonts/OpenSans/OpenSans-Semibold-webfont.woff2
  cms/static/fonts/OpenSans/OpenSans-SemiboldItalic-webfont.ttf
  cms/static/fonts/OpenSans/OpenSans-SemiboldItalic-webfont.woff
  cms/static/fonts/OpenSans/OpenSans-SemiboldItalic-webfont.woff2
  cms/static/sass/assets/_fonts.scss
  common/static/css/tinymce-studio-content-fonts.css
Labels: awaiting prioritization, open-source-contribution

#24523 [BD-6] Use updated django-wiki version, OEP-18 compliant and compatible with Python 3.8.
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: blended, needs triage

#24536 [BD-10] Remove _uses_pattern_library property from EdxFragmentViews
  cms/templates/fragments/standalone-page-v1.html
  cms/templates/fragments/standalone-page-v2.html
  lms/djangoapps/discussion/views.py
  lms/djangoapps/learner_dashboard/programs.py
  lms/templates/fragments/standalone-page-v1.html
  lms/templates/fragments/standalone-page-v2.html
  openedx/core/djangoapps/plugin_api/views.py
  openedx/features/course_bookmarks/views/course_bookmarks.py
  openedx/features/course_experience/views/course_dates.py
  openedx/features/course_experience/views/course_home.py
  openedx/features/course_experience/views/course_outline.py
  openedx/features/course_experience/views/course_updates.py
  openedx/features/course_experience/views/latest_update.py
  openedx/features/course_experience/views/welcome_message.py
  openedx/features/course_search/views/course_search.py
  openedx/features/learner_profile/views/learner_achievements.py
Labels: blended, needs triage

#24165 removed edx-pattern-library from JS bundles
  common/lib/xmodule/xmodule/js/karma_xmodule.conf.js
  common/static/common/js/karma.common.conf.js
Labels: awaiting prioritization, open-source-contribution

#24535 [BD-10] Remove uses bootstrap method
  common/lib/xmodule/xmodule/tabs.py
  lms/djangoapps/courseware/views/views.py
  lms/djangoapps/discussion/plugins.py
  lms/templates/courseware/tab-view-v2.html
  openedx/features/course_experience/views/course_home.py
  openedx/features/course_experience/views/course_reviews.py
  openedx/features/course_experience/views/course_updates.py
  openedx/features/course_search/views/course_search.py
Labels: blended

#24570 [BD-10] [DEPR-92] Remove pattern library of certificate styles.
  lms/static/certificates/fonts/OpenSans/OpenSans-Bold-webfont.ttf
  lms/static/certificates/fonts/OpenSans/OpenSans-Bold-webfont.woff
  lms/static/certificates/fonts/OpenSans/OpenSans-Bold-webfont.woff2
  lms/static/certificates/fonts/OpenSans/OpenSans-BoldItalic-webfont.ttf
  lms/static/certificates/fonts/OpenSans/OpenSans-BoldItalic-webfont.woff
  lms/static/certificates/fonts/OpenSans/OpenSans-BoldItalic-webfont.woff2
  lms/static/certificates/fonts/OpenSans/OpenSans-Italic-webfont.ttf
  lms/static/certificates/fonts/OpenSans/OpenSans-Italic-webfont.woff
  lms/static/certificates/fonts/OpenSans/OpenSans-Italic-webfont.woff2
  lms/static/certificates/fonts/OpenSans/OpenSans-Light-webfont.ttf
  lms/static/certificates/fonts/OpenSans/OpenSans-Light-webfont.woff
  lms/static/certificates/fonts/OpenSans/OpenSans-Light-webfont.woff2
  lms/static/certificates/fonts/OpenSans/OpenSans-LightItalic-webfont.ttf
  lms/static/certificates/fonts/OpenSans/OpenSans-LightItalic-webfont.woff
  lms/static/certificates/fonts/OpenSans/OpenSans-LightItalic-webfont.woff2
  lms/static/certificates/fonts/OpenSans/OpenSans-Regular-webfont.ttf
  lms/static/certificates/fonts/OpenSans/OpenSans-Regular-webfont.woff
  lms/static/certificates/fonts/OpenSans/OpenSans-Regular-webfont.woff2
  lms/static/certificates/fonts/OpenSans/OpenSans-Semibold-webfont.ttf
  lms/static/certificates/fonts/OpenSans/OpenSans-Semibold-webfont.woff
  lms/static/certificates/fonts/OpenSans/OpenSans-Semibold-webfont.woff2
  lms/static/certificates/fonts/OpenSans/OpenSans-SemiboldItalic-webfont.ttf
  lms/static/certificates/fonts/OpenSans/OpenSans-SemiboldItalic-webfont.woff
  lms/static/certificates/fonts/OpenSans/OpenSans-SemiboldItalic-webfont.woff2
  lms/static/certificates/sass/_base.scss
  lms/static/certificates/sass/_components.scss
  lms/static/certificates/sass/_config.scss
  lms/static/certificates/sass/_layouts.scss
  lms/static/certificates/sass/_print.scss
  lms/static/certificates/sass/_utilities.scss
  lms/static/certificates/sass/_views.scss
  lms/static/certificates/sass/main-ltr.scss
  lms/static/certificates/sass/main-rtl.scss
Labels: blended

#24591 [BD-10] [DEPR-92] Remove pattern library of pavelib folder
  pavelib/assets.py
  pavelib/paver_tests/test_assets.py
Labels: blended, needs triage

#24602 [BD-10] [DEPR-92] Remove directories that includes pattern library.
  cms/static/edx-pattern-library
  common/static/edx-pattern-library/font-awesome
  common/static/edx-pattern-library/fonts
  common/static/edx-pattern-library/js
  lms/static/edx-pattern-library
Labels: blended, needs triage

#24385 [BD-14]"Source from Library" XBlock
  cms/djangoapps/contentstore/views/item.py
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/assets/library_source_block/public/js/library_source_block.js
  common/lib/xmodule/xmodule/library_content_module.py
  common/lib/xmodule/xmodule/library_sourced_block.py
  common/lib/xmodule/xmodule/library_tools.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py
  common/lib/xmodule/xmodule/modulestore/xml_importer.py
  common/lib/xmodule/xmodule/templates/library-sourced-block-author-view.html
  common/lib/xmodule/xmodule/tests/test_library_content.py
  common/lib/xmodule/xmodule/tests/test_library_sourced_block.py
  common/lib/xmodule/xmodule/tests/test_library_tools.py
  lms/djangoapps/lms_xblock/runtime.py
  openedx/core/djangoapps/xblock/learning_context/manager.py
  openedx/tests/completion_integration/test_services.py
  openedx/tests/settings.py
Labels: blended, engineering review

#24592 Fix issue with `SameSite=None` cookies from being blocked when `django_cookies_samesite.middleware.CookiesSameSite` is enabled for `devstack_docker` environment.
  lms/envs/devstack.py
Labels: awaiting prioritization, open-source-contribution

#24593 Fix issue with `SameSite=None` cookies from being blocked when `django_cookies_samesite.middleware.CookiesSameSite` is enabled for `devstack_docker` environment.
  lms/envs/devstack.py
Labels: awaiting prioritization, open-source-contribution

#24417 [BD-29] [TNL-7263] Support Anonymous Courseware Access
  openedx/core/djangoapps/content/learning_sequences/api/outlines.py
  openedx/core/djangoapps/content/learning_sequences/api/processors/base.py
  openedx/core/djangoapps/content/learning_sequences/api/processors/enrollment.py
  openedx/core/djangoapps/content/learning_sequences/api/processors/schedule.py
  openedx/core/djangoapps/content/learning_sequences/api/processors/visibility.py
  openedx/core/djangoapps/content/learning_sequences/api/tests/test_data.py
  openedx/core/djangoapps/content/learning_sequences/api/tests/test_outlines.py
  openedx/core/djangoapps/content/learning_sequences/data.py
  openedx/core/djangoapps/content/learning_sequences/migrations/0003_create_course_context_for_course_specific_models.py
  openedx/core/djangoapps/content/learning_sequences/models.py
  openedx/core/djangoapps/content/learning_sequences/tasks.py
  openedx/core/djangoapps/content/learning_sequences/tests/test_views.py
  openedx/core/djangoapps/content/learning_sequences/views.py
Labels: blended, needs triage
