Repository openedx/edx-platform, pull requests merged in 2020-03, with the labels that each got.

#21984 Use authsource instead of auth_source for compatibilities with pymongo
  common/djangoapps/track/backends/mongodb.py
  common/lib/xmodule/xmodule/mongo_utils.py
Labels: awaiting prioritization, open-source-contribution

#20545 fix very long horizontal scroll for RTL layout
  lms/static/sass/course/instructor/_instructor_2.scss
Labels: engineering review, needs triage, open-source-contribution

#19283 [BB-527] expand subsections when the url anchor points to them.
  openedx/features/course_experience/static/course_experience/js/CourseOutline.js
Labels: engineering review, needs triage, open-source-contribution

#21567 SE-1463 Allow overriding broker heartbeat
  cms/envs/production.py
  lms/envs/production.py
Labels: awaiting prioritization, open-source-contribution

#23241 Fix Blockstore XBlock Runtime's handling of occasional S3 errors
  openedx/core/djangoapps/xblock/runtime/blockstore_field_data.py
  openedx/core/djangoapps/xblock/runtime/blockstore_runtime.py
  openedx/core/djangoapps/xblock/runtime/olx_parsing.py
  openedx/core/djangolib/blockstore_cache.py
  openedx/core/lib/blockstore_api/__init__.py
  openedx/core/lib/blockstore_api/exceptions.py
Labels: awaiting prioritization, open-source-contribution

#21365 Allow one letter extra fields
  openedx/core/djangoapps/user_authn/views/registration_form.py
Labels: engineering review, open-source-contribution

#23392 Fix Blockstore XBlock Runtime's handling of occasional S3 errors (take 2)
  openedx/core/djangoapps/xblock/runtime/blockstore_field_data.py
  openedx/core/djangoapps/xblock/runtime/blockstore_runtime.py
  openedx/core/djangoapps/xblock/runtime/olx_parsing.py
  openedx/core/djangolib/blockstore_cache.py
  openedx/core/lib/blockstore_api/__init__.py
  openedx/core/lib/blockstore_api/exceptions.py
Labels: engineering review, open-source-contribution

#23015 Add xblock.v1 and xmodule.v1 entrypoints for NonStaffErrorDescriptor
  common/lib/xmodule/setup.py
Labels: awaiting prioritization, open-source-contribution

#23512 Import private.py in devstack_docker.py files instead of devstack.py
  cms/envs/devstack.py
  cms/envs/devstack_docker.py
  lms/envs/devstack.py
  lms/envs/devstack_docker.py
Labels: awaiting prioritization, open-source-contribution
