Repository openedx/edx-platform, pull requests merged in 2020-06, with the labels that each got.

#24078 [BD-6] Remove pandas dependency
  openedx/core/process_warnings.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/coverage.in
  requirements/edx/coverage.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24116 [BD-6] Update sorl-thumbnail dependency
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#20225 BB-1156: Enable changing the build profile used by RequireJS
  lms/envs/production.py
Labels: needs triage, open-source-contribution

#24105 [BD-6] Remove pystache_custom dependency.
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24062 [BD-10] [DEPR-76] Remove pattern library of course-updates-fragment.html
  lms/static/sass/features/_course-experience.scss
  openedx/features/course_experience/views/course_updates.py
Labels: engineering review, open-source-contribution

#23265 [BB-112] Fix the unpredictable order randomization issue with randomized content blocks
  common/lib/xmodule/xmodule/library_content_module.py
  common/lib/xmodule/xmodule/tests/test_library_content.py
  lms/djangoapps/course_blocks/api.py
  lms/djangoapps/course_blocks/transformers/library_content.py
  lms/djangoapps/course_blocks/transformers/tests/test_library_content.py
  setup.py
Labels: engineering review, open-source-contribution

#24183 [BD-6] Use transifex-client fork
  requirements/constraints.txt
  requirements/edx/development.txt
  requirements/edx/testing.in
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24198 [BD-5] [BB-2503] Add 'ENABLE_ORA_USERNAMES_ON_DATA_EXPORT' feature toggle
  lms/envs/common.py
Labels: needs triage, open-source-contribution

#24217 [BD-6] Update transifex client to use PyPi release.
  requirements/edx/development.txt
  requirements/edx/testing.in
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24028 [BD-10] [DEPR-83] Remove course_experience.use_bootstrap waffle flag
  openedx/features/course_experience/__init__.py
  openedx/features/course_experience/views/course_home.py
  openedx/features/course_experience/views/course_reviews.py
  openedx/features/course_experience/views/course_updates.py
Labels: open-source-contribution

#24240 [BD-6] Fix python 3.8 compatibility
  common/lib/xmodule/xmodule/modulestore/__init__.py
Labels: needs triage, open-source-contribution

#24029 [BD-10] [DEPR-70] Remove pattern library of discussion/views.py
  common/static/common/templates/discussion/templates.underscore
  lms/djangoapps/discussion/views.py
  lms/static/sass/bootstrap/_components.scss
  lms/static/sass/bootstrap/_legacy.scss
Labels: open-source-contribution

#24044 [BD-10] [DEPR-75] Remove pattern library of course-outline-fragment.html
  lms/static/sass/features/_course-experience.scss
  openedx/features/course_experience/views/course_outline.py
Labels: open-source-contribution

#24077 [BD-10] [DEPR-78][DEPR-82] Remove pattern library of latest-update-fragment.html and welcome-message-fragment.html
  lms/static/sass/features/_course-experience.scss
  openedx/features/course_experience/views/latest_update.py
  openedx/features/course_experience/views/welcome_message.py
Labels: engineering review, open-source-contribution

#24101 [BD-10] [DEPR-70] Remove waffle flag edx_discussions.use_bootstrap.
  lms/djangoapps/discussion/config/waffle.py
  lms/djangoapps/discussion/plugins.py
  lms/djangoapps/discussion/views.py
  lms/envs/common.py
  lms/static/sass/discussion/lms-discussion-main-rtl.scss
  lms/static/sass/discussion/lms-discussion-main.scss
Labels: open-source-contribution

#24111 [BD-10] [DEPR-79] Remove pattern library of mobile/course-dates-fragment.html
  openedx/features/course_experience/views/course_dates.py
Labels: open-source-contribution

#24124 [BD-10] [DEPR-68][DEPR-84] Remove pattern library of learner_dashboard/programs.py
  lms/djangoapps/learner_dashboard/programs.py
  lms/static/sass/elements/_program-card.scss
Labels: open-source-contribution

#24158 [BD-10] Remove unused course sock URL.
  openedx/features/course_experience/urls.py
Labels: needs triage, open-source-contribution

#24100 Fixing implicit parser name for Beautiful Soup (lms, openedx)
  lms/djangoapps/verify_student/tests/test_views.py
  openedx/tests/xblock_integration/xblock_testcase.py
Labels: awaiting prioritization, open-source-contribution, waiting on author

#24256 Result of running make upgrade in order to upgrade to edx-enterprise 3.3.5
  requirements/edx/base.txt
  requirements/edx/coverage.txt
  requirements/edx/development.txt
  requirements/edx/django.txt
  requirements/edx/paver.txt
  requirements/edx/testing.txt
  scripts/xblock/requirements.txt
Labels: dependencies

#24126 [BD-6] Use Pypi release of social-app-django
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#23936 Fix DeprecationWarning for unescape
  lms/djangoapps/courseware/tests/test_views.py
  openedx/core/djangoapps/credit/email_utils.py
  openedx/core/djangolib/tests/test_js_utils.py
  openedx/tests/xblock_integration/xblock_testcase.py
Labels: awaiting prioritization, engineering review, open-source-contribution

#24058 Optimize blockstore cache
  openedx/core/djangolib/blockstore_cache.py
Labels: engineering review, open-source-contribution

#23039 SE-2176 Fix elem not selected if id contains special chars
  common/lib/xmodule/xmodule/js/src/capa/schematic.js
  common/lib/xmodule/xmodule/js/src/sequence/display.js
  common/lib/xmodule/xmodule/js/src/video/06_video_progress_slider.js
  common/static/js/capa/spec/formula_equation_preview_spec.js
  common/static/js/capa/src/formula_equation_preview.js
  lms/djangoapps/teams/static/teams/js/views/edit_team_members.js
  openedx/core/djangoapps/xblock/runtime/shims.py
  scripts/xsslint/tests/test_linters.py
  scripts/xsslint/xsslint/linters.py
  scripts/xsslint_thresholds.json
Labels: engineering review, open-source-contribution

#24257 [BD-6] Remove constraint from mako
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24220 SE-2634 Fix crashes in yt_video_metadata
  common/lib/xmodule/xmodule/video_module/video_handlers.py
  lms/djangoapps/courseware/views/views.py
Labels: open-source-contribution, waiting on author

#24274 [BD-6] Update dicts order to fix tests
  cms/djangoapps/contentstore/tests/test_course_settings.py
  common/djangoapps/pipeline_mako/tests/test_render.py
Labels: needs triage, open-source-contribution

#23939 Fixing cgi.escape DeprecationWarning
  common/lib/xmodule/xmodule/poll_module.py
Labels: open-source-contribution, waiting on author

#24268 [BD-6] Fix test for python3.8
  common/lib/capa/capa/safe_exec/tests/test_safe_exec.py
Labels: needs triage, open-source-contribution

#24265 [BD-6] async is a keyword in python>=3.7
  common/djangoapps/pipeline_mako/templates/mako/inline_js.html
  common/djangoapps/pipeline_mako/templates/mako/js.html
Labels: needs triage, open-source-contribution

#24311 [BD-6] Order VideoBlock html metadata alphabeticallly to fix test.
  common/lib/xmodule/xmodule/video_module/video_module.py
Labels: needs triage, open-source-contribution

#24312 [BD-6] Upgrade mongoengine
  lms/djangoapps/dashboard/git_import.py
  lms/djangoapps/dashboard/tests/test_sysadmin.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24297 [BD-6] Attempt to fix db sync problem for python3.8
  common/djangoapps/course_modes/migrations/0011_change_regex_for_comma_separated_ints.py
  common/djangoapps/course_modes/migrations/0012_historicalcoursemode.py
Labels: needs triage, open-source-contribution

#24310 [BD-6] Separate tests according to the python version, due to incompatibilities in sorted dicts.
  lms/djangoapps/discussion/django_comment_client/tests/test_utils.py
Labels: needs triage, open-source-contribution

#24337 [BD-6] Remove usage of enum34, since we are already in python>=3.4
  pavelib/prereqs.py
  requirements/edx-sandbox/base.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#24282 Replace track calls with eventtracking in task_track and server_track
  common/djangoapps/track/tracker.py
  common/djangoapps/track/views/__init__.py
  common/djangoapps/track/views/tests/test_views.py
  lms/djangoapps/certificates/tests/test_webview_views.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/envs/devstack_with_worker.py
  openedx/core/lib/tests/assertions/events.py
Labels: open-source-contribution, waiting on author

#23751 Fix 'npm install' command execution error handling
  pavelib/paver_tests/test_prereqs.py
  pavelib/paver_tests/utils.py
  pavelib/prereqs.py
Labels: awaiting prioritization, open-source-contribution

#24330 [BD-6] Fix invalid escape sequence deprecation warning.
  openedx/core/process_warnings.py
Labels: needs triage, open-source-contribution
