Repository openedx/edx-platform, pull requests merged in 2020-10, with the labels that each got.

#24794 [BD-21] Document settings with annotations
  Makefile
  cms/envs/common.py
  docs/technical/.gitignore
  docs/technical/Makefile
  docs/technical/conf.py
  docs/technical/featuretoggles.rst
  docs/technical/index.rst
  docs/technical/settings.rst
  lms/envs/common.py
  openedx/core/djangoapps/content_libraries/tests/base.py
Labels: blended, needs triage

#25215 upgrade to enterprise 3.8.25: blackboard client
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: blackboard

#25007 [BD-14] [SE-2932] Add a license field to libraries.
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/constants.py
  openedx/core/djangoapps/content_libraries/migrations/0004_contentlibrary_license.py
  openedx/core/djangoapps/content_libraries/models.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: blended, waiting on author

#25237 add missing app blackboard
  cms/envs/common.py
  lms/envs/common.py
Labels: blackboard

#24264 [BD-29] [TNL-7209] [BB-2595] Enable Anonymous access for course blocks API
  lms/djangoapps/course_api/blocks/forms.py
  lms/djangoapps/course_api/blocks/permissions.py
  lms/djangoapps/course_api/blocks/tests/test_views.py
  lms/djangoapps/course_api/blocks/views.py
Labels: blended, waiting on author

#25253 edxapp MySQL database dump
  edxapp.sql
Labels: MySQLdbdump

#23174 [BB-2088] Add %%COURSE_ID%% to html block
  common/lib/xmodule/xmodule/html_module.py
  common/lib/xmodule/xmodule/tests/test_html_module.py
Labels: cc-reviewer, open edx community review, open-source-contribution

#21594 [BB-1504] Fix the automatic enrollment issue for inactive user
  lms/djangoapps/instructor/enrollment.py
  lms/djangoapps/instructor/tests/test_enrollment.py
Labels: cc-reviewer, open edx community review, open-source-contribution

#25259 [SE-3111] Enforce CORS allow on xBlock handlers
  openedx/core/djangoapps/xblock/rest_api/views.py
Labels: cc-reviewer, open edx community review, open-source-contribution

#24816 [BD-14] Add UI for browsing and searching blocks in "Source from library" block
  common/lib/xmodule/xmodule/assets/library_source_block/LibrarySourcedBlockPicker.jsx
  common/lib/xmodule/xmodule/assets/library_source_block/public/js/library_source_block.js
  common/lib/xmodule/xmodule/assets/library_source_block/style.css
  common/lib/xmodule/xmodule/library_sourced_block.py
  common/lib/xmodule/xmodule/library_tools.py
  common/lib/xmodule/xmodule/templates/library-sourced-block-author-view.html
  common/lib/xmodule/xmodule/templates/library-sourced-block-studio-view.html
  common/lib/xmodule/xmodule/tests/test_library_sourced_block.py
  common/lib/xmodule/xmodule/tests/test_library_tools.py
  webpack.common.config.js
  webpack.dev.config.js
Labels: blended, ready to merge

#25361 upgrade enterprise to 3.8.39
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: blackboard

#25380 upgrade to enterprise 3.8.43
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: blackboard

#25411 [BD-21] Add edx-toggles requirement
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/django.txt
  requirements/edx/testing.txt
Labels: blended, needs triage

#25368 [BD-14] [SE-2939] Add ability to filter library blocks by type. Prevent changing types with unpublished changes.
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/libraries_index.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: blended, open edx community review

#24048 ADR for Sysadmin Dashboard deprecation and removal
  lms/djangoapps/dashboard/decisions/0002-deprecate-sysadmin-dashboard-adr.rst
Labels: core committer, open-source-contribution, waiting on author

#25440 Deprecate COURSE_OUTLINE_PAGE_FLAG and UNIFIED_COURSE_TAB_FLAG
  common/test/db_fixtures/waffle_flags.json
  lms/djangoapps/courseware/tabs.py
  lms/djangoapps/courseware/tests/test_course_info.py
  lms/djangoapps/courseware/tests/test_date_summary.py
  lms/djangoapps/courseware/tests/test_entrance_exam.py
  lms/djangoapps/courseware/tests/test_masquerade.py
  lms/djangoapps/courseware/tests/test_navigation.py
  lms/djangoapps/courseware/tests/test_tabs.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/views/index.py
  lms/djangoapps/courseware/views/views.py
  lms/envs/common.py
  lms/templates/courseware/courseware.html
  openedx/features/course_experience/__init__.py
  openedx/features/course_experience/plugins.py
  openedx/features/course_experience/templates/course_experience/course-home-fragment.html
  openedx/features/course_experience/tests/views/test_course_home.py
Labels: needs triage, open-source-contribution

#25386 remove the constraint on edx-sga
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, waiting on author

#25286 [BD-21] Move waffle_utils from edx-platform to edx-toggles
  Makefile
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/core/djangoapps/waffle_utils/tests/test_init.py
  openedx/core/djangoapps/waffle_utils/tests/test_testutils.py
  openedx/core/djangoapps/waffle_utils/tests/test_views.py
  openedx/core/djangoapps/waffle_utils/testutils.py
  openedx/core/djangoapps/waffle_utils/views.py
  openedx/features/course_experience/__init__.py
  requirements/constraints.txt
Labels: blended, needs triage

#25332 [BD-21] Use edx-toggle's SettingDictToggle to document setting-based feature toggles
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/views/entrance_exam.py
  cms/djangoapps/contentstore/views/helpers.py
  cms/djangoapps/contentstore/views/item.py
  cms/envs/common.py
  cms/urls.py
  common/djangoapps/student/models.py
  common/djangoapps/util/milestones_helpers.py
  lms/djangoapps/courseware/entrance_exams.py
  lms/djangoapps/gating/api.py
  lms/djangoapps/teams/toggles.py
  lms/djangoapps/teams/views.py
  lms/djangoapps/teams/waffle.py
  lms/envs/common.py
  openedx/core/toggles.py
  sys_path_hacks/lms/teams/waffle.py
Labels: blended, needs triage

#25457 Squash lms_initialization deprecated import warning
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution
