Repository openedx/edx-platform, pull requests merged in 2020-02, with the labels that each got.

#22937 Reveal a message to be extracted
  lms/templates/registration/password_reset_confirm.html
Labels: awaiting prioritization, open-source-contribution

#23107 BOM-1278
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: work in progress

#22637 update bookmarks update_xblocks_cache celery task name
  openedx/core/djangoapps/bookmarks/tasks.py
Labels: awaiting prioritization, open-source-contribution

#21158 Setting template to show currency defined in the course mode DB record
  common/djangoapps/course_modes/views.py
  lms/templates/course_modes/_upgrade_button.html
  lms/templates/course_modes/choose.html
Labels: open-source-contribution, product review

#22973 Display profile name in gradebook api
  lms/djangoapps/grades/rest_api/v1/gradebook_views.py
Labels: awaiting prioritization, open-source-contribution

#21616 SE-1496 conditionally re-enable user change password form in admin
  cms/envs/common.py
  cms/urls.py
  common/djangoapps/student/admin.py
  lms/envs/common.py
  lms/urls.py
Labels: engineering review, open-source-contribution

#22385 Do not hide all the elements of the units with graded problems to anonymous users
  common/lib/xmodule/xmodule/seq_module.py
Labels: engineering review, open-source-contribution

#19906 Allow a configurable number of weekly course highlight emails
  openedx/core/djangoapps/schedules/management/commands/__init__.py
  openedx/core/djangoapps/schedules/management/commands/send_course_update.py
  openedx/core/djangoapps/schedules/management/commands/tests/test_send_email_base_command.py
Labels: awaiting prioritization, needs triage, open-source-contribution

#23068 REST API to export modulestore XBlocks as OLX
  openedx/core/djangoapps/olx_rest_api/__init__.py
  openedx/core/djangoapps/olx_rest_api/adapters.py
  openedx/core/djangoapps/olx_rest_api/apps.py
  openedx/core/djangoapps/olx_rest_api/block_serializer.py
  openedx/core/djangoapps/olx_rest_api/test_adapters.py
  openedx/core/djangoapps/olx_rest_api/test_views.py
  openedx/core/djangoapps/olx_rest_api/urls.py
  openedx/core/djangoapps/olx_rest_api/views.py
  setup.py
Labels: awaiting prioritization, open-source-contribution

#20806 Add link to course url in the account creation and enrollment email
  lms/templates/instructor/edx_ace/accountcreationandenrollment/email/body.html
  lms/templates/instructor/edx_ace/accountcreationandenrollment/email/body.txt
Labels: awaiting prioritization, open-source-contribution

#22164 SE-1773 Logs failed heartbeat checks
  openedx/core/djangoapps/heartbeat/views.py
Labels: awaiting prioritization, open-source-contribution

#20378 BB-986: Add variable that allows overriding marketing urls
  cms/envs/common.py
  cms/envs/production.py
  common/djangoapps/edxmako/shortcuts.py
  common/djangoapps/edxmako/tests.py
  lms/envs/common.py
  lms/envs/production.py
Labels: engineering review, needs triage, open-source-contribution
