Repository openedx/edx-platform, pull requests merged in 2020-01, with the labels that each got.

#22676 Undefined name: import datetime for line 30
  lms/djangoapps/coursewarehistoryextended/migrations/0001_initial.py
Labels: awaiting prioritization, open-source-contribution

#22675 Use ==/!= to compare str, bytes, and int literals
  openedx/features/enterprise_support/api.py
Labels: needs triage, open-source-contribution

#22693 from xmodule.modulestore.exceptions import MultipleLibraryBlocksFound
  common/lib/xmodule/xmodule/modulestore/split_mongo/split.py
Labels: awaiting prioritization, open-source-contribution

#21522 WIP: Removing deprecated management commands which intended to …
  common/djangoapps/student/management/commands/delete_historical_enrollment_data.py
  lms/djangoapps/verify_student/management/commands/delete_historical_verify_student_data.py
  openedx/core/djangoapps/api_admin/management/commands/delete_historical_api_admin_data.py
  openedx/core/djangoapps/credit/management/__init__.py
  openedx/core/djangoapps/credit/management/commands/__init__.py
  openedx/core/djangoapps/credit/management/commands/delete_historical_credit_data.py
  openedx/core/djangoapps/util/row_delete.py
Labels: engineering review, open-source-contribution

#20804 [BB-1336] Add a management command to create or update site configuration
  openedx/core/djangoapps/site_configuration/management/commands/create_or_update_site_configuration.py
  openedx/core/djangoapps/site_configuration/management/commands/create_site_configuration.py
  openedx/core/djangoapps/site_configuration/management/commands/tests/fixtures/config1.json
  openedx/core/djangoapps/site_configuration/management/commands/tests/test_create_or_update_site_configuration.py
  openedx/core/djangoapps/site_configuration/management/commands/tests/test_create_site_configuration.py
Labels: engineering review, open-source-contribution

#22804 Delete extra parentheses which prevented a message from being extracted
  lms/templates/registration/password_reset_confirm.html
Labels: needs triage, open-source-contribution

#22858 Fix: KeyError: 'source' when parsing HTML5 videos
  common/lib/xmodule/xmodule/video_module/video_module.py
Labels: awaiting prioritization, open-source-contribution

#22837 Add way to get YouTube metadata that doesn't require a session cookie
  common/lib/xmodule/xmodule/js/src/video/01_initialize.js
  common/lib/xmodule/xmodule/video_module/video_handlers.py
  common/lib/xmodule/xmodule/video_module/video_module.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/courseware/views/views.py
Labels: open-source-contribution, waiting on author

#22777 Updated the django-ratelimit to add support for Django 2.2
  lms/djangoapps/oauth2_handler/tests.py
  lms/envs/test.py
  openedx/core/djangoapps/oauth_dispatch/views.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.in
  requirements/edx/testing.txt
Labels: work in progress
