Repository openedx/edx-platform, pull requests merged in 2020-12, with the labels that each got.

#25714 [WIP] [BTR-39] Cherry-pick warning squash commits
  cms/envs/common.py
  common/lib/xmodule/xmodule/modulestore/tests/django_utils.py
  common/lib/xmodule/xmodule/video_module/transcripts_utils.py
  lms/djangoapps/ccx/tests/test_field_override_performance.py
  lms/djangoapps/courseware/tests/test_model_data.py
  lms/djangoapps/courseware/tests/test_submitting_problems.py
  lms/djangoapps/courseware/tests/test_user_state_client.py
  lms/djangoapps/coursewarehistoryextended/tests.py
  lms/djangoapps/verify_student/management/commands/tests/test_populate_expiration_date.py
  lms/envs/common.py
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/features/course_duration_limits/tests/test_models.py
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/tests/views/test_course_outline.py
  openedx/features/course_experience/tests/views/test_course_updates.py
Labels: open-source-contribution, waiting on author

#25295 Correct DemoX Code Grader solution
  common/test/data/manual-testing-complete/problem/c2ee6e8917fe4c97ac99d7b616ff0b89.xml
Labels: cc-reviewer, open edx community review, open-source-contribution

#25728 [BTR-46] [SE-3439] Fixes block structure not caching when cache invalidation is enabled
  openedx/core/djangoapps/content/block_structure/signals.py
Labels: needs triage, open-source-contribution

#25543 [SE-3439] Fixes block structure not caching when cache invalidation is enabled
  openedx/core/djangoapps/content/block_structure/signals.py
Labels: awaiting prioritization, open-source-contribution

#25618 [BD-4] Convert Annotatable XModule to XBlock. [SE-3640]
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/annotatable_module.py
  common/lib/xmodule/xmodule/static_content.py
  common/lib/xmodule/xmodule/tests/test_annotatable_module.py
  common/lib/xmodule/xmodule/tests/test_xblock_wrappers.py
  lms/templates/annotatable.html
Labels: blended, engineering review

#25530 [BD-21] Start waffle namespace deprecation process
  cms/djangoapps/contentstore/config/waffle.py
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/views/item.py
  cms/djangoapps/contentstore/views/tests/test_videos.py
  cms/djangoapps/contentstore/views/videos.py
  common/djangoapps/student/__init__.py
  common/djangoapps/student/admin.py
  common/djangoapps/student/views/dashboard.py
  common/lib/xmodule/xmodule/seq_module.py
  lms/djangoapps/certificates/tests/test_signals.py
  lms/djangoapps/certificates/tests/test_webview_views.py
  lms/djangoapps/course_api/__init__.py
  lms/djangoapps/course_api/blocks/toggles.py
  lms/djangoapps/course_home_api/toggles.py
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/courseware/toggles.py
  lms/djangoapps/courseware/views/index.py
  lms/djangoapps/email_marketing/signals.py
  lms/djangoapps/email_marketing/tests/test_signals.py
  lms/djangoapps/experiments/flags.py
  lms/djangoapps/experiments/tests/test_flags.py
  lms/djangoapps/experiments/utils.py
  lms/djangoapps/experiments/views_custom.py
  lms/djangoapps/gating/tests/test_integration.py
  lms/djangoapps/grades/config/waffle.py
  lms/djangoapps/instructor/toggles.py
  lms/djangoapps/instructor_task/config/waffle.py
  lms/djangoapps/teams/toggles.py
  lms/djangoapps/verify_student/toggles.py
  openedx/core/djangoapps/certificates/config/waffle.py
  openedx/core/djangoapps/certificates/tests/test_api.py
  openedx/core/djangoapps/content/block_structure/config/__init__.py
  openedx/core/djangoapps/models/config/waffle.py
  openedx/core/djangoapps/programs/__init__.py
  openedx/core/djangoapps/schedules/config.py
  openedx/core/djangoapps/user_api/accounts/toggles.py
  openedx/core/djangoapps/user_api/accounts/utils.py
  openedx/core/djangoapps/user_api/config/waffle.py
  openedx/core/djangoapps/user_authn/config/waffle.py
  openedx/core/djangoapps/user_authn/views/register.py
  openedx/core/djangoapps/util/waffle.py
  openedx/core/djangoapps/video_pipeline/config/waffle.py
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/core/djangoapps/waffle_utils/views.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
  openedx/core/lib/request_utils.py
  openedx/features/course_experience/__init__.py
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/tests/views/test_course_outline.py
  openedx/features/course_experience/views/course_outline.py
  openedx/features/course_experience/waffle.py
  openedx/features/discounts/applicability.py
  openedx/features/enterprise_support/utils.py
  openedx/features/learner_profile/toggles.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: blended, needs triage

#25751 [BTR-38] [BB-3269] Add openassessment url to CMS
  cms/urls.py
Labels: open-source-contribution, waiting on author

#25760 Register pytest mongo marker to avoid warning.
  common/lib/pytest.ini
Labels: needs triage, open-source-contribution

#25809 In the LMS, bookmarks associated to deleted units are not deleted
  cms/djangoapps/contentstore/views/item.py
  openedx/core/djangoapps/bookmarks/api.py
  openedx/core/djangoapps/bookmarks/tests/test_api.py
  openedx/core/djangoapps/bookmarks/tests/test_models.py
  openedx/core/djangoapps/bookmarks/tests/test_services.py
  openedx/core/djangoapps/bookmarks/tests/test_tasks.py
  openedx/core/djangoapps/bookmarks/tests/test_views.py
Labels: needs triage, open-source-contribution

#25012 [BB-2961] [BD-05] [TNL-7577] Added open response button to the component tray
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/views/tests/test_item.py
  cms/djangoapps/contentstore/views/tests/test_library.py
  cms/envs/common.py
  cms/static/images/large-openassessment-icon.png
  cms/static/sass/assets/_graphics.scss
  cms/static/sass/elements/_modules.scss
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: blended, needs triage

#25830 [TNL-7771][LX-1409][SE-3764] sets blockstore values timeouts to avoid S3 links Expiration
  cms/envs/common.py
  lms/envs/common.py
  openedx/core/djangolib/blockstore_cache.py
Labels: needs triage, open-source-contribution

#24990 SE-3149 Fix inconsistent cached file hash issue since juniper
  common/lib/xmodule/xmodule/static_content.py
  openedx/core/djangoapps/theming/storage.py
  openedx/core/storage.py
Labels: cc-reviewer, open edx community review, open-source-contribution

#23109 SE-2010 Allows XBlocks to order columns for the Problem Response Report
  lms/djangoapps/instructor_task/tasks_helper/grades.py
  lms/djangoapps/instructor_task/tests/test_tasks_helper.py
Labels: cc-reviewer, open edx community review, open-source-contribution

#25881 [TNL-7771][SE-3764]: adds a new bundle_draft_files cache key
  openedx/core/djangolib/blockstore_cache.py
Labels: needs triage, open-source-contribution

#25694 SE-3492: Video Xblock API handler: student_view_state
  common/lib/xmodule/xmodule/video_module/video_handlers.py
Labels: engineering review, open-source-contribution

#25182 Add default value for learner records feature toggle in settings
  openedx/core/djangoapps/credentials/helpers.py
  openedx/core/djangoapps/credentials/models.py
  openedx/core/djangoapps/credentials/signals.py
  openedx/core/djangoapps/credentials/tests/test_signals.py
  openedx/core/djangoapps/programs/signals.py
Labels: changes requested, open-source-contribution

#25885 [BD-21] Fix deprecated waffle usage
  cms/djangoapps/contentstore/migrations/0005_add_enable_checklists_quality_waffle_flag.py
  cms/djangoapps/contentstore/views/tests/test_videos.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/grades/migrations/0018_add_waffle_flag_defaults.py
  lms/djangoapps/instructor/toggles.py
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/features/course_experience/tests/views/test_course_home.py
Labels: blended, needs triage

#25338 Sets default X-Frame-Options for login and registration forms to environment setting
  common/djangoapps/third_party_auth/decorators.py
Labels: open edx community review, open-source-contribution
