Repository openedx/edx-platform, pull requests merged in 2021-03, with the labels that each got.

#26808 Fix running tests in common/lib.
  common/lib/capa/capa/safe_exec/tests/test_safe_exec.py
  common/lib/capa/capa/tests/test_responsetypes.py
  common/lib/pytest.ini
  common/lib/xmodule/xmodule/modulestore/tests/test_assetstore.py
  common/lib/xmodule/xmodule/modulestore/tests/test_mixed_modulestore.py
  common/lib/xmodule/xmodule/tests/test_capa_module.py
  common/lib/xmodule/xmodule/tests/test_course_module.py
  common/lib/xmodule/xmodule/tests/test_graders.py
  pavelib/utils/envs.py
Labels: awaiting prioritization, open-source-contribution

#26809 [TSD] add annotaions for ENABLE_COOKIE_CONSENT feature flag
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#25941 Fix URL in forum notification post.
  lms/djangoapps/discussion/tasks.py
  lms/djangoapps/discussion/tests/test_tasks.py
Labels: open-source-contribution, ready to merge

#26106 Add option to disable the help link in the navbar
  cms/templates/widgets/header.html
  lms/envs/common.py
  lms/templates/header/navbar-authenticated.html
  lms/templates/navigation/bootstrap/navbar-authenticated.html
  lms/templates/navigation/navbar-authenticated.html
  themes/edx.org/lms/templates/header/navbar-authenticated.html
Labels: changes requested, open-source-contribution

#26897 TNL-7771: reverts back the bundle_draft_files cache key
  openedx/core/djangolib/blockstore_cache.py
Labels: needs triage, open-source-contribution

#26477 feat: Changed username max_length to the specified by django
  common/djangoapps/third_party_auth/models.py
  openedx/core/djangoapps/user_api/accounts/__init__.py
Labels: cc-reviewer, open-source-contribution, ready to merge

#26870 [TSD] add annotations for ENABLE_DISCUSSION_HOME_PANEL feature flag
  lms/envs/common.py
Labels: open-source-contribution, waiting on author

#25333 add toggle and setting annotations for CCX
  lms/envs/common.py
Labels: changes requested, core committer, open-source-contribution, ready to merge

#26667 [TSD] Annotate relative_dates waffle flag
  openedx/features/course_experience/__init__.py
Labels: changes requested, open-source-contribution

#26942 [TSD] Added annotation for ALLOW_HIDING_DISCUSSION_TAB feature flag
  lms/djangoapps/discussion/settings/common.py
Labels: awaiting prioritization, open-source-contribution

#26700 [TSD] add annotations for AUTOMATIC_AUTH_FOR_TESTING feature flag
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26973 [BD-04] Create CustomTagTemplateBlock, convert TranslateCustomTagDescriptor to XBlock and remove RawDescriptor
  cms/djangoapps/contentstore/tests/test_courseware_index.py
  cms/envs/test.py
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/backcompat_module.py
  common/lib/xmodule/xmodule/modulestore/tests/django_utils.py
  common/lib/xmodule/xmodule/modulestore/tests/test_mixed_modulestore.py
  common/lib/xmodule/xmodule/modulestore/tests/test_mongo.py
  common/lib/xmodule/xmodule/modulestore/tests/test_split_modulestore.py
  common/lib/xmodule/xmodule/modulestore/tests/test_split_w_old_mongo.py
  common/lib/xmodule/xmodule/modulestore/tests/utils.py
  common/lib/xmodule/xmodule/modulestore/xml_importer.py
  common/lib/xmodule/xmodule/raw_module.py
  common/lib/xmodule/xmodule/template_module.py
  lms/djangoapps/courseware/tests/test_module_render.py
  openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion/__init__.py
Labels: blended, engineering review

#26941 [TSD] Added annotations for DISABLE_COURSE_CREATION feature flag
  cms/envs/common.py
Labels: open-source-contribution, ready to merge

#26435 Fix missing email context values and pass site configuration to better multi-site customization
  cms/envs/common.py
  common/djangoapps/student/email_helpers.py
  lms/djangoapps/instructor/enrollment.py
  openedx/core/djangoapps/ace_common/template_context.py
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
  openedx/core/djangoapps/site_configuration/helpers.py
  openedx/core/djangoapps/site_configuration/tests/test_helpers.py
Labels: changes requested, open-source-contribution

#27040 [TSD] add annotations for ENABLE_LTI_PROVIDER feature flag
  lms/envs/common.py
Labels: changes requested, open-source-contribution

#26770 [TSD] add annotation to COURSE_HOME_MICROFRONTEND
  lms/djangoapps/course_home_api/toggles.py
Labels: open-source-contribution, ready to merge

#27059 docs: updates ticket links for block structure settings and toggles
  lms/envs/common.py
  openedx/core/djangoapps/content/block_structure/config/__init__.py
  openedx/core/djangoapps/content/block_structure/models.py
Labels: engineering review, open-source-contribution

#23457 [BB-2063] Calculate completion for custom blocks on the Course Outline page
  lms/djangoapps/course_api/blocks/serializers.py
  lms/djangoapps/course_api/blocks/transformers/block_completion.py
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/utils.py
Labels: changes requested, open-source-contribution

#26885 [BB-3710] Stop rendering Visibility button on libraries
  cms/djangoapps/contentstore/views/preview.py
Labels: cc-reviewer, engineering review, open-source-contribution

#27064 [ISSUE#7]Logo Swap & Config for serving assets from cdn.
  cms/envs/common.py
  cms/envs/production.py
  lms/djangoapps/branding/api.py
  lms/djangoapps/branding/toggles.py
  lms/envs/common.py
  lms/envs/production.py
  lms/static/sass/shared/_footer-edx.scss
  lms/static/sass/shared/_footer.scss
  lms/templates/main.html
  openedx/core/djangoapps/ace_common/template_context.py
  openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
  openedx/core/djangoapps/site_configuration/templatetags/configuration.py
Labels: awaiting prioritization, open-source-contribution

#27112 fixes contentstore next section navigation
  cms/djangoapps/contentstore/utils.py
Labels: needs triage, open-source-contribution

#26750 feat(jsinput): Allow JSInput problems to create downloads
  common/lib/capa/capa/inputtypes.py
  common/lib/capa/capa/templates/jsinput.html
  common/static/js/capa/fixtures/jsinput.html
Labels: awaiting prioritization, open-source-contribution

#27118 [BD-21] fix: TypeError in toggle state report view
  openedx/core/djangoapps/waffle_utils/tests/test_views.py
  openedx/core/djangoapps/waffle_utils/views.py
Labels: blended, needs triage

#27136 docs: annotate REGISTRATION_EXTRA_FIELDS setting
  lms/envs/common.py
Labels: needs triage, open-source-contribution

#25844 [BD-24] [BB-2726] [TNL-7330] Added batch_get_or_create class method for ExternalId
  openedx/core/djangoapps/external_user_ids/models.py
  openedx/core/djangoapps/external_user_ids/tests/test_batch_generate_id.py
Labels: blended, needs triage

#27186 fix: Backport py2neo fix workaround
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#25642 Find submission history using learner's email address
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/views/views.py
  lms/templates/courseware/xqa_interface.html
  lms/templates/staff_problem_info.html
  lms/urls.py
Labels: changes requested, open-source-contribution

#27162 FAL-249: fixes the blockstore runtime to set the correct translator
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
Labels: open-source-contribution, waiting on author
