Repository openedx/edx-platform, pull requests merged in 2021-11, with the labels that each got.

#29161 PR #27795 backport, Optionally run Codejail in a external service
  cms/envs/common.py
  common/lib/capa/capa/safe_exec/exceptions.py
  common/lib/capa/capa/safe_exec/remote_exec.py
  common/lib/capa/capa/safe_exec/safe_exec.py
  lms/envs/common.py
  requirements/edx-sandbox/py35-constraints.txt
  requirements/edx-sandbox/py35.in
  requirements/edx-sandbox/py35.txt
Labels: open-source-contribution, awaiting prioritization, automerge

#29099 feat: Add a new way to enable/disable teams [BD-38] [TNL-9175] [BB-5066]
  common/lib/xmodule/xmodule/tests/test_course_module.py
  lms/djangoapps/teams/plugins.py
  lms/djangoapps/teams/tests/test_views.py
  openedx/core/lib/teams_config.py
  openedx/core/lib/tests/test_teams_config.py
Labels: needs triage, blended

#29173 Backport to Lilac master: xblock-poll's export to CSV feature is not working [TNL-8370] [MNG-2273] [BB-4877]
  lms/envs/common.py
Labels: open-source-contribution, waiting on author, engineering review, core committer, automerge

#28981 feat: add anonymous settings to discussions api [BD-38] [TNL-8786] [BB-4973]
  lms/djangoapps/discussion/rest_api/api.py
  lms/djangoapps/discussion/rest_api/permissions.py
  lms/djangoapps/discussion/rest_api/serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_permissions.py
  lms/djangoapps/discussion/rest_api/tests/test_serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  lms/djangoapps/discussion/rest_api/tests/utils.py
  lms/djangoapps/discussion/rest_api/views.py
Labels: needs triage, blended

#29144 Add a data migration to copy all course index data into MySQL
  common/djangoapps/split_modulestore_django/migrations/0002_data_migration.py
Labels: open-source-contribution, engineering review, core committer

#29067 feat: add a file upload endpoint to the discussions REST API. [BD-38] [TNL-8779] [BB-4961]
  lms/djangoapps/discussion/rest_api/permissions.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  lms/djangoapps/discussion/rest_api/urls.py
  lms/djangoapps/discussion/rest_api/views.py
Labels: needs triage, blended

#28864 [BD-38][TNL-7615] [BB-4846] feat: Add discussion_enabled for Unit
  cms/djangoapps/contentstore/views/item.py
  cms/djangoapps/contentstore/views/tests/test_discussion_enabled.py
  common/lib/xmodule/xmodule/vertical_block.py
Labels: needs triage, blended

#29101 [SE-4631] add CCX ID to generated filename prefixes (#27028)
  common/djangoapps/util/file.py
  common/djangoapps/util/tests/test_file.py
  lms/envs/common.py
Labels: open-source-contribution, waiting on author, awaiting prioritization, automerge

#29100 [SE-4631] add CCX ID to generated filename prefixes (#27028)
  common/djangoapps/util/file.py
  common/djangoapps/util/tests/test_file.py
  lms/envs/common.py
Labels: open-source-contribution, waiting on author, awaiting prioritization, automerge

#29109 Flaky assetstore test
  common/lib/xmodule/xmodule/modulestore/tests/test_assetstore.py
Labels: open-source-contribution, awaiting prioritization, core committer

#29180 fix: fix issues with LANGUAGE_CODE for legacy UI [BB-4823] [OSPR-6196]
  lms/djangoapps/courseware/context_processor.py
  lms/djangoapps/courseware/tests/test_context_processor.py
Labels: open-source-contribution, ready to merge

#28571 [BD-13] Deprecate ModuleSystem.render_template
  cms/djangoapps/contentstore/views/helpers.py
  cms/djangoapps/contentstore/views/item.py
  cms/djangoapps/contentstore/views/preview.py
  cms/djangoapps/contentstore/views/tests/test_preview.py
  cms/lib/xblock/authoring_mixin.py
  common/djangoapps/edxmako/services.py
  common/djangoapps/edxmako/tests.py
  common/lib/xmodule/xmodule/annotatable_module.py
  common/lib/xmodule/xmodule/capa_module.py
  common/lib/xmodule/xmodule/conditional_module.py
  common/lib/xmodule/xmodule/error_module.py
  common/lib/xmodule/xmodule/html_module.py
  common/lib/xmodule/xmodule/library_content_module.py
  common/lib/xmodule/xmodule/library_root_xblock.py
  common/lib/xmodule/xmodule/lti_module.py
  common/lib/xmodule/xmodule/mako_module.py
  common/lib/xmodule/xmodule/poll_module.py
  common/lib/xmodule/xmodule/seq_module.py
  common/lib/xmodule/xmodule/split_test_module.py
  common/lib/xmodule/xmodule/studio_editable.py
  common/lib/xmodule/xmodule/template_module.py
  common/lib/xmodule/xmodule/tests/__init__.py
  common/lib/xmodule/xmodule/tests/helpers.py
  common/lib/xmodule/xmodule/tests/test_capa_module.py
  common/lib/xmodule/xmodule/tests/test_conditional.py
  common/lib/xmodule/xmodule/tests/test_delay_between_attempts.py
  common/lib/xmodule/xmodule/tests/test_editing_module.py
  common/lib/xmodule/xmodule/tests/test_html_module.py
  common/lib/xmodule/xmodule/tests/test_xml_module.py
  common/lib/xmodule/xmodule/vertical_block.py
  common/lib/xmodule/xmodule/video_module/video_module.py
  common/lib/xmodule/xmodule/word_cloud_module.py
  common/lib/xmodule/xmodule/x_module.py
  common/test/templates/edxmako.html
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/courseware/tests/helpers.py
  lms/djangoapps/courseware/tests/test_discussion_xblock.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/lms_xblock/test/test_runtime.py
  lms/envs/test.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
  openedx/core/lib/license/wrapper.py
  openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion/__init__.py
Labels: engineering review, blended

#29286 fix: "Uncaught TypeError: n is null" during login to LMS
  lms/static/js/spec/student_account/utils_spec.js
  lms/static/js/student_account/utils.js
Labels: open-source-contribution, waiting on author, core committer, automerge

#29297 Jsb/ha10 style fix
  cms/static/sass/elements/_header.scss
Labels: open-source-contribution, awaiting prioritization, automerge

#29082 feat: Adds a new discussion topic configuration mechanism [BD-38] [TNL-8623] [BB-4968]
  cms/djangoapps/contentstore/signals/handlers.py
  lms/djangoapps/course_wiki/tab.py
  lms/djangoapps/edxnotes/plugins.py
  lms/djangoapps/teams/plugins.py
  openedx/core/djangoapps/discussions/apps.py
  openedx/core/djangoapps/discussions/data.py
  openedx/core/djangoapps/discussions/handlers.py
  openedx/core/djangoapps/discussions/migrations/0007_add_discussion_topic_link.py
  openedx/core/djangoapps/discussions/models.py
  openedx/core/djangoapps/discussions/signals.py
  openedx/core/djangoapps/discussions/tasks.py
  openedx/core/djangoapps/discussions/tests/test_handlers.py
  openedx/core/djangoapps/discussions/tests/test_tasks.py
  openedx/features/lti_course_tab/tests.py
Labels: needs triage, blended

#29047 [SE-4891] feat: add optional but not toggled extra fields
  lms/envs/common.py
  lms/static/js/spec/student_account/register_spec.js
  lms/static/js/student_account/views/RegisterView.js
  openedx/core/djangoapps/user_api/helpers.py
  openedx/core/djangoapps/user_api/tests/test_helpers.py
  openedx/core/djangoapps/user_authn/views/registration_form.py
  openedx/core/djangoapps/user_authn/views/tests/test_login.py
  openedx/core/djangoapps/user_authn/views/tests/test_reset_password.py
Labels: open-source-contribution, awaiting prioritization

#29314 fix!: Removes the openedx provider temporarily [BD-38] [TNL-9269]
  openedx/core/djangoapps/discussions/models.py
  openedx/core/djangoapps/discussions/serializers.py
Labels: needs triage, blended

#29259 feat: Hide discussion block in studio if non-legacy discussion provider is configured for course [BD-38] [TNL-8699] [BB-4928]
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/views/tests/test_item.py
Labels: needs triage, blended

#28557 fix: do not remove comments from XML during course import
  cms/djangoapps/contentstore/views/tests/test_import_export.py
  common/lib/xmodule/xmodule/library_content_module.py
  common/lib/xmodule/xmodule/modulestore/xml.py
  common/lib/xmodule/xmodule/tests/test_library_content.py
  common/lib/xmodule/xmodule/xml_module.py
Labels: open-source-contribution, awaiting prioritization, core committer

#29262 feat!: Change the way tabs are ordered [BD-38] [TNL-9174] [BB-5076]
  cms/djangoapps/contentstore/rest_api/v0/tests/test_tabs.py
  cms/djangoapps/contentstore/rest_api/v0/views/advanced_settings.py
  cms/djangoapps/contentstore/rest_api/v0/views/tabs.py
  cms/djangoapps/contentstore/views/tabs.py
  cms/djangoapps/contentstore/views/tests/test_tabs.py
  cms/templates/edit-tabs.html
  common/lib/xmodule/xmodule/tabs.py
  lms/djangoapps/ccx/plugins.py
  lms/djangoapps/course_wiki/tab.py
  lms/djangoapps/courseware/tabs.py
  lms/djangoapps/courseware/tests/test_tabs.py
  lms/djangoapps/discussion/plugins.py
  lms/djangoapps/edxnotes/plugins.py
  lms/djangoapps/instructor/views/instructor_dashboard.py
  lms/djangoapps/teams/plugins.py
  openedx/features/lti_course_tab/tab.py
Labels: needs triage, blended

#29261 fix: In Studio, ALLOW_PUBLIC_ACCOUNT_CREATION flag does not show/hide signup section above footer.
  cms/templates/howitworks.html
Labels: open-source-contribution, awaiting prioritization

#29293 Add a data migration to copy all course index data into MySQL (Take 2)
  common/djangoapps/split_modulestore_django/migrations/0002_data_migration.py
Labels: open-source-contribution, awaiting prioritization, core committer

#29285 feat: Add support for using the discussions MFE UI instead of existing UI [BD-38] [TNL-9228]
  cms/envs/common.py
  cms/envs/devstack.py
  lms/djangoapps/courseware/tests/test_discussion_xblock.py
  lms/djangoapps/discussion/django_comment_client/tests/test_utils.py
  lms/djangoapps/discussion/plugins.py
  lms/djangoapps/discussion/toggles.py
  lms/djangoapps/discussion/views.py
  lms/envs/common.py
  lms/envs/devstack.py
  openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion/__init__.py
Labels: needs triage, blended

#29315 [SE-4891] Cherry pick: feat: add `optional-exposed` extra field type to registration form
  lms/envs/common.py
  lms/static/js/spec/student_account/register_spec.js
  lms/static/js/student_account/views/RegisterView.js
  openedx/core/djangoapps/user_api/helpers.py
  openedx/core/djangoapps/user_api/tests/test_helpers.py
  openedx/core/djangoapps/user_authn/views/registration_form.py
  openedx/core/djangoapps/user_authn/views/tests/test_login.py
  openedx/core/djangoapps/user_authn/views/tests/test_reset_password.py
Labels: open-source-contribution, awaiting prioritization, automerge

#29413 Add a data migration to copy all course index data into MySQL (Take 3)
  common/djangoapps/split_modulestore_django/migrations/0002_data_migration.py
Labels: open-source-contribution, waiting on author, core committer

#29354 [BD-13] Deprecate ModuleSystem.render_template (fixed)
  cms/djangoapps/contentstore/views/helpers.py
  cms/djangoapps/contentstore/views/item.py
  cms/djangoapps/contentstore/views/preview.py
  cms/djangoapps/contentstore/views/tests/test_preview.py
  cms/lib/xblock/authoring_mixin.py
  cms/lib/xblock/test/test_authoring_mixin.py
  common/djangoapps/edxmako/services.py
  common/djangoapps/edxmako/tests.py
  common/lib/xmodule/xmodule/annotatable_module.py
  common/lib/xmodule/xmodule/capa_module.py
  common/lib/xmodule/xmodule/conditional_module.py
  common/lib/xmodule/xmodule/error_module.py
  common/lib/xmodule/xmodule/html_module.py
  common/lib/xmodule/xmodule/library_content_module.py
  common/lib/xmodule/xmodule/library_root_xblock.py
  common/lib/xmodule/xmodule/lti_module.py
  common/lib/xmodule/xmodule/mako_module.py
  common/lib/xmodule/xmodule/poll_module.py
  common/lib/xmodule/xmodule/seq_module.py
  common/lib/xmodule/xmodule/split_test_module.py
  common/lib/xmodule/xmodule/studio_editable.py
  common/lib/xmodule/xmodule/template_module.py
  common/lib/xmodule/xmodule/tests/__init__.py
  common/lib/xmodule/xmodule/tests/helpers.py
  common/lib/xmodule/xmodule/tests/test_capa_module.py
  common/lib/xmodule/xmodule/tests/test_conditional.py
  common/lib/xmodule/xmodule/tests/test_delay_between_attempts.py
  common/lib/xmodule/xmodule/tests/test_editing_module.py
  common/lib/xmodule/xmodule/tests/test_html_module.py
  common/lib/xmodule/xmodule/tests/test_xml_module.py
  common/lib/xmodule/xmodule/vertical_block.py
  common/lib/xmodule/xmodule/video_module/video_module.py
  common/lib/xmodule/xmodule/word_cloud_module.py
  common/lib/xmodule/xmodule/x_module.py
  common/test/templates/edxmako.html
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/courseware/tests/helpers.py
  lms/djangoapps/courseware/tests/test_discussion_xblock.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/lms_xblock/test/test_runtime.py
  lms/envs/test.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
  openedx/core/lib/license/wrapper.py
  openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion/__init__.py
Labels: needs triage, blended

#29317 Fixed toggle name for ENABLE_PASSWORD_RESET_FAILURE_EMAIL
  lms/envs/common.py
Labels: open-source-contribution, changes requested
