Repository openedx/edx-platform, pull requests merged in 2021-01, with the labels that each got.

#25696 [BD-04] Convert SplitTest XModule to XBlock. [SE-3640]
  cms/djangoapps/contentstore/views/tests/test_group_configurations.py
  cms/djangoapps/contentstore/views/tests/test_item.py
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/split_test_module.py
  common/lib/xmodule/xmodule/tests/test_split_test_module.py
  lms/templates/split_test_author_view.html
Labels: blended, engineering review

#25927 Extend appropriate proctoring exam modes if provider allows it.
  lms/djangoapps/courseware/rules.py
  lms/djangoapps/courseware/tests/test_rules.py
Labels: engineering review, open-source-contribution

#25330 Remove CAS settings; part of DEPR-6
  cms/devstack.yml
  cms/envs/common.py
  lms/devstack.yml
  lms/envs/common.py
Labels: awaiting prioritization, core committer, open-source-contribution

#24789 Added a configuration flag to force third party auth
  lms/envs/production.py
  lms/static/js/spec/student_account/login_spec.js
  lms/static/js/spec/student_account/register_spec.js
  lms/static/js/student_account/views/AccessView.js
  lms/static/js/student_account/views/LoginView.js
  lms/static/js/student_account/views/RegisterView.js
  lms/templates/student_account/login.underscore
  lms/templates/student_account/register.underscore
  openedx/core/djangoapps/user_authn/toggles.py
  openedx/core/djangoapps/user_authn/views/login.py
  openedx/core/djangoapps/user_authn/views/login_form.py
  openedx/core/djangoapps/user_authn/views/register.py
  openedx/core/djangoapps/user_authn/views/tests/test_login.py
  openedx/core/djangoapps/user_authn/views/tests/test_register.py
Labels: cc-reviewer, open edx community review, open-source-contribution

#25570 [BD-04] Convert ErrorModule and NonStaffErrorModule to XBlocks. [SE-3191]
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/views/preview.py
  common/djangoapps/student/tests/test_course_listing.py
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/conditional_module.py
  common/lib/xmodule/xmodule/error_module.py
  common/lib/xmodule/xmodule/modulestore/mongo/base.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/split.py
  common/lib/xmodule/xmodule/modulestore/xml.py
  common/lib/xmodule/xmodule/tests/__init__.py
  common/lib/xmodule/xmodule/tests/test_conditional.py
  common/lib/xmodule/xmodule/tests/test_error_module.py
  common/lib/xmodule/xmodule/tests/test_import.py
  common/lib/xmodule/xmodule/x_module.py
  lms/djangoapps/ccx/models.py
  lms/djangoapps/courseware/access.py
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/courseware/rules.py
  lms/djangoapps/courseware/tests/tests.py
  openedx/core/djangoapps/content/course_overviews/models.py
  openedx/core/djangoapps/content/course_overviews/tests/test_course_overviews.py
Labels: blended, engineering review

#25695 [SE-3381] Allows adding new tinymce plugins through platform configuration
  cms/envs/common.py
  common/lib/xmodule/xmodule/js/src/html/edit.js
  docs/guides/extension_points.rst
  docs/guides/extensions/tinymce_plugins.rst
  openedx/core/djangoapps/util/management/commands/print_setting.py
  pavelib/assets.py
  pavelib/paver_tests/test_servers.py
  pavelib/utils/envs.py
  webpack.dev.config.js
  webpack.prod.config.js
Labels: cc-reviewer, open edx community review, open-source-contribution

#26041 [BD-21] Upgrade edx-toggles to 2.0.0
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: blended, needs triage

#26042 [BD-21] Document non-namespaced waffle classes in ADR
  openedx/core/djangoapps/waffle_utils/docs/decisions/0004-waffle-util-namespacing.rst
Labels: blended, needs triage

#26017 [BD-21] Get rid of calls to `set_request_cache_with_short_name`
  lms/djangoapps/course_api/blocks/tests/test_api.py
  openedx/core/djangoapps/content/block_structure/config/__init__.py
  openedx/core/djangoapps/content/block_structure/management/commands/generate_course_blocks.py
  openedx/core/djangoapps/content/block_structure/manager.py
  openedx/core/djangoapps/content/block_structure/signals.py
  openedx/core/djangoapps/content/block_structure/store.py
  openedx/core/djangoapps/content/block_structure/tasks.py
  openedx/core/djangoapps/content/block_structure/tests/test_manager.py
  openedx/core/djangoapps/content/block_structure/tests/test_signals.py
  openedx/core/djangoapps/content/block_structure/tests/test_store.py
  openedx/core/djangoapps/coursegraph/management/commands/tests/test_dump_to_neo4j.py
Labels: blended, needs triage

#25278 Change data-language format to ISO639-1
  lms/djangoapps/courseware/date_summary.py
Labels: engineering review, open-source-contribution

#25978 [SE-3440] Adds grade cutoffs to gradebook grading information
  lms/djangoapps/grades/rest_api/v1/gradebook_views.py
  lms/djangoapps/grades/rest_api/v1/tests/test_gradebook_views.py
Labels: open-source-contribution, ready to merge

#25020 [ADD] /user_api endpoints in api-docs
  docs/swagger.yaml
  lms/static/js/spec/student_account/account_settings_factory_spec.js
  lms/static/js/spec/student_account/account_settings_fields_spec.js
  lms/static/js/spec/student_account/emailoptin_spec.js
  lms/static/js/spec/student_account/login_spec.js
  lms/static/js/spec/student_account/register_spec.js
  lms/static/js/student_account/emailoptin.js
  lms/static/js/student_account/views/account_settings_fields.js
  openedx/core/djangoapps/user_api/legacy_urls.py
  openedx/core/djangoapps/user_api/tests/test_views.py
  openedx/core/djangoapps/user_api/urls.py
  openedx/core/djangoapps/user_api/views.py
  openedx/core/djangoapps/user_authn/urls_common.py
  openedx/core/djangoapps/user_authn/views/login.py
Labels: open-source-contribution, ready to merge

#26080 Fix Markdown errors on discussions tab
  lms/djangoapps/discussion/views.py
Labels: engineering review, open-source-contribution

#25771 Fix `paver update_assets` warning on missing sass dir
  pavelib/assets.py
Labels: awaiting prioritization, open-source-contribution, waiting on author

#25537 [MCKIN-26432] [BB-3158] Add Unit to breadcrumbs navigation
  cms/djangoapps/contentstore/views/component.py
  cms/templates/container.html
Labels: cc-reviewer, open edx community review, open-source-contribution

#25572 [SE-3530] Adds Boto3 support for Import/Export functionality
  cms/djangoapps/contentstore/views/import_export.py
  cms/djangoapps/contentstore/views/tests/test_import_export.py
Labels: cc-reviewer, engineering review, open-source-contribution

#25910 [BD-03] [TNL-7805] [BB-3371] LTI Discussion Tab
  lms/djangoapps/ccx/tests/test_field_override_performance.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/views/views.py
  lms/djangoapps/discussion/plugins.py
  lms/urls.py
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/tests/views/test_course_updates.py
  openedx/features/lti_course_tab/__init__.py
  openedx/features/lti_course_tab/tab.py
  openedx/features/lti_course_tab/tests.py
  requirements/edx-sandbox/py35.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
  setup.py
Labels: blended, needs triage

#26124 Bump version of lti-consumer-xblock to include fixed migrations
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#26135 [MNG-1904] Fix: update new runtime's runtime.anonymous_student_id to store in DB
  common/djangoapps/student/migrations/0039_anon_id_context.py
  common/djangoapps/student/models.py
  openedx/core/djangoapps/xblock/runtime/shims.py
Labels: core committer, open-source-contribution, waiting on author

#24800 Fix TypeError during transcript upload to S3
  cms/djangoapps/contentstore/views/transcript_settings.py
  cms/djangoapps/contentstore/views/transcripts_ajax.py
  common/lib/xmodule/xmodule/video_module/video_handlers.py
Labels: engineering review, open-source-contribution

#26152 Enable annotation linting with edx-lint
  lms/djangoapps/bulk_email/models.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution

#26159 [TSD] adds settings annotations for XBLOCK_FIELD_DATA_WRAPPERS
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#26165 [TSD] adds annotations for XBLOCK_RUNTIME_V2_EPHEMERAL_DATA_CACHE
  lms/envs/common.py
Labels: changes requested, open-source-contribution

#26172 [BD-21] Fix `ERROR_ON_DEPRECATED_EDX_PLATFORM_IMPORTS` code annotation
  cms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#25955 [BD-04] [SE-3708] Convert HiddenDescriptor to an XBlock.
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/hidden_module.py
  openedx/core/lib/xblock_utils/__init__.py
Labels: blended, waiting on author

#25949 add PR template
  .github/pull_request_template.md
Labels: core committer, open-source-contribution, waiting on author

#25777 [BB-3306] Customizable Certificate Date Format
  lms/djangoapps/certificates/views/webview.py
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26167 [TSD] add toggle annotations for DEFAULT_MOBILE_AVAILABLE
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26163 [TSD] adds annotations for XBLOCK_SETTINGS
  lms/envs/common.py
Labels: changes requested, open-source-contribution

#26164 [TSD] adds annotations for XBLOCK_SELECT_FUNCTION
  lms/envs/common.py
Labels: changes requested, open-source-contribution

#26226 [TSD] annotations for student.courseenrollment_admin
  common/djangoapps/student/__init__.py
  common/djangoapps/student/admin.py
Labels: open-source-contribution, waiting on author

#26220 [TSD] add annotations for ALLOW_EMAIL_ADDRESS_CHANGE feature flag
  lms/envs/common.py
Labels: engineering review, open-source-contribution, rejected

#26256 [TSD] Adding FEATURES[‘ENABLE_EDXNOTES’] annotations
  cms/envs/common.py
  lms/envs/common.py
Labels: needs triage, open-source-contribution
