Repository openedx/edx-platform, pull requests merged in 2021-02, with the labels that each got.

#25957 fix: "Invalid type for parameter ContentType" error on js upload
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: changes requested, open-source-contribution

#26177 [TSD] [SE-3990] Add in standardized documentation for Badgr-related settings.
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26169 [TSD] Annotate course_experience.calendar_sync
  openedx/features/course_experience/__init__.py
Labels: engineering review, open-source-contribution

#26058 [BD-21] Improve test coverage of toggle state view
  openedx/core/djangoapps/waffle_utils/tests/test_views.py
  openedx/core/djangoapps/waffle_utils/views.py
Labels: blended, needs triage

#26040 [BD-21] Remove soon-to-be-deprecated value monitor in edx-toggles
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/core/djangoapps/waffle_utils/tests/test_init.py
Labels: blended, needs triage

#26175 [TSD] Annotates block structures settings and waffle switches
  lms/envs/common.py
  openedx/core/djangoapps/content/block_structure/config/__init__.py
  openedx/core/djangoapps/content/block_structure/models.py
Labels: engineering review, open-source-contribution

#26252 [TSD] add annotations for the DISABLE_LOGIN_BUTTON feature flag
  lms/envs/common.py
Labels: core committer, engineering review, open-source-contribution, waiting on author

#26261 [TSD] Adding annotations for edx_notes_api settings
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26251 [TSD] Adding annotations for User Retirement settings
  cms/envs/common.py
  lms/envs/common.py
Labels: engineering review, needs triage, open-source-contribution

#26245 [TSD] add annotations for DISABLE_MOBILE_COURSE_AVAILABLE feature flag
  cms/envs/common.py
Labels: engineering review, open-source-contribution

#26248 [TSD] add annotations for ALLOW_COURSE_RERUNS feature flag
  cms/envs/common.py
Labels: engineering review, open-source-contribution

#26183 [TSD] Documents maintenance banner switch and setting and updates switch
  lms/envs/common.py
  openedx/core/djangoapps/util/maintenance_banner.py
  openedx/core/djangoapps/util/tests/test_maintenance_banner.py
  openedx/core/djangoapps/util/waffle.py
Labels: engineering review, open-source-contribution

#26354 [TSD] add annotations for ENABLE_BULK_ENROLLMENT_VIEW feature flag
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#26353 [TSD] add annotations for ENABLE_ACCOUNT_DELETION feature flag
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#26352 [TSD] adds annotations for COURSES_ARE_BROWSABLE feature flag
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#26350 [TSD] annotations for ALWAYS_REDIRECT_HOMEPAGE_TO_DASHBOARD_FOR_AUTHENTICATED_USER
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#26046 [BTR-53] [BB-3502] Misuse of urljoin in Gradebook URL from Instructor Panel
  lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
  lms/djangoapps/instructor/views/instructor_dashboard.py
Labels: cc-reviewer, engineering review, open-source-contribution

#26205 [TSD] add toggle annotations for FEATURES['ENABLE_DISCUSSION_SERVICE']
  cms/envs/common.py
  lms/envs/common.py
Labels: open-source-contribution, rejected

#26262 [TSD]Adding toggle annotations for wiki settings
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26374 [BD-21] Upgrade usage of edx_toggles.toggles
  openedx/core/djangoapps/content/block_structure/config/__init__.py
Labels: blended, needs triage

#25872 [SE-3685] Hide footer links if unconfigured in Certificates
  lms/djangoapps/certificates/tests/test_webview_views.py
  lms/templates/certificates/_accomplishment-footer.html
Labels: engineering review, open-source-contribution

#26406 [TSD] docs: Add annotations for ENABLE_STUDENT_HISTORY_VIEW feature flag
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26212 [TSD] Add annotations for MFE URL settings
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26403 [TSD] docs: Adds annotations for HIDE_DASHBOARD_COURSES_UNTIL_ACTIVATED feature flag
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26388 [TSD] docs: Add annotations for ENABLE_DJANGO_ADMIN_SITE feature flag
  lms/envs/common.py
Labels: engineering review, needs triage, open-source-contribution

#26401 [TSD] docs: Add annotations for EDITABLE_SHORT_DESCRIPTION feature flag
  cms/envs/common.py
Labels: engineering review, open-source-contribution

#26389 [TSD] docs: Add annotations for ENABLE_FOOTER_MOBILE_APP_LINKS feature flag
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26202 [TSD] [SE-3988] add annotations to instructor plugin settings
  lms/djangoapps/instructor/settings/common.py
Labels: engineering review, open-source-contribution

#26230 [SE-3989] - Fixes for Blockstore integration tests.
  openedx/core/djangoapps/content_libraries/libraries_index.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
Labels: cc-reviewer, engineering review, open-source-contribution

#26243 [TSD] Annotate git export settings and toggles in CMS
  cms/djangoapps/contentstore/git_export_utils.py
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/models/settings/course_metadata.py
  cms/envs/common.py
  cms/templates/widgets/header.html
  cms/urls.py
Labels: awaiting prioritization, open-source-contribution

#26469 [TSD] add annotations for ENABLE_HTML_XBLOCK_STUDENT_VIEW_DATA feature flag
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#26266 [TSD] Annotate comprehensive theming settings
  cms/envs/common.py
  lms/envs/common.py
  openedx/core/djangoapps/theming/checks.py
  openedx/core/djangoapps/theming/helpers.py
Labels: changes requested, open-source-contribution

#26416 [TSD] Annotate schedules debugging toggle
  openedx/core/djangoapps/schedules/config.py
Labels: awaiting prioritization, open-source-contribution

#26492 [TSD] add annotation for the header & footer language selector
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#26428 [TSD] add annotations for login failure settings and feature flags
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#25713 [BD-04] Convert LTI XModule to XBlock. [SE-3640]
  common/lib/xmodule/setup.py
  common/lib/xmodule/xmodule/lti_2_util.py
  common/lib/xmodule/xmodule/lti_module.py
  common/lib/xmodule/xmodule/static_content.py
  common/lib/xmodule/xmodule/tests/test_lti20_unit.py
  common/lib/xmodule/xmodule/tests/test_lti_unit.py
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/courseware/tests/test_lti_integration.py
  lms/djangoapps/courseware/tests/test_module_render.py
Labels: blended, ready to merge

#26455 [TSD] add annotations for courseware and dashboard search feature flag
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#25984 Fix PY3 incompatible division
  lms/djangoapps/discussion/rest_api/api.py
Labels: engineering review, open-source-contribution

#26393 Remove surplus %20 and + from links to twitter and email
  lms/templates/courseware/course_about_sidebar_header.html
Labels: engineering review, open-source-contribution, waiting on author

#26119 [BB-3335] Fix flexbox not wrapping on mobile devices in preview menu
  lms/templates/preview_menu.html
Labels: awaiting prioritization, open-source-contribution

#26405 Only show sequence list horizontal scrollbar when the width of the screen is xs
  common/lib/xmodule/xmodule/css/sequence/display.scss
Labels: awaiting prioritization, open-source-contribution

#26056 Fix sidebar width on course about page when screen resolution less than 768px
  lms/static/sass/multicourse/_course_about.scss
Labels: awaiting prioritization, open-source-contribution

#20955 SE-1168 [FAL-92] implement ORA process summary report csv
  lms/djangoapps/instructor/tests/test_api.py
  lms/djangoapps/instructor/views/api.py
  lms/djangoapps/instructor/views/api_urls.py
  lms/djangoapps/instructor/views/instructor_dashboard.py
  lms/djangoapps/instructor_task/api.py
  lms/djangoapps/instructor_task/tasks.py
  lms/djangoapps/instructor_task/tasks_helper/misc.py
  lms/djangoapps/instructor_task/tests/test_tasks.py
  lms/djangoapps/instructor_task/tests/test_tasks_helper.py
  lms/templates/instructor/instructor_dashboard_2/data_download.html
Labels: open-source-contribution, ready to merge

#26093 [SE-3949] remove absolute positioning to allow RTL scrolling
  lms/static/sass/course/_gradebook.scss
Labels: engineering review, open-source-contribution

#26704 [TSD] add annotations for AUTOMATIC_VERIFY_STUDENT_IDENTITY_FOR_TESTING feature flag
  lms/envs/common.py
Labels: awaiting prioritization, open-source-contribution

#26094 [SE-3949] remove absolute positioning to allow RTL scrolling
  lms/static/sass/course/_gradebook.scss
Labels: engineering review, open-source-contribution

#26708 [TSD] add annotations for DISPLAY_HISTOGRAMS_TO_STAFF feature flag
  lms/envs/common.py
Labels: open-source-contribution, ready to merge
