Repository openedx/edx-platform, pull requests merged in 2021-06, with the labels that each got.

#27181 Badgr integration updates
  lms/djangoapps/badges/backends/badgr.py
  lms/djangoapps/badges/backends/tests/test_badgr_backend.py
  lms/djangoapps/badges/migrations/0004_badgeclass_badgr_server_slug.py
  lms/djangoapps/badges/models.py
  lms/djangoapps/badges/tests/factories.py
  lms/djangoapps/badges/tests/test_models.py
  lms/envs/common.py
Labels: engineering review, open-source-contribution

#25843 [BD-24] [BB-2726] [TNL-7330] Added Course Membership API function
  common/djangoapps/student/models.py
  lms/djangoapps/course_api/api.py
  lms/djangoapps/course_api/exceptions.py
  lms/djangoapps/course_api/tests/mixins.py
  lms/djangoapps/course_api/tests/test_api.py
  lms/envs/common.py
Labels: blended, needs triage

#27717 [FAL-249] chore: update DnD xblock version
  requirements/edx-sandbox/py35.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: awaiting prioritization, cc-reviewer, open-source-contribution

#27844 [BD-27] FEAT: Add new API endpoint for uploading transcripts
  cms/djangoapps/contentstore/views/tests/test_transcript_settings.py
  cms/djangoapps/contentstore/views/transcript_settings.py
  cms/urls.py
Labels: blended, needs triage

#27810 [BD-26] feat: add temporary waffle flag for enabling disabling proctored exams
  common/lib/xmodule/xmodule/seq_module.py
  lms/djangoapps/courseware/toggles.py
  openedx/core/djangoapps/courseware_api/serializers.py
  openedx/core/djangoapps/courseware_api/tests/test_views.py
  openedx/core/djangoapps/courseware_api/views.py
Labels: blended, community manager review

#27644 refactor: remove deprecated mongodb client class
  common/lib/xmodule/xmodule/mongo_utils.py
Labels: engineering review, open-source-contribution

#23171 [BB-2059] Remove deprecated city field from student features report
  lms/djangoapps/instructor_analytics/basic.py
Labels: cc-reviewer, changes requested, open-source-contribution

#27799 fix: handle opening verticals in new tabs with the "View In Studio" button [BB-4211]
  lms/templates/preview_menu.html
Labels: awaiting prioritization, open-source-contribution

#27269 [SE-4304] Allow custom upload directory and filename for grade and calculated profile reports
  lms/djangoapps/instructor_task/api.py
  lms/djangoapps/instructor_task/models.py
  lms/djangoapps/instructor_task/tasks_helper/enrollments.py
  lms/djangoapps/instructor_task/tasks_helper/grades.py
  lms/djangoapps/instructor_task/tasks_helper/utils.py
  lms/djangoapps/instructor_task/tests/test_integration.py
  lms/djangoapps/instructor_task/tests/test_tasks_helper.py
Labels: engineering review, open-source-contribution, waiting on author

#27867 feat: Removing references to Google Plus
  edxapp.sql
  lms/djangoapps/bulk_email/fixtures/course_email_template.json
  lms/djangoapps/bulk_email/fixtures/plain-html-no-newlines-or-tabs.txt
  lms/djangoapps/bulk_email/fixtures/plain-html-no-newlines.txt
  lms/djangoapps/bulk_email/fixtures/plain-html.txt
Labels: engineering review, open-source-contribution

#27950 feat: redirect to 'contact' page if zendesk url is not defined
  lms/djangoapps/support/tests/test_views.py
  lms/djangoapps/support/views/contact_us.py
Labels: changes requested, open-source-contribution

#27542 feat: Course Apps API [BD-38] [TNL-8103] [BB-2716]
  docs/swagger.yaml
  lms/djangoapps/course_wiki/plugins/__init__.py
  lms/djangoapps/courseware/plugins.py
  lms/djangoapps/discussion/rest_api/api.py
  lms/djangoapps/edxnotes/plugins.py
  lms/djangoapps/grades/rest_api/v1/gradebook_views.py
  lms/djangoapps/grades/rest_api/v1/views.py
  lms/djangoapps/program_enrollments/rest_api/v1/utils.py
  lms/djangoapps/teams/plugins.py
  openedx/core/djangoapps/content/learning_sequences/views.py
  openedx/core/djangoapps/course_apps/__init__.py
  openedx/core/djangoapps/course_apps/api.py
  openedx/core/djangoapps/course_apps/apps.py
  openedx/core/djangoapps/course_apps/migrations/__init__.py
  openedx/core/djangoapps/course_apps/models.py
  openedx/core/djangoapps/course_apps/plugins.py
  openedx/core/djangoapps/course_apps/rest_api/__init__.py
  openedx/core/djangoapps/course_apps/rest_api/tests/__init__.py
  openedx/core/djangoapps/course_apps/rest_api/tests/test_views.py
  openedx/core/djangoapps/course_apps/rest_api/urls.py
  openedx/core/djangoapps/course_apps/rest_api/v1/urls.py
  openedx/core/djangoapps/course_apps/rest_api/v1/views.py
  openedx/core/djangoapps/course_apps/tests/__init__.py
  openedx/core/djangoapps/course_apps/tests/test_api.py
  openedx/core/djangoapps/course_apps/tests/utils.py
  openedx/core/djangoapps/course_apps/toggles.py
  openedx/core/djangoapps/discussions/plugins.py
  openedx/core/djangoapps/discussions/views.py
  openedx/core/lib/api/tests/test_view_utils.py
  openedx/core/lib/api/view_utils.py
  openedx/core/lib/teams_config.py
  setup.py
Labels: blended, needs triage

#27193 docs: ADR for new course apps API [BD-38] [TNL-8002] [BB-3964]
  openedx/core/djangoapps/course_apps/docs/decisions/001-course-apps.rst
Labels: blended, changes requested

#27529 refactor: Move CourseEditLTIFieldsEnabledFlag to xblock-lti-consumer [BD-38] [TNL-8104]
  cms/djangoapps/contentstore/views/item.py
  cms/djangoapps/xblock_config/admin.py
  cms/djangoapps/xblock_config/forms.py
  cms/djangoapps/xblock_config/migrations/0003_move_course_edit_lti_fields_enabled_flag_model_to_lti_consumer.py
  cms/djangoapps/xblock_config/models.py
  cms/djangoapps/xblock_config/tests/__init__.py
  cms/djangoapps/xblock_config/tests/test_models.py
  requirements/constraints.txt
  requirements/edx-sandbox/py35.txt
  requirements/edx-sandbox/py38.txt
  requirements/edx/base.txt
  requirements/edx/coverage.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/paver.txt
  requirements/edx/pip-tools.txt
  requirements/edx/testing.txt
  scripts/xblock/requirements.txt
Labels: blended, needs triage

#28058 fix: Creates a squashed migration for xblock_config that removes moved model
  cms/djangoapps/xblock_config/migrations/0001_squashed_0003_move_course_edit_lti_fields_enabled_flag_model_to_lti_consumer.py
Labels: needs triage, open-source-contribution

#28019 fix: xblock-poll's export to CSV feature is not working [TNL-8370] [MNG-2273]
  lms/envs/common.py
Labels: core committer, open-source-contribution, waiting on author

#27022 fix: Align answer submission notification to bottom of viewport if out of view
  lms/templates/courseware/courseware.html
Labels: engineering review, open-source-contribution
