Repository openedx/edx-platform, pull requests merged in 2021-08, with the labels that each got.

#28105 Translate prerequisite section banner text
  common/lib/xmodule/xmodule/seq_module.py
Labels: awaiting prioritization, open-source-contribution

#26760 making LOGIN_REDIRECT_WHITELIST configurable through env files
  cms/envs/production.py
  lms/envs/common.py
  lms/envs/devstack.py
  lms/envs/production.py
Labels: cc-reviewer, engineering review, open-source-contribution

#28347 feat: Adds a new flag for discussions LTI configuration for admin only config [BD-38] [TNL-8442]
  openedx/core/djangoapps/discussions/models.py
Labels: blended, waiting on author

#28300 feat: redirect to 'contact' page if zendesk url is not defined
  lms/djangoapps/support/tests/test_views.py
  lms/djangoapps/support/views/contact_us.py
Labels: automerge, open-source-contribution, ready to merge

#28327 feat: Supply documentaion links for course apps from the backend [BD-38] [TNL-8446] [BB-4462]
  cms/envs/common.py
  lms/djangoapps/course_wiki/plugins/__init__.py
  lms/djangoapps/courseware/plugins.py
  lms/djangoapps/edxnotes/plugins.py
  lms/djangoapps/teams/plugins.py
  lms/envs/common.py
  openedx/core/djangoapps/course_apps/plugins.py
  openedx/core/djangoapps/course_apps/rest_api/v1/views.py
  openedx/core/djangoapps/discussions/plugins.py
Labels: blended, needs triage

#28038 fix: Produce grade report when subsections have future start dates [BB-4005]
  lms/djangoapps/grades/course_data.py
  lms/djangoapps/grades/course_grade.py
  lms/djangoapps/instructor_task/tests/test_tasks_helper.py
Labels: automerge, awaiting prioritization, open-source-contribution

#28250 FAL-2076 Cherry-picks #28066 into lilac.master
  cms/envs/common.py
  cms/envs/production.py
  lms/envs/common.py
  lms/envs/production.py
Labels: automerge, engineering review, open-source-contribution, waiting on author

#27278 Remove some unused code from split modulestore
  common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/split.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/split_draft.py
  common/lib/xmodule/xmodule/modulestore/tests/test_split_modulestore.py
  common/lib/xmodule/xmodule/modulestore/tests/test_split_modulestore_bulk_operations.py
Labels: open-source-contribution, engineering review, core committer

#28336 Run modulestore tests in common/lib/... using Django
  cms/djangoapps/contentstore/tests/test_courseware_index.py
  common/lib/pytest.ini
  common/lib/xmodule/xmodule/modulestore/django.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py
  common/lib/xmodule/xmodule/modulestore/tests/django_utils.py
  common/lib/xmodule/xmodule/modulestore/tests/test_mixed_modulestore.py
  common/lib/xmodule/xmodule/modulestore/tests/test_mongo.py
  common/lib/xmodule/xmodule/modulestore/tests/test_semantics.py
  common/lib/xmodule/xmodule/modulestore/tests/test_split_modulestore.py
  common/lib/xmodule/xmodule/modulestore/tests/utils.py
  common/lib/xmodule/xmodule/tests/test_conditional.py
  common/lib/xmodule/xmodule/tests/test_course_module.py
  common/lib/xmodule/xmodule/tests/test_services.py
  lms/djangoapps/edxnotes/decorators.py
  openedx/tests/completion_integration/test_services.py
  openedx/tests/settings.py
  pavelib/utils/test/suites/pytest_suite.py
Labels: open-source-contribution, engineering review, core committer

#28124 fix: courseware-chromeless: cancel click event only when target is found
  lms/templates/courseware/courseware-chromeless.html
Labels: open-source-contribution, awaiting prioritization

#27715 Add a content libraries import from courseware API and management command [SE-4619]
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/management/commands/content_libraries_import.py
  openedx/core/djangoapps/content_libraries/migrations/0005_contentlibraryblockimporttask.py
  openedx/core/djangoapps/content_libraries/models.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tasks.py
  openedx/core/djangoapps/content_libraries/tests/test_api.py
  openedx/core/djangoapps/content_libraries/tests/test_command_content_libraries_import.py
  openedx/core/djangoapps/content_libraries/urls.py
  openedx/core/djangoapps/content_libraries/views.py
  openedx/core/djangoapps/olx_rest_api/adapters.py
Labels: open-source-contribution, changes requested, cc-reviewer

#27197 Add toggle to redirect user to the login page on unauthenticated enrollement
  lms/templates/courseware/course_about.html
Labels: open-source-contribution, changes requested

#28525 refactor: changed create_user with UserFactory to avoid errors
  cms/djangoapps/cms_user_tasks/tests.py
  cms/djangoapps/contentstore/tests/test_i18n.py
  cms/djangoapps/contentstore/tests/test_permissions.py
  cms/djangoapps/contentstore/views/tests/test_access.py
  cms/djangoapps/contentstore/views/tests/test_user.py
  cms/djangoapps/course_creators/tests/test_admin.py
  cms/djangoapps/course_creators/tests/test_views.py
  common/djangoapps/student/tests/test_authz.py
  common/djangoapps/student/tests/tests.py
  common/djangoapps/third_party_auth/saml_configuration/tests/test_saml_configuration.py
  common/djangoapps/third_party_auth/samlproviderconfig/tests/test_samlproviderconfig.py
  common/djangoapps/third_party_auth/samlproviderdata/tests/test_samlproviderdata.py
  lms/djangoapps/ccx/api/v0/tests/test_views.py
  lms/djangoapps/course_goals/tests/test_api.py
  lms/djangoapps/course_home_api/outline/tests/test_goals.py
  lms/djangoapps/discussion/django_comment_client/base/tests.py
  lms/djangoapps/program_enrollments/rest_api/v1/tests/test_views.py
  lms/djangoapps/survey/tests/test_models.py
  lms/djangoapps/survey/tests/test_utils.py
  openedx/core/djangoapps/content/learning_sequences/api/tests/test_outlines.py
  openedx/core/djangoapps/django_comment_common/tests.py
  openedx/core/djangoapps/oauth_dispatch/tests/test_dot_overrides.py
  openedx/core/djangoapps/user_authn/views/tests/test_register.py
  openedx/core/lib/api/tests/test_authentication.py
Labels: open-source-contribution, needs triage

#28036 fix: Milestones app feature flag docs
  common/djangoapps/util/milestones_helpers.py
Labels: open-source-contribution, changes requested

#28547 refactor: replace User.objects.create_user for UserFactory p2
  cms/djangoapps/contentstore/views/tests/test_entrance_exam.py
  common/djangoapps/student/management/tests/test_change_enterprise_user_username.py
  common/djangoapps/student/tests/tests.py
  common/lib/xmodule/xmodule/modulestore/tests/django_utils.py
  lms/djangoapps/grades/management/commands/tests/test_compute_grades.py
  openedx/core/djangoapps/credit/tests/test_services.py
  openedx/core/djangoapps/user_authn/views/tests/test_login.py
Labels: open-source-contribution, needs triage

#27608 feat: Add REST APIs for course advanced settings and course tabs [BD-38] [TNL-8625] [BB-4132]
  cms/djangoapps/contentstore/rest_api/urls.py
  cms/djangoapps/contentstore/rest_api/v0/__init__.py
  cms/djangoapps/contentstore/rest_api/v0/serializers/__init__.py
  cms/djangoapps/contentstore/rest_api/v0/serializers/advanced_settings.py
  cms/djangoapps/contentstore/rest_api/v0/serializers/tabs.py
  cms/djangoapps/contentstore/rest_api/v0/tests/__init__.py
  cms/djangoapps/contentstore/rest_api/v0/tests/test_advanced_settings.py
  cms/djangoapps/contentstore/rest_api/v0/tests/test_tabs.py
  cms/djangoapps/contentstore/rest_api/v0/urls.py
  cms/djangoapps/contentstore/rest_api/v0/views/__init__.py
  cms/djangoapps/contentstore/rest_api/v0/views/advanced_settings.py
  cms/djangoapps/contentstore/rest_api/v0/views/tabs.py
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/views/tabs.py
  cms/djangoapps/models/settings/course_metadata.py
  openedx/core/lib/api/serializers.py
  openedx/core/lib/api/view_utils.py
Labels: needs triage, blended

#28161 revert: Removing read_committed argument when using outer_atomic
  common/djangoapps/course_modes/views.py
  common/djangoapps/student/views/management.py
  common/djangoapps/util/db.py
  common/djangoapps/util/tests/test_db.py
  lms/djangoapps/verify_student/views.py
  openedx/core/djangoapps/user_authn/views/register.py
Labels: open-source-contribution, ready to merge
