Repository openedx/edx-platform, pull requests merged in 2021-09, with the labels that each got.

#28415 feat: Emit course completion related events
  lms/djangoapps/grades/events.py
  lms/djangoapps/grades/models.py
  lms/djangoapps/grades/signals/handlers.py
  lms/djangoapps/grades/signals/signals.py
  lms/djangoapps/grades/tests/integration/test_events.py
  lms/djangoapps/grades/tests/test_models.py
  lms/djangoapps/grades/tests/test_signals.py
Labels: open-source-contribution, rejected

#27411 LTI 1.3 tool support for blockstore-based content (aka. "Content Libraries V2") [SE-4514]
  cms/envs/common.py
  cms/templates/content_libraries/xblock_iframe.html
  lms/envs/common.py
  openedx/core/djangoapps/content_libraries/admin.py
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/apps.py
  openedx/core/djangoapps/content_libraries/auth.py
  openedx/core/djangoapps/content_libraries/migrations/0005_ltigradedresource_ltiprofile.py
  openedx/core/djangoapps/content_libraries/migrations/0006_auto_20210615_1916.py
  openedx/core/djangoapps/content_libraries/migrations/0007_merge_20210818_0614.py
  openedx/core/djangoapps/content_libraries/migrations/0008_auto_20210818_2148.py
  openedx/core/djangoapps/content_libraries/models.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/signal_handlers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_auth.py
  openedx/core/djangoapps/content_libraries/tests/test_models.py
  openedx/core/djangoapps/content_libraries/tests/test_views_lti.py
  openedx/core/djangoapps/content_libraries/urls.py
  openedx/core/djangoapps/content_libraries/views.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, awaiting prioritization

#28552 Log a single-line warning in case of video_transcrip NotFound
  common/lib/xmodule/xmodule/video_module/video_handlers.py
Labels: open-source-contribution, engineering review

#28266 [BD-32] feat: 1st batch of Open edX Events
  common/djangoapps/student/models.py
  common/djangoapps/student/tests/test_enrollment.py
  common/djangoapps/student/tests/test_events.py
  openedx/core/djangoapps/user_authn/views/login.py
  openedx/core/djangoapps/user_authn/views/register.py
  openedx/core/djangoapps/user_authn/views/tests/test_events.py
  openedx/core/djangoapps/user_authn/views/tests/test_login.py
  openedx/core/djangoapps/user_authn/views/tests/test_register.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, blended

#27979 [OSPR-5869][BB-4385] Prevent course details AJAX request from getting into browser history
  cms/static/js/factories/settings.js
Labels: open-source-contribution, engineering review, cc-reviewer

#28619 fix: fetch commons.js from the correct URL [SE-4785]
  cms/templates/content_libraries/xblock_iframe.html
Labels: open-source-contribution, needs triage

#28555 fix: loading of profile images in devstack
  lms/urls.py
Labels: open-source-contribution, waiting on author

#28165 feat!: Add data model for course app API [BD-38] [TNL-8506] [BB-4470]
  openedx/core/djangoapps/course_apps/api.py
  openedx/core/djangoapps/course_apps/apps.py
  openedx/core/djangoapps/course_apps/handlers.py
  openedx/core/djangoapps/course_apps/management/__init__.py
  openedx/core/djangoapps/course_apps/management/commands/__init__.py
  openedx/core/djangoapps/course_apps/management/commands/cache_course_app_status.py
  openedx/core/djangoapps/course_apps/migrations/0001_initial.py
  openedx/core/djangoapps/course_apps/models.py
  openedx/core/djangoapps/course_apps/rest_api/v1/views.py
  openedx/core/djangoapps/course_apps/signals.py
  openedx/core/djangoapps/course_apps/tasks.py
  openedx/core/djangoapps/course_apps/tests/test_api.py
Labels: needs triage, blended

#28579 feat: created custom pages course app plugin [BD-38] [TNL-8543] [BB-4738]
  cms/envs/common.py
  lms/djangoapps/courseware/plugins.py
  lms/envs/common.py
  setup.py
Labels: needs triage, blended

#28464 Feature: Add permissions filter to courses API [SE-4588]
  lms/djangoapps/course_api/api.py
  lms/djangoapps/course_api/forms.py
  lms/djangoapps/course_api/tests/test_api.py
  lms/djangoapps/course_api/tests/test_forms.py
  lms/djangoapps/course_api/tests/test_views.py
  lms/djangoapps/course_api/views.py
  lms/djangoapps/courseware/courses.py
Labels: open-source-contribution, awaiting prioritization

#28642 feat: Added support for enterprise id in course_grade_passed_first_time event
  lms/djangoapps/grades/events.py
  openedx/features/enterprise_support/context.py
  openedx/features/enterprise_support/tests/test_context.py
  openedx/features/enterprise_support/utils.py
Labels: open-source-contribution, engineering review

#26616 [BB-3622] Add course creation condition for organisation
  cms/djangoapps/contentstore/tests/test_course_create_rerun.py
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/views/helpers.py
  cms/djangoapps/contentstore/views/library.py
  cms/djangoapps/contentstore/views/tests/test_library.py
  cms/djangoapps/course_creators/admin.py
  cms/djangoapps/course_creators/migrations/0002_add_org_support_for_course_creators.py
  cms/djangoapps/course_creators/models.py
  cms/djangoapps/course_creators/tests/test_views.py
  cms/djangoapps/course_creators/views.py
  common/djangoapps/student/auth.py
  common/djangoapps/student/roles.py
  common/djangoapps/student/tests/test_authz.py
  common/djangoapps/student/tests/test_roles.py
Labels: open-source-contribution, ready to merge

#28716 fix: remove pystache custom dependency
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: open-source-contribution, community manager review

#28221 docs: ADR for in context discussions [BD-38] [TNL-8512] [BB-4481]
  openedx/core/djangoapps/discussions/docs/decisions/0004-in-context-discussions-linking.rst
Labels: needs triage, blended

#28734 [BB-4414] Port request caching bugfix
  cms/static/js/factories/settings.js
Labels: open-source-contribution, awaiting prioritization, automerge

#28537 FAL-2367 [LX-2140] Skip broken links in blockstore
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
Labels: open-source-contribution, engineering review

#28452 docs: ADR that documents how MFEs can access in-context discussions [BD-38] [TNL-8396] [BB-4367]
  openedx/core/djangoapps/discussions/docs/decisions/0005-in-context-discussion-course-blocks.rst
Labels: needs triage, blended

#28788 Mark a message to be extracted using i18n_tools
  openedx/features/course_experience/templates/course_experience/course-dates-fragment.html
Labels: open-source-contribution, awaiting prioritization

#26633 Use registration field order when using a registration extension form
  openedx/core/djangoapps/user_authn/views/registration_form.py
  openedx/core/djangoapps/user_authn/views/tests/test_register.py
Labels: open-source-contribution, ready to merge

#28641 fix!: use bleach for sanitising HTML in discussions [BD-38] [TNL-8610] [BB-4741]
  lms/djangoapps/discussion/rest_api/render.py
  lms/djangoapps/discussion/rest_api/tests/test_render.py
Labels: engineering review, blended

#28440 [BD-13] Let ModuleSystem use UserService
  cms/djangoapps/contentstore/views/preview.py
  common/djangoapps/xblock_django/constants.py
  common/djangoapps/xblock_django/tests/test_user_service.py
  common/djangoapps/xblock_django/user_service.py
  common/lib/xmodule/xmodule/capa_module.py
  common/lib/xmodule/xmodule/html_module.py
  common/lib/xmodule/xmodule/lti_module.py
  common/lib/xmodule/xmodule/seq_module.py
  common/lib/xmodule/xmodule/tests/__init__.py
  common/lib/xmodule/xmodule/tests/helpers.py
  common/lib/xmodule/xmodule/tests/test_capa_module.py
  common/lib/xmodule/xmodule/tests/test_conditional.py
  common/lib/xmodule/xmodule/tests/test_html_module.py
  common/lib/xmodule/xmodule/tests/test_lti20_unit.py
  common/lib/xmodule/xmodule/tests/test_lti_unit.py
  common/lib/xmodule/xmodule/tests/test_vertical.py
  common/lib/xmodule/xmodule/x_module.py
  lms/djangoapps/courseware/module_render.py
  lms/djangoapps/courseware/tests/test_lti_integration.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/edxnotes/decorators.py
  lms/djangoapps/lms_xblock/runtime.py
  lms/djangoapps/lms_xblock/test/test_runtime.py
  lms/djangoapps/mobile_api/course_info/tests.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
Labels: needs triage, blended

#28502 [OSPR-5979] Port "LANGUAGE_CODE" site configuration option to Lilac
  openedx/core/djangoapps/dark_lang/middleware.py
  openedx/core/djangoapps/dark_lang/tests.py
Labels: open-source-contribution, engineering review, automerge

#28660 fix: log a single line warning in case of video_transcrip NotFound in…
  common/lib/xmodule/xmodule/video_module/video_handlers.py
Labels: open-source-contribution, engineering review, automerge

#28859 feat: Added support for enterprise id in course_grade_passed_first_time event
  lms/djangoapps/grades/events.py
  openedx/features/enterprise_support/context.py
  openedx/features/enterprise_support/tests/test_context.py
  openedx/features/enterprise_support/tests/test_utils.py
  openedx/features/enterprise_support/utils.py
Labels: open-source-contribution, awaiting prioritization

#28790 Remove event routing backends from edx-platform
  cms/envs/common.py
  lms/envs/common.py
  requirements/edx/base.in
Labels: open-source-contribution, engineering review

#28207 fix: handle invalid source library version on course import [BB-4436]
  cms/djangoapps/contentstore/views/tests/test_import_export.py
  common/lib/xmodule/xmodule/modulestore/xml_importer.py
Labels: open-source-contribution, awaiting prioritization

#28849 [SE-4860] Add CELERY_BROKER_TRANSPORT_OPTIONS
  cms/envs/production.py
  lms/envs/production.py
Labels: open-source-contribution, awaiting prioritization
