Repository openedx/edx-platform, pull requests merged in 2021-04, with the labels that each got.

#27198 [Koa Backport] Remove injected edxnotes from AboutBlock
  common/lib/xmodule/xmodule/html_module.py
Labels: awaiting prioritization, open-source-contribution

#25935 feat: associates user by email for oauth when tpa is required
  common/djangoapps/third_party_auth/pipeline.py
  common/djangoapps/third_party_auth/settings.py
  common/djangoapps/third_party_auth/tests/specs/base.py
  common/djangoapps/third_party_auth/tests/specs/test_azuread.py
  common/djangoapps/third_party_auth/tests/specs/test_google.py
  common/djangoapps/third_party_auth/tests/specs/test_linkedin.py
  common/djangoapps/third_party_auth/tests/specs/test_twitter.py
  common/djangoapps/third_party_auth/tests/test_utils.py
  common/djangoapps/third_party_auth/utils.py
Labels: cc-reviewer, engineering review, open-source-contribution

#24951 Added setting to manage from_email address
  lms/djangoapps/bulk_email/tasks.py
  lms/djangoapps/bulk_email/tests/test_email.py
  lms/djangoapps/bulk_email/toggles.py
Labels: cc-reviewer, open-source-contribution, product review

#27209 fix: Language preferences change enhancement.
  lms/static/js/views/fields.js
Labels: engineering review, open-source-contribution

#27185 [TSD] add annotations for CUSTOM_CERTIFICATE_TEMPLATES_ENABLED feature flag
  lms/djangoapps/certificates/tests/test_webview_views.py
  lms/envs/common.py
Labels: changes requested, open-source-contribution

#27213 Remove Sysadmin Dashboard
  cms/devstack.yml
  cms/envs/common.py
  import_shims/lms/dashboard/__init__.py
  import_shims/lms/dashboard/git_import.py
  import_shims/lms/dashboard/management/__init__.py
  import_shims/lms/dashboard/management/commands/__init__.py
  import_shims/lms/dashboard/management/commands/git_add_course.py
  import_shims/lms/dashboard/management/commands/tests/__init__.py
  import_shims/lms/dashboard/management/commands/tests/test_git_add_course.py
  import_shims/lms/dashboard/models.py
  import_shims/lms/dashboard/sysadmin.py
  import_shims/lms/dashboard/sysadmin_urls.py
  import_shims/lms/dashboard/tests/__init__.py
  import_shims/lms/dashboard/tests/test_sysadmin.py
  lms/devstack.yml
  lms/djangoapps/dashboard/__init__.py
  lms/djangoapps/dashboard/git_import.py
  lms/djangoapps/dashboard/management/__init__.py
  lms/djangoapps/dashboard/management/commands/__init__.py
  lms/djangoapps/dashboard/management/commands/git_add_course.py
  lms/djangoapps/dashboard/management/commands/tests/__init__.py
  lms/djangoapps/dashboard/management/commands/tests/test_git_add_course.py
  lms/djangoapps/dashboard/models.py
  lms/djangoapps/dashboard/sysadmin.py
  lms/djangoapps/dashboard/sysadmin_urls.py
  lms/djangoapps/dashboard/tests/__init__.py
  lms/djangoapps/dashboard/tests/test_sysadmin.py
  lms/djangoapps/instructor/views/instructor_dashboard.py
  lms/envs/common.py
  lms/envs/production.py
  lms/envs/test.py
  lms/templates/header/navbar-authenticated.html
  lms/templates/instructor/instructor_dashboard_2/course_info.html
  lms/templates/navigation/bootstrap/navbar-authenticated.html
  lms/templates/navigation/navbar-authenticated.html
  lms/templates/sysadmin_dashboard.html
  lms/templates/sysadmin_dashboard_gitlogs.html
  lms/urls.py
  themes/edx.org/lms/templates/header/navbar-authenticated.html
Labels: engineering review, open-source-contribution

#25800 [SE-3405] Django app to allow user retirement via API
  lms/djangoapps/bulk_user_retirement/__init__.py
  lms/djangoapps/bulk_user_retirement/tests/__init__.py
  lms/djangoapps/bulk_user_retirement/tests/test_views.py
  lms/djangoapps/bulk_user_retirement/urls.py
  lms/djangoapps/bulk_user_retirement/views.py
  lms/envs/common.py
  lms/envs/test.py
  lms/urls.py
  openedx/core/djangoapps/user_api/accounts/tests/test_retirement_views.py
  openedx/core/djangoapps/user_api/accounts/utils.py
  openedx/core/djangoapps/user_api/accounts/views.py
Labels: changes requested, open-source-contribution

#26860 [BB-3825] Fix: Hide new post indicator on thread open
  common/static/common/js/discussion/views/discussion_inline_view.js
  common/static/common/js/spec/discussion/view/discussion_inline_view_spec.js
Labels: changes requested, open-source-contribution

#27252 make course advanced setting invite_only configurable site-wide
  lms/djangoapps/courseware/access.py
  lms/djangoapps/courseware/tests/test_access.py
  lms/djangoapps/courseware/toggles.py
  lms/djangoapps/courseware/views/views.py
  lms/templates/courseware/course_about.html
Labels: changes requested, open-source-contribution

#27130 fix: Hide enterprise/login button if enterprise integration disabled.
  lms/static/js/spec/student_account/login_spec.js
  lms/static/js/student_account/views/AccessView.js
  lms/static/js/student_account/views/FormView.js
  lms/static/js/student_account/views/LoginView.js
  lms/templates/student_account/form_field.underscore
  openedx/core/djangoapps/user_authn/views/login_form.py
Labels: changes requested, open-source-contribution

#27325 fix: extra ")}" in 500 error page
  cms/templates/500.html
Labels: needs triage, open-source-contribution

#27339 fix: Import missing function in server_error template.
  cms/templates/error.html
Labels: needs triage, open-source-contribution

#27377 Use github version of py2neo instead of PyPI
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: needs triage, open-source-contribution
