Repository openedx/edx-platform, pull requests merged in 2022-08, with the labels that each got.

#30572 refactor: [BB-6077] allow setting celery backend in yml
  cms/envs/production.py
  lms/envs/production.py
Labels: open-source-contribution, automerge

#27925 fix: Bug showing hidden sections for learners of a public course fixed
  lms/djangoapps/course_api/blocks/api.py
  lms/djangoapps/course_api/blocks/tests/test_api.py
Labels: open-source-contribution

#30583 [BD-32] feat: Open edX Filters backport
  common/djangoapps/student/tests/test_filters.py
  common/djangoapps/student/views/dashboard.py
  lms/djangoapps/certificates/generation_handler.py
  lms/djangoapps/certificates/management/commands/cert_generation.py
  lms/djangoapps/certificates/signals.py
  lms/djangoapps/certificates/tests/test_filters.py
  lms/djangoapps/certificates/views/support.py
  lms/djangoapps/certificates/views/tests/__init__.py
  lms/djangoapps/certificates/views/tests/test_filters.py
  lms/djangoapps/certificates/views/webview.py
  lms/djangoapps/courseware/tests/test_filters.py
  lms/djangoapps/courseware/views/views.py
  lms/static/js/groups/views/cohort_editor.js
  lms/static/js/spec/groups/views/cohorts_spec.js
  openedx/core/djangoapps/course_groups/models.py
  openedx/core/djangoapps/course_groups/tests/test_filters.py
  openedx/core/djangoapps/course_groups/views.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: blended, automerge

#30840 fix: marks a text for i18n
  lms/templates/instructor/instructor_dashboard_2/certificate-allowlist.underscore
Labels: open-source-contribution

#30615 [BD-14] feat: implement V2 libraries usage for library content block
  xmodule/assets/library_content/public/js/library_content_edit_helpers.js
  xmodule/library_content_module.py
  xmodule/library_tools.py
  xmodule/modulestore/split_mongo/caching_descriptor_system.py
  xmodule/tests/test_library_content.py
  xmodule/tests/test_library_tools.py
Labels: blended

#30803 [BD-14] feat: Take the Library Content xblocks out the Advanced section to the top default level
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/views/tests/test_item.py
  cms/djangoapps/contentstore/views/tests/test_library.py
  cms/envs/common.py
  cms/static/images/large-library-icon.png
  cms/static/sass/assets/_graphics.scss
Labels: blended

#30630 Removed hardcoded social media and mobile store Images hosted on Sailthru
  cms/envs/common.py
  cms/envs/devstack-experimental.yml
  lms/djangoapps/branding/api.py
  lms/djangoapps/branding/tests/test_api.py
  lms/envs/common.py
  openedx/core/djangoapps/ace_common/template_context.py
  openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
Labels: open-source-contribution

#30773 Add openedx-filters hook to VerticalBlock before rendering of child blocks
  docs/guides/hooks/filters.rst
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
  xmodule/vertical_block.py
Labels: open-source-contribution

#30818 fix: change conditions for showing new and legacy discussion providers [BD-38]
  lms/djangoapps/discussion/toggles.py
  openedx/core/djangoapps/discussions/config/waffle.py
  openedx/core/djangoapps/discussions/handlers.py
  openedx/core/djangoapps/discussions/migrations/0013_auto_20220802_1154.py
  openedx/core/djangoapps/discussions/models.py
  openedx/core/djangoapps/discussions/tests/test_models.py
  openedx/core/djangoapps/discussions/tests/test_transformer.py
  openedx/core/djangoapps/discussions/tests/test_views.py
  openedx/core/djangoapps/discussions/views.py
Labels: blended
