Repository openedx/edx-platform, pull requests merged in 2022-02, with the labels that each got.

#29287 feat: Add a new user API for discussions [BD-38] [TNL-8795]
  lms/djangoapps/discussion/rest_api/api.py
  lms/djangoapps/discussion/rest_api/forms.py
  lms/djangoapps/discussion/rest_api/serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  lms/djangoapps/discussion/rest_api/tests/utils.py
  lms/djangoapps/discussion/rest_api/urls.py
  lms/djangoapps/discussion/rest_api/views.py
  openedx/core/djangoapps/django_comment_common/comment_client/course.py
Labels: needs triage, blended, isv-211129

#29785 feat: show share feedback button only for discussions MFE when URL is configured [BD-38]
  lms/djangoapps/discussion/views.py
  lms/envs/common.py
  lms/templates/discussion/_switch_experience_fragment.html
Labels: needs triage, blended

#29772 fix: course discovery dates localization after user logout
  lms/djangoapps/courseware/context_processor.py
  lms/djangoapps/courseware/tests/test_context_processor.py
Labels: open-source-contribution, ready to merge

#29817 fix: remove extra slash in courseblock api call
  common/static/common/js/components/BlockBrowser/data/api/client.js
Labels: open-source-contribution, waiting on author

#29773 fix: course discovery dates localization after user logout
  lms/djangoapps/bulk_user_retirement/tests/test_views.py
  lms/djangoapps/courseware/context_processor.py
  lms/djangoapps/courseware/tests/test_context_processor.py
Labels: open-source-contribution, awaiting prioritization, automerge

#29271 [SE-4473] Add completion progress bar to dashboard
  common/lib/xmodule/xmodule/js/src/sequence/display.js
  common/lib/xmodule/xmodule/seq_module.py
  lms/templates/courseware/courseware.html
  lms/templates/seq_module.html
Labels: open-source-contribution, awaiting prioritization

#29851 feat: add PREPEND_LOCALE_PATHS configuration setting
  cms/envs/common.py
  cms/envs/devstack-experimental.yml
  cms/envs/production.py
  lms/envs/common.py
  lms/envs/devstack-experimental.yml
  lms/envs/production.py
  lms/envs/test.py
Labels: open-source-contribution, awaiting prioritization

#29764 fix: account activation email site logo is not themed
  common/djangoapps/student/email_helpers.py
Labels: open-source-contribution, engineering review

#29863 fix: discussion configuration not saved to course for new provider [BD-38] [TNL-8622]
  openedx/core/djangoapps/discussions/serializers.py
Labels: needs triage, blended

#29843 fix: registration form validation message
  lms/static/js/student_account/views/RegisterView.js
Labels: open-source-contribution, awaiting prioritization, needs triage

#29864 feat: add provider info to the discussion configuration API [BD-38] [TNL-9333] [BB-5248]
  lms/djangoapps/discussion/rest_api/api.py
  lms/djangoapps/discussion/rest_api/serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
Labels: needs triage, blended

#29953 fix: old links edx-guide-for-students
  lms/static/js/fixtures/calculator.html
  lms/static/js/student_account/components/StudentAccountDeletion.jsx
  lms/static/js/student_account/components/StudentAccountDeletionModal.jsx
  lms/templates/calculator/toggle_calculator.html
  lms/templates/certificates/_edx-accomplishment-print-help.html
Labels: open-source-contribution, needs triage
