Repository openedx/edx-platform, pull requests merged in 2022-03, with the labels that each got.

#30006 fix: Use legacy view for legacy URLs [BD-38] [TNL-9651]
  lms/djangoapps/discussion/tests/test_views.py
  lms/djangoapps/discussion/views.py
Labels: needs triage, blended

#29944 perf: use CourseOverview instead of modulestore when getting course summaries
  cms/djangoapps/contentstore/tests/test_course_listing.py
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/views/tests/test_course_index.py
Labels: open-source-contribution, engineering review

#29955 [BD-38] feat: add flag to toggle learners tab in the discussions MFE [TNL-9481][BB-5421]
  lms/djangoapps/discussion/rest_api/api.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  lms/djangoapps/discussion/toggles.py
Labels: needs triage, blended

#29928 docs: ADR for adding context to discussion topic links [BD-38]
  openedx/core/djangoapps/discussions/docs/decisions/0007-topic-context-for-deletion.rst
Labels: needs triage, blended

#29046 [SE-4860] Upgrade Celery to v5.2.1
  requirements/constraints.txt
  requirements/edx-sandbox/py38.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/github.in
  requirements/edx/pip-tools.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, engineering review

#29184 Cutover to read course index data from MySQL
  cms/djangoapps/contentstore/tests/test_course_listing.py
  cms/djangoapps/contentstore/views/tests/test_course_index.py
  cms/djangoapps/contentstore/views/tests/test_item.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py
  common/lib/xmodule/xmodule/modulestore/tests/test_libraries.py
  common/lib/xmodule/xmodule/modulestore/tests/test_mixed_modulestore.py
  common/lib/xmodule/xmodule/modulestore/tests/test_mongo_call_count.py
  lms/djangoapps/ccx/tests/test_field_override_performance.py
  lms/djangoapps/ccx/tests/test_models.py
  lms/djangoapps/course_api/blocks/transformers/tests/test_milestones.py
  lms/djangoapps/courseware/tests/test_course_info.py
  lms/djangoapps/courseware/tests/test_courses.py
  lms/djangoapps/courseware/tests/test_discussion_xblock.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/testutils.py
  lms/djangoapps/discussion/django_comment_client/base/tests.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  lms/djangoapps/grades/tests/test_course_grade_factory.py
  lms/djangoapps/grades/tests/test_tasks.py
  lms/djangoapps/grades/tests/test_transformer.py
  lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
  lms/djangoapps/instructor_task/tests/test_tasks_helper.py
  lms/djangoapps/teams/tests/test_serializers.py
  openedx/core/djangoapps/bookmarks/tests/test_api.py
  openedx/core/djangoapps/bookmarks/tests/test_models.py
  openedx/core/djangoapps/bookmarks/tests/test_services.py
  openedx/core/djangoapps/bookmarks/tests/test_tasks.py
  openedx/core/djangoapps/credit/tests/test_api.py
  openedx/core/djangoapps/enrollments/tests/test_views.py
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/tests/views/test_course_updates.py
  openedx/tests/completion_integration/test_models.py
Labels: open-source-contribution, waiting on author

#29957 fix: rewrite calcualtor tips to reflect the supported features
  lms/templates/calculator/toggle_calculator.html
Labels: open-source-contribution, awaiting prioritization

#29403 fix: Inconsistent PipelineCachedStorage usages
  cms/envs/devstack_optimized.py
  cms/envs/test_static_optimized.py
  lms/envs/devstack_optimized.py
  lms/envs/test_static_optimized.py
  openedx/core/lib/django_require/staticstorage.py
Labels: open-source-contribution, awaiting prioritization

#29834 fix: catch and log the CourseOverview.DoesNotExist instead of raising
  openedx/core/djangoapps/credit/services.py
  openedx/core/djangoapps/credit/tests/test_services.py
Labels: open-source-contribution, waiting on author

#29609 [BD-38] [TNL-8842] [BB-5251] Add API support for reason codes
  lms/djangoapps/discussion/rest_api/api.py
  lms/djangoapps/discussion/rest_api/permissions.py
  lms/djangoapps/discussion/rest_api/serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_permissions.py
  lms/djangoapps/discussion/rest_api/tests/test_serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  lms/djangoapps/discussion/rest_api/tests/utils.py
  lms/djangoapps/discussion/rest_api/views.py
  openedx/core/djangoapps/django_comment_common/comment_client/comment.py
  openedx/core/djangoapps/django_comment_common/comment_client/thread.py
Labels: needs triage, blended

#29948 [BD-32] feat: add unenrollment Open edX Filter
  common/djangoapps/student/models.py
  common/djangoapps/student/tests/test_filters.py
  common/djangoapps/student/views/management.py
  lms/static/js/learner_dashboard/views/unenroll_view.js
Labels: needs triage, blended

#30015 feat: Add API for retrieving moderation reason codes from the LMS settings [BD-38] [TNL-9479] [BB-5419]
  lms/djangoapps/discussion/rest_api/api.py
  lms/djangoapps/discussion/rest_api/serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  lms/djangoapps/discussion/rest_api/tests/utils.py
  lms/djangoapps/discussion/rest_api/views.py
  lms/djangoapps/discussion/toggles.py
  lms/envs/common.py
Labels: needs triage, blended

#29958 fix: icon on course outline was not showing correctly
  openedx/features/course_experience/utils.py
Labels: open-source-contribution, waiting on author, engineering review

#29833 fix: problem_grade_report task parent dir being discarded.
  lms/djangoapps/instructor_task/tasks_helper/grades.py
Labels: open-source-contribution, waiting on author, engineering review

#28268 feat: allow marking Library Content Block as complete on view [BB-4503]
  cms/envs/common.py
  common/lib/xmodule/xmodule/library_content_module.py
  lms/envs/common.py
  openedx/core/__pycache__/apidocs.cpython-38.pyc.139860693926064
  openedx/tests/completion_integration/test_services.py
Labels: open-source-contribution, engineering review

#29080 fix: make bulk_email send email task handles a retryable exception
  lms/djangoapps/bulk_email/tasks.py
  lms/djangoapps/bulk_email/tests/test_tasks.py
Labels: open-source-contribution, awaiting prioritization
