Repository openedx/edx-platform, pull requests merged in 2022-12, with the labels that each got.

#31390 feat: pass event_metadata to event bus
  cms/djangoapps/contentstore/signals/handlers.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: event-bus

#31399 fix: Fix retiring user auth models on disable event (nutmeg backport)
  lms/djangoapps/support/tests/test_views.py
  lms/djangoapps/support/views/manage_user.py
Labels: open-source-contribution

#31365 fix: update problem templates according newer python versions
  xmodule/templates/problem/circuitschematic.yaml
  xmodule/templates/problem/problem_with_hint_in_latex.yaml
Labels: open-source-contribution, core committer

#30072 reafactor: simplify XModule serialization/deserialization layer [BD-13]
  cms/djangoapps/contentstore/course_info_model.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  openedx/core/djangoapps/olx_rest_api/adapters.py
  openedx/core/djangoapps/xblock/runtime/blockstore_runtime.py
  openedx/core/djangoapps/xblock/runtime/serializer.py
  openedx/core/djangoapps/xblock/runtime/shims.py
  xmodule/course_module.py
  xmodule/discussion_block.py
  xmodule/raw_module.py
  xmodule/template_module.py
  xmodule/tests/test_poll.py
  xmodule/tests/test_video.py
  xmodule/tests/test_xml_module.py
  xmodule/vertical_block.py
  xmodule/video_module/video_module.py
  xmodule/x_module.py
  xmodule/xml_module.py
Labels: blended

#31044 fix: added keyword substitution support in edx_ace based bulk course emails
  lms/djangoapps/bulk_email/messages.py
  lms/djangoapps/bulk_email/tests/test_email.py
  lms/envs/common.py
  lms/templates/bulk_email/edx_ace/bulkemail/email/body.html
  lms/templates/bulk_email/edx_ace/bulkemail/email/body.txt
  lms/templates/instructor/instructor_dashboard_2/send_email.html
Labels: open-source-contribution, core committer

#31309 feat: force enrollment after enrollment end date
  openedx/core/djangoapps/enrollments/api.py
  openedx/core/djangoapps/enrollments/data.py
  openedx/core/djangoapps/enrollments/tests/fake_data_api.py
  openedx/core/djangoapps/enrollments/tests/test_views.py
  openedx/core/djangoapps/enrollments/views.py
Labels: open-source-contribution

#31422 [OldMongo FC-0004] Tests for removing support for children in Old Mongo - part 1
  cms/djangoapps/contentstore/tests/test_course_settings.py
  cms/djangoapps/contentstore/tests/test_utils.py
  cms/djangoapps/contentstore/views/tests/test_group_configurations.py
  cms/djangoapps/contentstore/views/tests/test_preview.py
  lms/djangoapps/discussion/tests/test_views.py
  lms/djangoapps/gating/tests/test_integration.py
  lms/djangoapps/instructor/tests/test_tools.py
  lms/djangoapps/program_enrollments/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/course_date_signals/tests.py
  openedx/features/content_type_gating/tests/test_access.py
  xmodule/modulestore/tests/utils.py
Labels: open-source-contribution, FC
