Repository openedx/edx-platform, pull requests merged in 2022-04, with the labels that each got.

#30164 feat: handle navigation and resize events from discussions MFE [BD-38] [TNL-9585]
  lms/djangoapps/discussion/templates/discussion/discussion_mfe_embed.html
Labels: needs triage, blended

#29792 Fix certificate generation without persistent grades
  lms/djangoapps/certificates/generation_handler.py
  lms/djangoapps/grades/course_grade_factory.py
  lms/djangoapps/grades/tests/test_course_grade_factory.py
Labels: open-source-contribution, awaiting prioritization

#30232 build: kickoff the Nutmeg release
  .github/pull_request_template.md
  .tx/config
  openedx/core/release.py
Labels: open-source-contribution, waiting on author, core committer

#30233 build: nudge devs to backport changes to nutmeg
  .github/pull_request_template.md
Labels: open-source-contribution, needs triage

#30109 feat: use native learning MFE tab for discussions [BD-38] [TNL-9743]
  lms/djangoapps/courseware/tests/test_tabs.py
  lms/djangoapps/discussion/plugins.py
Labels: needs triage, blended

#29973 [BD-38][TNL-9482] Add user update stats API
  lms/djangoapps/discussion/management/commands/update_user_discussion_stats.py
  openedx/core/djangoapps/django_comment_common/comment_client/course.py
Labels: community manager review, blended

#30230 fix!: supply the editor and closing user as separate params to cs_comments_service [BD-38] [TNL-9809]
  lms/djangoapps/discussion/rest_api/serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  openedx/core/djangoapps/django_comment_common/comment_client/comment.py
  openedx/core/djangoapps/django_comment_common/comment_client/thread.py
Labels: needs triage, blended

#30131 [BB-5968][BD-13] feat: deprecate filestore
  cms/djangoapps/contentstore/views/preview.py
  common/lib/capa/capa/capa_problem.py
  common/lib/capa/capa/responsetypes.py
  common/lib/capa/capa/tests/helpers.py
  common/lib/capa/capa/tests/test_html_render.py
  common/lib/xmodule/xmodule/capa_module.py
  common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py
  common/lib/xmodule/xmodule/tests/__init__.py
  common/lib/xmodule/xmodule/x_module.py
  lms/djangoapps/courseware/module_render.py
  openedx/core/djangoapps/xblock/runtime/shims.py
  openedx/core/lib/xblock_utils/__init__.py
Labels: needs triage, blended

#29739 refactor: consider celery imports from common settings plus env tokens
  lms/envs/common.py
  lms/envs/production.py
Labels: open-source-contribution, changes requested

#29779 [BD-14] Install the blockstore app into edx-platform, behind a waffle switch
  cms/envs/common.py
  cms/envs/test.py
  cms/urls.py
  common/lib/xmodule/xmodule/contentstore/content.py
  common/test/problem.html
  common/test/problem_ajax.html
  common/test/video.html
  lms/envs/common.py
  lms/envs/devstack.py
  lms/envs/test.py
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/library_bundle.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/tests/test_libraries_index.py
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/content_libraries/tests/test_static_assets.py
  openedx/core/djangoapps/content_libraries/tests/test_views_lti.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
  openedx/core/djangolib/tests/test_blockstore_cache.py
  openedx/core/lib/blockstore_api/__init__.py
  openedx/core/lib/blockstore_api/config/__init__.py
  openedx/core/lib/blockstore_api/config/waffle.py
  openedx/core/lib/blockstore_api/db_routers.py
  openedx/core/lib/blockstore_api/exceptions.py
  openedx/core/lib/blockstore_api/methods.py
  openedx/core/lib/blockstore_api/models.py
  openedx/core/lib/blockstore_api/tests/test_blockstore_api.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: needs triage, blended

#29927 [BD-13] [BB-5519] refactor: deletes XModuleDescriptorToXBlockMixin
  common/lib/xmodule/xmodule/annotatable_module.py
  common/lib/xmodule/xmodule/capa_module.py
  common/lib/xmodule/xmodule/conditional_module.py
  common/lib/xmodule/xmodule/error_module.py
  common/lib/xmodule/xmodule/hidden_module.py
  common/lib/xmodule/xmodule/html_module.py
  common/lib/xmodule/xmodule/library_content_module.py
  common/lib/xmodule/xmodule/lti_module.py
  common/lib/xmodule/xmodule/modulestore/mongo/base.py
  common/lib/xmodule/xmodule/poll_module.py
  common/lib/xmodule/xmodule/randomize_module.py
  common/lib/xmodule/xmodule/seq_module.py
  common/lib/xmodule/xmodule/split_test_module.py
  common/lib/xmodule/xmodule/template_module.py
  common/lib/xmodule/xmodule/video_module/video_module.py
  common/lib/xmodule/xmodule/word_cloud_module.py
  common/lib/xmodule/xmodule/x_module.py
  common/lib/xmodule/xmodule/xml_module.py
  common/test/data/conditional/course.xml
  common/test/data/conditional_and_poll/course/2013_Spring.xml
  common/test/data/course_ignore/course.xml
  common/test/data/manual-testing-complete/problem/45c317cb93d447f293ce982a2eccd77d.xml
  common/test/data/manual-testing-complete/problem/d0bdd7c3487d4f94b7bcd207f110c20a.xml
  common/test/data/simple/course.xml
  common/test/data/simple_with_draft/course.xml
  common/test/data/split_test_module/course.xml
  common/test/data/test_import_course/chapter/vertical_container.xml
  common/test/data/test_import_course/sequential/vertical_sequential.xml
  common/test/data/test_import_course_2/chapter/vertical_container.xml
  common/test/data/test_import_course_2/sequential/vertical_sequential.xml
  common/test/data/test_unicode/sequential/vertical_sequential.xml
  common/test/data/toy/chapter/vertical_container.xml
  common/test/data/toy/sequential/vertical_sequential.xml
  common/test/data/word_cloud/sequential/Problem_Demos.xml
  common/test/data/xml_dag/course/2012_Fall.xml
  common/test/data/xml_dag/vertical/vertical_test.xml
  openedx/core/lib/xblock_builtin/xblock_discussion/tests.py
  openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion/__init__.py
Labels: needs triage, blended

#30240 FC-0001: enterprise dependencies for EdxRestAPIClient replacement
  cms/envs/common.py
  cms/envs/devstack.py
  lms/envs/common.py
  lms/envs/devstack.py
  openedx/core/djangoapps/commerce/utils.py
  openedx/core/lib/edx_api_utils.py
Labels: open-source-contribution, needs triage

#29326 [BB-4951] Implement feature flag to disable students un-enrollment
  cms/envs/common.py
  common/djangoapps/student/tests/test_enrollment.py
  common/djangoapps/student/views/dashboard.py
  common/djangoapps/student/views/management.py
  lms/envs/common.py
  lms/templates/dashboard.html
  lms/templates/dashboard/_dashboard_course_listing.html
Labels: open-source-contribution, waiting on author

#30302 FC-0001: remove deprecated save option for anonymous_id_for_user
  common/djangoapps/student/models.py
Labels: open-source-contribution, needs triage

#29959 Some tests are skipped due to duplicate names fix
  scripts/xsslint/tests/test_utils.py
Labels: open-source-contribution, awaiting prioritization

#30310 fix: Disallow endorsements for replies to comments [BD-38] [INF-160]
  lms/djangoapps/discussion/rest_api/permissions.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_permissions.py
Labels: needs triage, blended

#29687 fix: relax load in instructor dashboard page.
  lms/djangoapps/instructor/views/instructor_dashboard.py
Labels: open-source-contribution, awaiting prioritization
