Repository openedx/edx-platform, pull requests merged in 2022-05, with the labels that each got.

#30334 docs: fix release notes URL
  CHANGELOG.rst
Labels: open-source-contribution, awaiting prioritization

#30330 FC-0001: Remove legacy waffles
  cms/djangoapps/contentstore/config/waffle.py
  cms/djangoapps/contentstore/tests/test_contentstore.py
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/views/public.py
  cms/djangoapps/contentstore/views/tests/test_videos.py
  cms/djangoapps/contentstore/views/videos.py
  cms/djangoapps/models/settings/waffle.py
  cms/templates/widgets/footer.html
  common/djangoapps/student/views/dashboard.py
  common/lib/xmodule/xmodule/seq_module.py
  common/lib/xmodule/xmodule/video_module/video_module.py
  lms/djangoapps/course_api/__init__.py
  lms/djangoapps/course_api/blocks/toggles.py
  lms/djangoapps/course_home_api/toggles.py
  lms/djangoapps/courseware/tests/test_about.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/toggles.py
  lms/djangoapps/courseware/views/index.py
  lms/djangoapps/courseware/views/views.py
  lms/djangoapps/discussion/toggles.py
  lms/djangoapps/experiments/flags.py
  lms/djangoapps/experiments/tests/test_flags.py
  lms/djangoapps/experiments/views_custom.py
  lms/djangoapps/grades/api.py
  lms/djangoapps/grades/config/__init__.py
  lms/djangoapps/grades/config/waffle.py
  lms/djangoapps/grades/grade_utils.py
  lms/djangoapps/grades/migrations/0018_add_waffle_flag_defaults.py
  lms/djangoapps/grades/rest_api/v1/tests/test_gradebook_views.py
  lms/djangoapps/grades/tasks.py
  lms/djangoapps/grades/tests/test_course_grade.py
  lms/djangoapps/grades/tests/test_course_grade_factory.py
  lms/djangoapps/grades/tests/test_services.py
  lms/djangoapps/grades/tests/test_tasks.py
  lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
  lms/djangoapps/instructor/toggles.py
  lms/djangoapps/instructor_task/config/waffle.py
  lms/djangoapps/ora_staff_grader/views.py
  lms/djangoapps/teams/toggles.py
  lms/djangoapps/verify_student/toggles.py
  openedx/core/djangoapps/course_apps/toggles.py
  openedx/core/djangoapps/course_live/config/waffle.py
  openedx/core/djangoapps/discussions/config/waffle.py
  openedx/core/djangoapps/programs/__init__.py
  openedx/core/djangoapps/schedules/config.py
  openedx/core/djangoapps/user_api/accounts/toggles.py
  openedx/core/djangoapps/user_authn/config/waffle.py
  openedx/core/djangoapps/user_authn/views/register.py
  openedx/core/djangoapps/video_pipeline/config/waffle.py
  openedx/core/djangoapps/waffle_utils/__future__.py
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/core/djangoapps/waffle_utils/tests/test_init.py
  openedx/features/course_experience/__init__.py
  openedx/features/course_experience/waffle.py
  openedx/features/discounts/applicability.py
  openedx/features/effort_estimation/toggles.py
  openedx/features/enterprise_support/utils.py
  openedx/features/learner_profile/toggles.py
Labels: open-source-contribution, awaiting prioritization

#29949 [BD-32] feat: add certificate creation Open edX Filter
  lms/djangoapps/certificates/generation_handler.py
  lms/djangoapps/certificates/management/commands/cert_generation.py
  lms/djangoapps/certificates/signals.py
  lms/djangoapps/certificates/tests/test_filters.py
  lms/djangoapps/certificates/views/support.py
  lms/djangoapps/courseware/views/views.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: needs triage, blended

#30301 FC-0001: Remove old EdxRestAPIClient usage across the platform
  common/djangoapps/course_modes/helpers.py
  common/djangoapps/student/models.py
  common/djangoapps/student/tests/test_refunds.py
  lms/djangoapps/commerce/api/v0/views.py
  lms/djangoapps/commerce/api/v1/views.py
  lms/djangoapps/commerce/management/commands/create_orders_for_old_enterprise_course_enrollment.py
  lms/djangoapps/commerce/tests/__init__.py
  lms/djangoapps/commerce/utils.py
  lms/djangoapps/verify_student/views.py
  lms/envs/common.py
  lms/envs/production.py
  openedx/core/djangoapps/api_admin/views.py
  openedx/core/djangoapps/catalog/management/commands/cache_programs.py
  openedx/core/djangoapps/catalog/tests/test_utils.py
  openedx/core/djangoapps/catalog/utils.py
  openedx/core/djangoapps/commerce/utils.py
  openedx/core/djangoapps/credentials/tasks/v1/tasks.py
  openedx/core/djangoapps/credentials/tests/test_tasks.py
  openedx/core/djangoapps/credentials/tests/test_utils.py
  openedx/core/djangoapps/credentials/utils.py
  openedx/core/djangoapps/credit/email_utils.py
  openedx/core/djangoapps/credit/tests/test_api.py
  openedx/core/djangoapps/programs/tasks.py
  openedx/core/djangoapps/programs/tests/test_tasks.py
  openedx/core/djangoapps/programs/utils.py
  openedx/core/djangoapps/user_api/accounts/settings_views.py
  openedx/core/djangoapps/user_api/accounts/views.py
  openedx/core/djangoapps/user_api/management/commands/sync_hubspot_contacts.py
  openedx/core/djangoapps/video_pipeline/api.py
  openedx/core/djangoapps/video_pipeline/tests/test_api.py
  openedx/core/lib/edx_api_utils.py
  openedx/core/lib/tests/test_edx_api_utils.py
  openedx/features/enterprise_support/api.py
  openedx/features/enterprise_support/signals.py
  openedx/features/enterprise_support/tests/test_api.py
  openedx/features/enterprise_support/tests/test_signals.py
Labels: open-source-contribution, engineering review

#29994 [BD-32] feat: add filter before dashboard rendering process starts
  common/djangoapps/student/tests/test_filters.py
  common/djangoapps/student/views/dashboard.py
Labels: needs triage, blended

#30262 [BD-13][BB-5615] refactor: Delete XModule classes
  cms/djangoapps/contentstore/views/preview.py
  common/lib/xmodule/xmodule/mako_module.py
  common/lib/xmodule/xmodule/modulestore/xml_importer.py
  common/lib/xmodule/xmodule/seq_module.py
  common/lib/xmodule/xmodule/static_content.py
  common/lib/xmodule/xmodule/studio_editable.py
  common/lib/xmodule/xmodule/tests/__init__.py
  common/lib/xmodule/xmodule/tests/test_content.py
  common/lib/xmodule/xmodule/tests/test_error_module.py
  common/lib/xmodule/xmodule/tests/test_progress.py
  common/lib/xmodule/xmodule/tests/test_xblock_wrappers.py
  common/lib/xmodule/xmodule/x_module.py
  common/lib/xmodule/xmodule/xml_module.py
  lms/djangoapps/courseware/access.py
  lms/djangoapps/courseware/rules.py
  lms/djangoapps/courseware/tests/test_module_render.py
  lms/djangoapps/lms_xblock/runtime.py
  openedx/core/lib/xblock_utils/__init__.py
Labels: needs triage, blended

#29976 [BD-32] feat: add filter before certificate rendering process starts
  lms/djangoapps/certificates/views/tests/__init__.py
  lms/djangoapps/certificates/views/tests/test_filters.py
  lms/djangoapps/certificates/views/webview.py
Labels: needs triage, blended

#30351 FC-0001: upgrade original CourseWaffleFlag
  cms/djangoapps/contentstore/config/waffle.py
  cms/djangoapps/contentstore/views/videos.py
  cms/djangoapps/models/settings/waffle.py
  lms/djangoapps/course_home_api/toggles.py
  lms/djangoapps/courseware/toggles.py
  lms/djangoapps/discussion/toggles.py
  lms/djangoapps/experiments/flags.py
  lms/djangoapps/experiments/tests/test_flags.py
  lms/djangoapps/grades/config/waffle.py
  lms/djangoapps/instructor_task/config/waffle.py
  lms/djangoapps/ora_staff_grader/views.py
  lms/djangoapps/teams/toggles.py
  openedx/core/djangoapps/course_apps/toggles.py
  openedx/core/djangoapps/course_live/config/waffle.py
  openedx/core/djangoapps/discussions/config/waffle.py
  openedx/core/djangoapps/video_pipeline/config/waffle.py
  openedx/core/djangoapps/waffle_utils/__future__.py
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/core/djangoapps/waffle_utils/tests/test_init.py
  openedx/features/course_experience/__init__.py
  openedx/features/effort_estimation/toggles.py
  requirements/edx/base.in
Labels: open-source-contribution, engineering review

#30370 FC-0001: update lti-consumer block version
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, needs triage

#29996 [BD-32] feat: add filter before course about rendering process starts
  lms/djangoapps/courseware/tests/test_filters.py
  lms/djangoapps/courseware/views/views.py
Labels: needs triage, blended

#30367 FC-0001: delete now unused FutureCourseWaffleFlag
  cms/djangoapps/contentstore/tests/test_contentstore.py
  cms/djangoapps/contentstore/views/tests/test_videos.py
  lms/djangoapps/commerce/tests/test_utils.py
  lms/djangoapps/course_api/tests/test_views.py
  lms/djangoapps/courseware/tests/test_about.py
  lms/djangoapps/courseware/tests/test_date_summary.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/teams/toggles.py
  lms/djangoapps/verify_student/tests/test_views.py
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
  openedx/core/djangoapps/waffle_utils/__future__.py
  openedx/core/djangoapps/waffle_utils/tests/test_init.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, engineering review, FC, arch-bom

#29964 [BD-32] feat: add cohort change Open edX Filter
  openedx/core/djangoapps/course_groups/models.py
  openedx/core/djangoapps/course_groups/tests/test_filters.py
Labels: blended, cc-reviewer

#30338 fix: bump pinned pyfilesystem2 version
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, awaiting prioritization

#30348 [BACKPORT] feat: Implement feature flag to disable students un-enrollment (#29326)
  cms/envs/common.py
  common/djangoapps/student/tests/test_enrollment.py
  common/djangoapps/student/views/dashboard.py
  common/djangoapps/student/views/management.py
  lms/envs/common.py
  lms/templates/dashboard.html
  lms/templates/dashboard/_dashboard_course_listing.html
Labels: open-source-contribution, open edx community review

#30458 FC-0001: rename `toggle_warnings` to `toggle_warning`
  cms/djangoapps/contentstore/config/waffle.py
  cms/djangoapps/contentstore/toggles.py
  cms/envs/common.py
  common/djangoapps/course_modes/views.py
  common/djangoapps/student/admin.py
  doc.rst.j2
  lms/djangoapps/course_api/blocks/toggles.py
  lms/djangoapps/courseware/toggles.py
  lms/djangoapps/experiments/utils.py
  lms/djangoapps/experiments/views_custom.py
  lms/djangoapps/grades/config/waffle.py
  lms/djangoapps/instructor/toggles.py
  lms/djangoapps/learner_dashboard/config/waffle.py
  lms/djangoapps/teams/toggles.py
  lms/djangoapps/teams/waffle.py
  lms/djangoapps/verify_student/toggles.py
  lms/envs/common.py
  openedx/core/djangoapps/content/block_structure/config/__init__.py
  openedx/core/djangoapps/cookie_metadata/middleware.py
  openedx/core/djangoapps/course_apps/toggles.py
  openedx/core/djangoapps/course_live/config/waffle.py
  openedx/core/djangoapps/credentials/helpers.py
  openedx/core/djangoapps/discussions/config/waffle.py
  openedx/core/djangoapps/safe_sessions/middleware.py
  openedx/core/djangoapps/user_api/accounts/toggles.py
  openedx/core/djangoapps/user_authn/config/waffle.py
  openedx/core/djangoapps/user_authn/toggles.py
  openedx/core/djangoapps/user_authn/views/register.py
  openedx/core/djangoapps/video_pipeline/config/waffle.py
  openedx/core/lib/blockstore_api/config/waffle.py
  openedx/core/lib/request_utils.py
  openedx/features/announcements/settings/common.py
  openedx/features/course_experience/__init__.py
  openedx/features/discounts/applicability.py
  openedx/features/learner_profile/toggles.py
Labels: open-source-contribution, needs triage

#30492 fix: revert discussion tab redirection [BD-38]
  lms/djangoapps/courseware/tests/test_tabs.py
  lms/djangoapps/discussion/plugins.py
Labels: needs triage, blended

#30389 fix: share urls in course about page
  lms/templates/courseware/course_about_sidebar_header.html
Labels: open-source-contribution, needs triage
