Repository openedx/edx-platform, pull requests merged in 2022-06, with the labels that each got.

#30520 fix: Run course discussion settings update task when settings change [BD-38]
  openedx/core/djangoapps/discussions/serializers.py
Labels: needs triage, blended

#30365 fix: Platform name calculated every time UNVERIFIED_CERT_DATA is requested
  lms/djangoapps/courseware/views/views.py
Labels: open-source-contribution, waiting on author, engage

#29728 feat: add reset option to the Randomized Content Block
  common/lib/xmodule/xmodule/assets/library_content/public/js/library_content_reset.js
  common/lib/xmodule/xmodule/library_content_module.py
  common/lib/xmodule/xmodule/tests/test_library_content.py
  lms/static/sass/course/courseware/_courseware.scss
  lms/templates/vert_module.html
Labels: open-source-contribution, product review

#30309 fix: Upgrade npm package @edx/studio-frontend to ^1.19.1 to fix missing assets
  package-lock.json
  package.json
Labels: open-source-contribution, community manager review

#29689 fix: Improve studio /settings/details page.
  cms/djangoapps/contentstore/tests/test_course_listing.py
  cms/djangoapps/contentstore/views/course.py
Labels: open-source-contribution, awaiting prioritization

#30447 [BD-13][BB-6209] refactor: deprecate node_path attribute of ModuleSystem
  common/lib/capa/capa/capa_problem.py
  common/lib/capa/capa/tests/helpers.py
  common/lib/xmodule/xmodule/capa_module.py
  common/lib/xmodule/xmodule/tests/__init__.py
  common/lib/xmodule/xmodule/x_module.py
  lms/djangoapps/courseware/module_render.py
  lms/envs/common.py
  openedx/core/djangoapps/xblock/runtime/shims.py
  tox.ini
Labels: needs triage, blended

#30437 fix: Fix jasmine-jquery package format to avoid checking out over ssh
  package-lock.json
  package.json
Labels: open-source-contribution, needs triage

#30518 fix: share urls in course about page (#30389)
  lms/templates/courseware/course_about_sidebar_header.html
Labels: open-source-contribution, needs triage

#30299 FC-0001: Remove legacy course info page & related code
  .github/workflows/pylint-checks.yml
  .github/workflows/unit-test-shards.json
  cms/djangoapps/contentstore/management/commands/edit_course_tabs.py
  cms/djangoapps/contentstore/management/commands/tests/test_backfill_course_tabs.py
  cms/djangoapps/contentstore/tests/test_import.py
  cms/djangoapps/contentstore/views/tabs.py
  cms/djangoapps/contentstore/views/tests/test_tabs.py
  cms/envs/common.py
  common/djangoapps/util/views.py
  common/lib/xmodule/xmodule/course_module.py
  common/lib/xmodule/xmodule/modulestore/tests/test_split_modulestore.py
  common/lib/xmodule/xmodule/tabs.py
  common/lib/xmodule/xmodule/tests/test_tabs.py
  common/test/data/scoreable/policies/course/policy.json
  common/test/test-theme/lms/templates/courseware/courses.html
  common/test/test-theme/lms/templates/courseware/info.html
  common/test/test-theme/lms/templates/courseware/progress.html
  lms/djangoapps/courseware/tabs.py
  lms/djangoapps/courseware/tests/test_course_info.py
  lms/djangoapps/courseware/tests/test_date_summary.py
  lms/djangoapps/courseware/tests/test_masquerade.py
  lms/djangoapps/courseware/tests/test_tabs.py
  lms/djangoapps/courseware/tests/test_views.py
  lms/djangoapps/courseware/views/views.py
  lms/envs/common.py
  lms/static/sass/course/_info.scss
  lms/templates/courseware/info.html
  lms/urls.py
  openedx/core/djangoapps/content/course_overviews/tests/test_course_overviews.py
  openedx/core/djangoapps/schedules/docs/README.rst
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
  openedx/core/djangoapps/self_paced/__init__.py
  openedx/core/djangoapps/self_paced/admin.py
  openedx/core/djangoapps/self_paced/migrations/0001_initial.py
  openedx/core/djangoapps/self_paced/migrations/__init__.py
  openedx/core/djangoapps/self_paced/models.py
  openedx/core/djangoapps/theming/tests/test_theme_style_overrides.py
  openedx/features/course_experience/__init__.py
  openedx/features/course_experience/plugins.py
  openedx/features/enterprise_support/tests/test_api.py
  setup.py
Labels: open-source-contribution, awaiting prioritization, FC, arch-bom

#30431 [BD-32] feat: integrate cohort assignment filter definition
  lms/static/js/groups/views/cohort_editor.js
  lms/static/js/spec/groups/views/cohorts_spec.js
  openedx/core/djangoapps/course_groups/models.py
  openedx/core/djangoapps/course_groups/tests/test_filters.py
  openedx/core/djangoapps/course_groups/views.py
Labels: needs triage, blended

#30456 [BD-14] fix: call blockstore APIs in atomic transactions.
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: blended

#30244 fix: get CELERY_RESULT_BACKEND from ENV_TOKENS
  cms/envs/production.py
  lms/envs/production.py
Labels: open-source-contribution, waiting on author

#30246 fix: get CELERY_RESULT_BACKEND from ENV_TOKENS
  cms/envs/production.py
  lms/envs/production.py
Labels: open-source-contribution, waiting on author

#29866 [BD-32] docs: Open edX Filters & Events guides update
  docs/guides/extension_points.rst
  docs/guides/hooks/events.rst
  docs/guides/hooks/filters.rst
  docs/guides/hooks/index.rst
Labels: blended

#30570 fix: update problem with hint template for python newer versions
  common/lib/xmodule/xmodule/templates/problem/problem_with_hint.yaml
Labels: open-source-contribution, automerge

#30550 fix: if pages and resources view is disabled, show all pages in studio [BB-6338]
  cms/djangoapps/contentstore/rest_api/v0/tests/test_tabs.py
  cms/djangoapps/contentstore/rest_api/v0/views/tabs.py
  cms/djangoapps/contentstore/views/tabs.py
  cms/djangoapps/contentstore/views/tests/test_tabs.py
  cms/static/images/preview-lms-staticpage.png
  cms/templates/edit-tabs.html
  xmodule/tabs.py
Labels: open-source-contribution

#30535 Clarify a potentially confusing deprecation message [MNG-3057]
  openedx/core/djangoapps/xblock/runtime/shims.py
Labels: open-source-contribution, needs triage

#30373 [BACKPORT] fixup! feat: options for excluding courses from search (#28518)
  cms/djangoapps/contentstore/courseware_index.py
  lms/envs/common.py
  lms/envs/production.py
  lms/lib/courseware_search/lms_filter_generator.py
Labels: open-source-contribution, needs triage

#30644 [BD-13][BB-6146] refactor: delete ModuleSystem's `file_data` property
  xmodule/x_module.py
Labels: blended

#30646 [BD-13][BB-6147] refactor: remove `error_descriptor_class` and `NonStaffErrorBlock`
  cms/djangoapps/contentstore/views/preview.py
  lms/djangoapps/courseware/module_render.py
  setup.py
  xmodule/error_module.py
  xmodule/tests/__init__.py
  xmodule/tests/test_conditional.py
  xmodule/tests/test_error_module.py
  xmodule/x_module.py
Labels: blended
