Repository openedx/edx-platform, pull requests merged in 2023-03, with the labels that each got.

#31853 [FC-0009] New actions menu for editing components in Studio (behind waffle flag)
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/contentstore/views/preview.py
  cms/static/js/views/pages/container.js
  cms/static/sass/elements/_xblocks.scss
  cms/templates/studio_xblock_wrapper.html
Labels: open-source-contribution, core committer, FC

#31862 fix: use supported YouTube API for transcripts imports
  cms/djangoapps/contentstore/tests/test_transcripts_utils.py
  cms/djangoapps/contentstore/tests/utils.py
  cms/djangoapps/contentstore/views/tests/test_transcripts.py
  cms/djangoapps/contentstore/views/transcripts_ajax.py
  cms/envs/bok_choy.py
  cms/envs/bok_choy_docker.py
  cms/envs/common.py
  lms/envs/bok_choy.py
  lms/envs/bok_choy_docker.py
  lms/envs/common.py
  xmodule/tests/test_transcripts_utils.py
  xmodule/tests/test_video.py
  xmodule/video_module/transcripts_utils.py
Labels: open-source-contribution, core committer

#31821 feat: add send survey report button
  openedx/features/survey_report/admin.py
Labels: open-source-contribution, product review

#31295 Add openedx-filters hook to account settings before rendering it context
  openedx/core/djangoapps/user_api/accounts/settings_views.py
  openedx/core/djangoapps/user_api/accounts/tests/test_filters.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#31901 chore: bump edx-enterprise to 3.61.6
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: emet

#31671 fix: Fix units hover tooltips in studio which are overlapping by other page content
  cms/static/sass/elements/_layout.scss
Labels: open-source-contribution

#31978 Apply Django security fix to Olive master
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/django.txt
Labels: open-source-contribution, core committer

#31984 fix: typo in the documentation for hooks
  docs/guides/hooks/filters.rst
Labels: open-source-contribution, core committer

#32005 chore: bumping enterprise version 3.61.8
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: emet
