Repository openedx/edx-platform, pull requests merged in 2023-02, with the labels that each got.

#31723 Update django for olive
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/django.txt
Labels: open-source-contribution, core committer

#31724 chore: update LTI Consumer XBlock
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, core committer

#30975 feat: added organization dropdown in studio
  cms/djangoapps/contentstore/tests/test_course_create_rerun.py
  cms/djangoapps/contentstore/views/course.py
  cms/static/sass/views/_course-create.scss
  cms/static/sass/views/_dashboard.scss
  cms/templates/index.html
Labels: open-source-contribution, product review

#31752 fix: add missing variables to library_listing context
  cms/djangoapps/contentstore/views/course.py
Labels: open-source-contribution

#31350 feat: hook xblock publish, delete and duplicate openedx-events
  cms/djangoapps/contentstore/signals/handlers.py
  cms/djangoapps/contentstore/views/block.py
  cms/djangoapps/contentstore/views/tests/test_block.py
  docs/guides/hooks/events.rst
  xmodule/modulestore/mixed.py
  xmodule/modulestore/tests/test_mixed_modulestore.py
Labels: open-source-contribution, event-bus

#31491 feat: Added submission history API and extended enrollment API to support grading and finished flags.
  lms/djangoapps/grades/rest_api/v1/tests/test_views.py
  lms/djangoapps/grades/rest_api/v1/urls.py
  lms/djangoapps/grades/rest_api/v1/utils.py
  lms/djangoapps/grades/rest_api/v1/views.py
  openedx/core/djangoapps/enrollments/paginators.py
Labels: open-source-contribution, waiting on author, changes requested

#31431 feat: add SurveyReportUpload and add send report method
  lms/envs/production.py
  lms/envs/test.py
  openedx/features/survey_report/api.py
  openedx/features/survey_report/management/commands/generate_report.py
  openedx/features/survey_report/management/commands/tests/test_generate_report.py
  openedx/features/survey_report/migrations/0004_surveyreportupload.py
  openedx/features/survey_report/migrations/0005_surveyreportanonymoussiteid.py
  openedx/features/survey_report/models.py
Labels: open-source-contribution, product review

#31788 feat: allow using all components of LibraryContentBlock
  lms/djangoapps/course_blocks/transformers/library_content.py
  xmodule/library_content_block.py
  xmodule/tests/test_library_content.py
Labels: open-source-contribution, core committer

#31813 feat: put sending xblock events over bus behind feature flag
  cms/djangoapps/contentstore/signals/handlers.py
  cms/envs/devstack.py
  lms/envs/devstack.py
Labels: open-source-contribution

#31718 Install xblock-poll from pypi
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/testing.txt
Labels: open-source-contribution, core committer

#31588 feat: Add "certificate_available_date" in edX's Course Details API
  docs/swagger.yaml
  lms/djangoapps/course_api/serializers.py
  lms/djangoapps/course_api/tests/mixins.py
  lms/djangoapps/course_api/tests/test_serializers.py
  lms/djangoapps/course_api/views.py
Labels: open-source-contribution

#31731 Correct link to byte-size issues and tasks
  CONTRIBUTING.rst
Labels: open-source-contribution
