Repository openedx/edx-platform, pull requests merged in 2023-11, with the labels that each got.

#33651 Update openedx-learning, new format for the "get object tags" REST API (unstable) [FC-0036]
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, FC

#33611 feat: add update taxonomy orgs rest api [FC-0036]
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/serializers.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/views.py
  openedx/core/djangoapps/content_tagging/rules.py
Labels: open-source-contribution, FC

#33563 [FC-0036] feat: Display Units Taxonomy Tags in drawer
  cms/djangoapps/contentstore/tests/test_contentstore.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/js/views/course_outline.js
  cms/static/js/views/xblock_outline.js
  cms/static/sass/_build-v1.scss
  cms/static/sass/elements/_drawer.scss
  cms/templates/course_outline.html
  cms/templates/js/course-outline.underscore
Labels: open-source-contribution, FC

#31715 feat: Add toggle to allow redirecting to courseware after enrollment.
  common/djangoapps/student/tests/tests.py
  common/djangoapps/student/toggles.py
  common/djangoapps/student/views/management.py
Labels: open-source-contribution

#33684 fix: check masquerade on instructor dashboard tab acess check
  lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
  lms/djangoapps/instructor/views/instructor_dashboard.py
Labels: open-source-contribution

#33293 fix: [FC-0031] Fix count items in pagination for api courses list.
  lms/djangoapps/course_api/api.py
  lms/djangoapps/course_api/forms.py
  lms/djangoapps/course_api/tests/test_forms.py
  lms/djangoapps/course_api/tests/test_views.py
  lms/djangoapps/course_api/views.py
  lms/envs/common.py
Labels: open-source-contribution, FC

#33686 [FC-0036] fix: allows taxonomy list to "filter by org" even if org does not exist
  openedx/core/djangoapps/content_tagging/rest_api/v1/serializers.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/views.py
Labels: open-source-contribution, FC

#33310 feat: link LTI Provider launches to authenticated users
  lms/djangoapps/lti_provider/migrations/0004_require_user_account.py
  lms/djangoapps/lti_provider/models.py
  lms/djangoapps/lti_provider/tests/test_users.py
  lms/djangoapps/lti_provider/tests/test_views.py
  lms/djangoapps/lti_provider/users.py
  lms/djangoapps/lti_provider/views.py
  lms/templates/lti_provider/user-auth-error.html
Labels: open-source-contribution

#31668 fix: Fix absent notification message after submit Generate Exception …
  lms/static/js/certificates/views/certificate_allowlist.js
Labels: open-source-contribution, waiting for eng review, needs maintainer attention

#33663 feat: add import taxonomy endpoint
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/views.py
  openedx/core/djangoapps/content_tagging/rules.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#33368 feat: FC-0012 - add (--no-segment) option to extract_translations
  Makefile
Labels: open-source-contribution

#33295 feat: [FC-0031] Add field profile_image to CommentSerializer
  lms/djangoapps/discussion/rest_api/serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  openedx/core/djangoapps/user_api/accounts/api.py
Labels: open-source-contribution, FC

#33696 Display tag counts on course outline [FC-0036]
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/templates/js/course-outline.underscore
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/tests/test_api.py
  openedx/core/djangoapps/content_tagging/tests/test_rules.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, FC

#33645 feat: Tag List on Unit page [FC-0036]
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/js/models/xblock_info.js
  cms/static/js/views/course_outline.js
  cms/static/js/views/pages/container.js
  cms/static/js/views/pages/container_subviews.js
  cms/static/js/views/utils/tagging_drawer_utils.js
  cms/static/sass/elements/_controls.scss
  cms/static/sass/views/_container.scss
  cms/templates/container.html
  cms/templates/js/tag-list.underscore
  cms/templates/studio_xblock_wrapper.html
Labels: open-source-contribution, FC

#33656 [Quince Backport] feat: link LTI Provider launches to authenticated users
  lms/djangoapps/lti_provider/migrations/0004_require_user_account.py
  lms/djangoapps/lti_provider/models.py
  lms/djangoapps/lti_provider/tests/test_users.py
  lms/djangoapps/lti_provider/tests/test_views.py
  lms/djangoapps/lti_provider/users.py
  lms/djangoapps/lti_provider/views.py
  lms/templates/lti_provider/user-auth-error.html
Labels: open-source-contribution, backport

#33761 Display tags on the Unit page in Studio (feature-flagged) - Take 2 [FC-0036]
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/js/models/xblock_info.js
  cms/static/js/views/course_outline.js
  cms/static/js/views/pages/container.js
  cms/static/js/views/pages/container_subviews.js
  cms/static/js/views/utils/tagging_drawer_utils.js
  cms/static/sass/elements/_controls.scss
  cms/static/sass/views/_container.scss
  cms/templates/container.html
  cms/templates/js/tag-list.underscore
  cms/templates/studio_xblock_wrapper.html
Labels: open-source-contribution, FC

#33729 fix: session_language url renamed to update_language
  cms/templates/widgets/header.html
  lms/templates/header/header.html
  lms/templates/navigation/navigation.html
Labels: open-source-contribution

#33727 fix: CSRF errors in POST requests to LMS
  lms/envs/common.py
Labels: open-source-contribution

#33790 fix: CSRF errors in POST requests to LMS
  lms/envs/common.py
Labels: open-source-contribution

#33294 feat: [FC-0031] Add DefaultPagination in UserCourseEnrollmentsList
  lms/djangoapps/mobile_api/users/tests.py
  lms/djangoapps/mobile_api/users/views.py
  lms/djangoapps/mobile_api/utils.py
  lms/urls.py
Labels: open-source-contribution, FC

#33757 Fix ObjectTag taxonomy rule [FC-0036]
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rules.py
Labels: open-source-contribution

#33839 feat: Bump openedx-learning to 0.3.6
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution
