Repository openedx/edx-platform, pull requests merged in 2023-10, with the labels that each got.

#33184 feat: Expected error part of EXPECTED_ERRORS
  lms/envs/common.py
  openedx/core/lib/docs/decisions/0001-logging-and-monitoring-ignored-errors.rst
  openedx/core/lib/docs/decisions/0002-logging-and-monitoring-expected-errors-removed.rst
  openedx/core/lib/docs/how_tos/logging-and-monitoring-expected-errors.rst
  openedx/core/lib/docs/how_tos/logging-and-monitoring-ignored-errors.rst
  openedx/core/lib/request_utils.py
  openedx/core/lib/tests/test_request_utils.py
Labels: open-source-contribution

#33408 feat: remove askbot changes in depr216
  cms/envs/test.py
  lms/static/sass/course/base/_extends.scss
Labels: open-source-contribution

#33378 Simplify Tag Models [FC-0030]
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/migrations/0002_system_defined_taxonomies.py
  openedx/core/djangoapps/content_tagging/migrations/0006_simplify_models.py
  openedx/core/djangoapps/content_tagging/models/__init__.py
  openedx/core/djangoapps/content_tagging/models/base.py
  openedx/core/djangoapps/content_tagging/models/system_defined.py
  openedx/core/djangoapps/content_tagging/tasks.py
  openedx/core/djangoapps/content_tagging/tests/test_api.py
  openedx/core/djangoapps/content_tagging/tests/test_models.py
  openedx/core/djangoapps/content_tagging/tests/test_rules.py
  openedx/core/djangoapps/content_tagging/tests/test_tasks.py
  openedx/core/djangoapps/content_tagging/types.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#32656 feat: allow oauth configuration per site and backend
  common/djangoapps/third_party_auth/models.py
  common/djangoapps/third_party_auth/pipeline.py
  common/djangoapps/third_party_auth/tests/test_provider.py
  common/djangoapps/third_party_auth/views.py
Labels: open-source-contribution

#33438 Continued simplification of Taxonomy model, squashed migrations [FC-0030]
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/migrations/0001_squashed.py
  openedx/core/djangoapps/content_tagging/migrations/0003_system_defined_fixture.py
  openedx/core/djangoapps/content_tagging/migrations/0004_system_defined_org.py
  openedx/core/djangoapps/content_tagging/migrations/0007_system_defined_org_2.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/tests/test_tasks.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#33459 [BACKPORT] fix: replace py2neo with forked package (#33453)
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#33468 fix: replace py2neo with forked package
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#33308 feat: Adds disable_progress_graph attribute to the returned course_me…
  lms/djangoapps/course_home_api/progress/serializers.py
  lms/djangoapps/course_home_api/progress/views.py
Labels: open-source-contribution

#33471 build: kickoff the Quince release
  .github/pull_request_template.md
  .tx/config
  openedx/core/release.py
Labels: open-source-contribution

#33464 feat: adds endpoint for downloading the taxonomy templates [FC-0036]
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/urls.py
Labels: open-source-contribution

#33343 fix: clarify grade range numerical values
  cms/static/js/views/settings/grading.js
Labels: open-source-contribution

#33338 feat: set course for wiki based on the wiki_slug
  lms/djangoapps/course_wiki/middleware.py
  lms/djangoapps/course_wiki/tests/test_middleware.py
Labels: open-source-contribution

#33275 Fix studio for users with derived roles and some other related changes [BB-7834]
  common/djangoapps/student/roles.py
  lms/djangoapps/courseware/rules.py
  lms/djangoapps/instructor/permissions.py
  lms/djangoapps/instructor/views/api.py
Labels: open-source-contribution

#33484 Enforce type hints for tagging code in edx-platform [FC-0030]
  mypy.ini
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/content_staging/tests/test_clipboard.py
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/serializers.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/tasks.py
  openedx/core/djangoapps/content_tagging/tests/test_rules.py
  openedx/core/djangoapps/content_tagging/tests/test_tasks.py
  openedx/core/djangoapps/xblock/tests/test_utils.py
Labels: open-source-contribution, FC

#33483 feat: override permissions for export taxonomy
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rules.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#33491 fix: limited staff cohorts and gradebook access [BB-7962]
  common/djangoapps/student/auth.py
  common/djangoapps/student/tests/test_authz.py
Labels: open-source-contribution

#33490 fix: Disable reset button until an answer is submitted.
  lms/templates/problem.html
Labels: open-source-contribution

#33439 feat: New link on studio home to Taxonomy list and flag added [FC-0036]
  cms/djangoapps/contentstore/rest_api/v1/serializers/home.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_home.py
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/contentstore/utils.py
  cms/templates/index.html
Labels: open-source-contribution, FC

#33413 fix: update taxonomies permission rules
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/filters.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/urls.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/views.py
  openedx/core/djangoapps/content_tagging/rules.py
  openedx/core/djangoapps/content_tagging/tests/test_api.py
  openedx/core/djangoapps/content_tagging/tests/test_rules.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#32994 docs: decision to standardize django/djangojs po files FC-0012
  docs/decisions/0018-standarize-django-po-files.rst
Labels: open-source-contribution

#33525 feat: Add url that exposes taxonomy tags CRUD API
  cms/urls.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/urls.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#33476 [Quince backport] Squash Tagging/Taxonomy migrations, bump openedx-learning to 0.2.3 [FC-0030]
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/migrations/0001_squashed.py
  openedx/core/djangoapps/content_tagging/migrations/0003_system_defined_fixture.py
  openedx/core/djangoapps/content_tagging/migrations/0004_system_defined_org.py
  openedx/core/djangoapps/content_tagging/migrations/0007_system_defined_org_2.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/tests/test_tasks.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#33166 doc: design for `atlas pull` for the edx-platform and its plugins FC-0012
  docs/decisions/0019-oep-58-atlas-translations-design.rst
Labels: open-source-contribution

#33493 feat: add filtering via filenames in asset list endpoint
  cms/djangoapps/contentstore/asset_storage_handlers.py
  cms/djangoapps/contentstore/views/tests/test_assets.py
Labels: open-source-contribution

#33472 build: nudge devs about Quince release in github
  .github/pull_request_template.md
Labels: open-source-contribution, waiting for eng review

#33025 fix: User retirement 404 for state RETIRING_FORUMS
  lms/djangoapps/discussion/rest_api/urls.py
Labels: open-source-contribution

#33553 chore: update content_tagging for compatibility with new openedx-learning [FC-0036]
  openedx/core/djangoapps/content_tagging/tests/test_api.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, FC

#33395 feat: emit signal for thread, response, and comment created event
  lms/djangoapps/discussion/django_comment_client/base/tests.py
  lms/djangoapps/discussion/django_comment_client/base/views.py
Labels: open-source-contribution
