Repository openedx/edx-platform, pull requests merged in 2023-05, with the labels that each got.

#32007 chore: Switch from edx-sphinx-theme to sphinx-book-theme
  Makefile
  docs/api/conf.py
  docs/guides/conf.py
  docs/swagger.yaml
  docs/technical/conf.py
  requirements/common_constraints.txt
  requirements/edx/base.txt
  requirements/edx/doc.in
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#32107 [FC-0014] [palm] Add GA 4 support to edX platform
  lms/envs/common.py
  lms/envs/production.py
  lms/templates/certificates/accomplishment-base.html
  lms/templates/main.html
  lms/templates/main_django.html
  lms/templates/public_video_share_embed.html
  openedx/core/djangoapps/site_configuration/templatetags/configuration.py
Labels: open-source-contribution

#32165 fix: anonymous student IDs [BD-13]
  cms/djangoapps/contentstore/views/preview.py
  cms/djangoapps/contentstore/views/tests/test_preview.py
  common/djangoapps/xblock_django/constants.py
  common/djangoapps/xblock_django/user_service.py
  lms/djangoapps/courseware/block_render.py
  lms/djangoapps/courseware/tests/test_block_render.py
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
  openedx/features/course_experience/tests/views/test_course_updates.py
  xmodule/capa_block.py
  xmodule/html_block.py
  xmodule/tests/__init__.py
  xmodule/tests/helpers.py
  xmodule/tests/test_html_block.py
  xmodule/video_block/video_block.py
  xmodule/x_module.py
Labels: blended

#32018 Decouple XModule styles from LMS/Studio styles
  cms/envs/common.py
  cms/static/sass/_build-v1.scss
  lms/envs/common.py
  lms/static/sass/_build-course.scss
  pavelib/assets.py
  xmodule/css/annotatable/display.scss
  xmodule/css/capa/display.scss
  xmodule/css/editor/edit.scss
  xmodule/css/html/display.scss
  xmodule/css/lti/lti.scss
  xmodule/css/poll/display.scss
  xmodule/css/sequence/display.scss
  xmodule/css/tabs/tabs.scss
  xmodule/css/video/accessible_menu.scss
  xmodule/css/video/display.scss
  xmodule/css/word_cloud/display.scss
  xmodule/static_content.py
  xmodule/util/xmodule_django.py
Labels: open-source-contribution

#32116 fix: support files with a unicode signature in the Instructor Dashboard API
  lms/djangoapps/instructor/tests/test_api.py
  lms/djangoapps/instructor/views/api.py
Labels: open-source-contribution, core committer

#32094 fix: remove relative due date limit
  cms/static/js/spec/views/pages/course_outline_spec.js
  cms/static/js/views/modals/course_outline_modals.js
  cms/templates/js/self-paced-due-date-editor.underscore
Labels: open-source-contribution, core committer

#32148 feat: add Waffle Flag to disable resetting self-paced deadlines by learners
  openedx/features/course_experience/__init__.py
  openedx/features/course_experience/api/v1/tests/test_views.py
  openedx/features/course_experience/utils.py
Labels: open-source-contribution, core committer

#32106 [FC-0014] [olive] Add GA 4 support to edX platform
  lms/envs/common.py
  lms/envs/production.py
  lms/templates/certificates/accomplishment-base.html
  lms/templates/main.html
  lms/templates/main_django.html
  openedx/core/djangoapps/site_configuration/templatetags/configuration.py
Labels: open-source-contribution

#32097 fix: missing advance_settings_access template variable
  cms/djangoapps/contentstore/tests/test_course_settings.py
  cms/djangoapps/contentstore/views/course.py
  cms/templates/settings.html
  cms/templates/settings_graders.html
  cms/templates/widgets/header.html
  common/djangoapps/student/auth.py
Labels: open-source-contribution

#32188 Decouple XModule styles from LMS/Studio styles
  cms/envs/common.py
  cms/static/sass/_build-v1.scss
  lms/envs/common.py
  lms/static/sass/_build-course.scss
  pavelib/assets.py
  xmodule/css/annotatable/display.scss
  xmodule/css/capa/display.scss
  xmodule/css/editor/edit.scss
  xmodule/css/html/display.scss
  xmodule/css/lti/lti.scss
  xmodule/css/poll/display.scss
  xmodule/css/sequence/display.scss
  xmodule/css/tabs/tabs.scss
  xmodule/css/video/accessible_menu.scss
  xmodule/css/video/display.scss
  xmodule/css/word_cloud/display.scss
  xmodule/static_content.py
  xmodule/util/xmodule_django.py
Labels: open-source-contribution

#32132 [FC-0009] Show a preview of what will be pasted with new Paste Component Button
  cms/djangoapps/contentstore/views/block.py
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/views/helpers.py
  cms/djangoapps/contentstore/views/tests/test_helpers.py
  cms/static/js/views/pages/container.js
  cms/static/sass/elements/_modules.scss
  lms/templates/studio_render_children_view.html
  openedx/core/djangoapps/content_staging/api.py
  openedx/core/djangoapps/content_staging/serializers.py
  openedx/core/djangoapps/content_staging/tests/test_clipboard.py
  openedx/core/djangoapps/content_staging/views.py
Labels: open-source-contribution, core committer

#32177 Fix some warnings from usage of deprecated properties
  cms/templates/asset_index.html
  cms/templates/course_outline.html
  lms/djangoapps/courseware/tests/test_block_render.py
  xmodule/modulestore/mongo/base.py
  xmodule/x_module.py
Labels: open-source-contribution, core committer

#32152 feat: updating edx-search version to 3.5.0
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, automerge

#32231 fix: Include common in edx-platform packages
  setup.py
Labels: open-source-contribution

#32117 feat: update event_bus_kafka and add event_bus_redis
  cms/envs/devstack.py
  lms/envs/devstack.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#32220 fix: update shard names for GH tests
  .github/workflows/unit-tests-gh-hosted.yml
  .github/workflows/unit-tests.yml
Labels: open-source-contribution, core committer

#31741 fix: upgrade reminder email image
  openedx/core/djangoapps/schedules/resolvers.py
Labels: open-source-contribution

#32237 Decouple XModule styles from LMS/Studio styles (attempt 3)
  cms/envs/common.py
  cms/static/sass/_build-v1.scss
  lms/envs/common.py
  lms/static/sass/_build-course.scss
  pavelib/assets.py
  xmodule/css/annotatable/display.scss
  xmodule/css/capa/display.scss
  xmodule/css/editor/edit.scss
  xmodule/css/html/display.scss
  xmodule/css/lti/lti.scss
  xmodule/css/poll/display.scss
  xmodule/css/sequence/display.scss
  xmodule/css/tabs/tabs.scss
  xmodule/css/video/accessible_menu.scss
  xmodule/css/video/display.scss
  xmodule/css/word_cloud/display.scss
  xmodule/static_content.py
  xmodule/util/xmodule_django.py
Labels: open-source-contribution

#32024 [FAL-3383] feat: New waffleflag to enable or disable new video editor flow
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/contentstore/views/tests/test_videos.py
  cms/djangoapps/contentstore/views/videos.py
  cms/static/js/views/pages/container.js
  cms/templates/studio_xblock_wrapper.html
  test_root/data/Q291cnNlTG9jYXRvcignb3JnLjIzMTYnLCAnY291cnNlXzIzMTYnLCAnUnVuXzIzMTYnLCBOb25lLCBOb25lKQ==/good.tar.gz
  test_root/data/Q291cnNlTG9jYXRvcignb3JnLjIzMTknLCAnY291cnNlXzIzMTknLCAnUnVuXzIzMTknLCBOb25lLCBOb25lKQ==/good.tar.gz
Labels: open-source-contribution

#32221 chore: revert back to using GH runners for Palm
  .github/workflows/unit-tests-gh-hosted.yml
  .github/workflows/unit-tests.yml
  .github/workflows/verify-gha-unit-tests-count.yml
Labels: open-source-contribution, core committer

#32099 fix: update transcripts field in video on upload
  cms/djangoapps/contentstore/views/tests/test_transcripts.py
  cms/djangoapps/contentstore/views/transcripts_ajax.py
  lms/djangoapps/courseware/tests/test_video_handlers.py
  xmodule/video_block/video_handlers.py
Labels: open-source-contribution

#32227 fix: upgrade reminder email image
  openedx/core/djangoapps/schedules/resolvers.py
Labels: open-source-contribution

#32265 chore: upgrade Django to 3.2.19
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/django.txt
Labels: open-source-contribution, core committer

#32295 chore: upgrade Django to 3.2.19
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, core committer

#32058 refactor: Duplicate and update primitives made available.
  cms/djangoapps/contentstore/tests/test_libraries.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/block.py
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/views/tests/test_block.py
  xmodule/modulestore/split_mongo/split.py
  xmodule/modulestore/store_utilities.py
  xmodule/modulestore/tests/test_store_utilities.py
Labels: open-source-contribution

#32309 fix: missing advance_settings_access template variable [BACKPORT]
  cms/djangoapps/contentstore/tests/test_course_settings.py
  cms/djangoapps/contentstore/views/course.py
  cms/templates/settings.html
  cms/templates/settings_graders.html
  cms/templates/widgets/header.html
  common/djangoapps/student/auth.py
Labels: open-source-contribution

#32331 feat: Extending API functionality for proctoring errors
  cms/djangoapps/contentstore/rest_api/v0/tests/test_advanced_settings.py
  cms/djangoapps/contentstore/rest_api/v0/views/advanced_settings.py
  cms/djangoapps/contentstore/rest_api/v1/serializers.py
  cms/djangoapps/contentstore/rest_api/v1/tests/test_views.py
  cms/djangoapps/contentstore/rest_api/v1/urls.py
  cms/djangoapps/contentstore/rest_api/v1/views.py
Labels: open-source-contribution
