Repository openedx/edx-platform, pull requests merged in 2023-06, with the labels that each got.

#32339 [FC-0009] Update text of new clipboard menu, hide it in libraries
  cms/djangoapps/contentstore/views/preview.py
  cms/templates/studio_xblock_wrapper.html
Labels: open-source-contribution, core committer

#32276 Remove extra </div> tag from calculators's HTML
  lms/templates/calculator/toggle_calculator.html
Labels: open-source-contribution

#32383 chore: remove 2nd entry of the same xblock
  requirements/edx/base.in
Labels: open-source-contribution

#32399 feat: Create DRF for course grading
  cms/djangoapps/contentstore/rest_api/v1/serializers/__init__.py
  cms/djangoapps/contentstore/rest_api/v1/serializers/grading.py
  cms/djangoapps/contentstore/rest_api/v1/tests/test_grading.py
  cms/djangoapps/contentstore/rest_api/v1/urls.py
  cms/djangoapps/contentstore/rest_api/v1/views/__init__.py
  cms/djangoapps/contentstore/rest_api/v1/views/grading.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/course.py
Labels: open-source-contribution

#32273 Make Split Mongo's CachedDescriptorSystem load field-data service on demand
  lms/djangoapps/courseware/tests/test_block_render.py
  lms/djangoapps/gating/tests/test_integration.py
  xmodule/modulestore/inheritance.py
  xmodule/modulestore/mongo/base.py
  xmodule/modulestore/split_mongo/caching_descriptor_system.py
  xmodule/modulestore/xml.py
  xmodule/tests/test_import.py
  xmodule/x_module.py
  xmodule/xml_block.py
Labels: open-source-contribution, core committer

#32380 enhancement: add support for caching programs for one site
  openedx/core/djangoapps/catalog/management/commands/cache_programs.py
  openedx/core/djangoapps/catalog/management/commands/tests/test_cache_programs.py
Labels: open-source-contribution

#32461 chore: update PR template for Palm release
  .github/pull_request_template.md
Labels: open-source-contribution, core committer

#32356 feat: remove block-specific handling from runtime role checks [FC-0026]
  common/djangoapps/xblock_django/constants.py
  common/djangoapps/xblock_django/tests/test_user_service.py
  common/djangoapps/xblock_django/user_service.py
  lms/djangoapps/courseware/block_render.py
  lms/djangoapps/courseware/tests/test_block_render.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/testing.txt
  xmodule/x_module.py
Labels: open-source-contribution, core committer

#32341 chore: replace edx-shinx-theme with sphinx-book-theme in dev dependencies
  requirements/edx/development.in
  requirements/edx/development.txt
Labels: open-source-contribution

#31061 fix: save scroll position on exit from video xblock fullscreen mode
  xmodule/js/src/video/04_video_full_screen.js
Labels: open-source-contribution, product review

#32306 Fix/scroll position on exit from video fullscreen mode palm
  xmodule/js/src/video/04_video_full_screen.js
Labels: open-source-contribution

#31053 fix: save scroll position on exit from video xblock fullscreen mode
  common/lib/xmodule/xmodule/js/src/video/04_video_full_screen.js
Labels: open-source-contribution

#31871 fix: save scroll position on exit from video xblock fullscreen mode
  xmodule/js/src/video/04_video_full_screen.js
Labels: open-source-contribution

#32368 feat!: remove block handling from runtime initialization of ReplaceURLService [FC-0026]
  cms/djangoapps/contentstore/views/preview.py
  cms/djangoapps/contentstore/views/tests/test_preview.py
  common/djangoapps/static_replace/services.py
  common/djangoapps/static_replace/test/test_static_replace.py
  common/djangoapps/static_replace/wrapper.py
  lms/djangoapps/courseware/block_render.py
  lms/djangoapps/courseware/tests/test_block_render.py
  openedx/core/djangoapps/xblock/runtime/shims.py
  xmodule/x_module.py
Labels: open-source-contribution, core committer

#31956 test: use new newer test format instead of deprecated yield tests in modulestore/tests/test_mongo.py
  xmodule/modulestore/tests/test_mongo.py
Labels: open-source-contribution

#32346 [FC-0009] Copy/Paste associated static assets
  cms/djangoapps/contentstore/helpers.py
  cms/djangoapps/contentstore/views/tests/test_clipboard_paste.py
  cms/djangoapps/contentstore/xblock_services/xblock_service.py
  cms/envs/common.py
  cms/static/js/views/pages/container.js
  openedx/core/djangoapps/content_staging/admin.py
  openedx/core/djangoapps/content_staging/api.py
  openedx/core/djangoapps/content_staging/data.py
  openedx/core/djangoapps/content_staging/filters.py
  openedx/core/djangoapps/content_staging/migrations/0002_stagedcontentfile.py
  openedx/core/djangoapps/content_staging/models.py
  openedx/core/djangoapps/content_staging/tests/test_clipboard.py
  openedx/core/djangoapps/content_staging/views.py
  openedx/core/lib/xblock_serializer/block_serializer.py
  openedx/core/lib/xblock_serializer/data.py
  openedx/core/lib/xblock_serializer/test_api.py
  openedx/core/lib/xblock_serializer/test_utils.py
  openedx/core/lib/xblock_serializer/utils.py
Labels: open-source-contribution, core committer, FC

#32517 feat: Remove block_structure.invalidate_cache_on_publish waffle flag …
  openedx/core/djangoapps/content/block_structure/config/__init__.py
  openedx/core/djangoapps/content/block_structure/signals.py
  openedx/core/djangoapps/content/block_structure/tests/test_signals.py
Labels: open-source-contribution

#32357 feat: remove field-data binding from the runtime [FC-0026]
  cms/djangoapps/contentstore/tests/test_i18n.py
  cms/djangoapps/contentstore/views/preview.py
  cms/djangoapps/contentstore/views/tests/test_preview.py
  lms/djangoapps/courseware/block_render.py
  lms/djangoapps/courseware/tests/test_block_render.py
  lms/djangoapps/courseware/tests/test_views.py
  openedx/core/djangoapps/schedules/tests/test_resolvers.py
  openedx/features/course_experience/tests/views/test_course_updates.py
  xmodule/services.py
Labels: open-source-contribution, core committer

#32420 feat: reuse runtime services and wrappers between XBlocks [FC-0026]
  cms/djangoapps/contentstore/views/preview.py
  lms/djangoapps/courseware/block_render.py
  lms/djangoapps/courseware/tests/test_block_render.py
  lms/djangoapps/courseware/tests/test_discussion_xblock.py
  lms/djangoapps/courseware/testutils.py
  lms/djangoapps/courseware/views/views.py
  lms/djangoapps/instructor_task/tasks_helper/module_state.py
  lms/djangoapps/instructor_task/tests/test_tasks.py
  lms/djangoapps/lti_provider/tests/test_views.py
  lms/djangoapps/lti_provider/views.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
  xmodule/services.py
  xmodule/tests/test_library_content.py
  xmodule/tests/test_lti20_unit.py
  xmodule/tests/test_lti_unit.py
  xmodule/tests/test_sequence.py
  xmodule/tests/test_split_test_block.py
  xmodule/tests/test_vertical.py
  xmodule/x_module.py
Labels: open-source-contribution, core committer

#32566 feat: configure acceptable language codes for youtube transcripts
  cms/envs/common.py
  lms/envs/common.py
  xmodule/tests/test_transcripts_utils.py
  xmodule/video_block/transcripts_utils.py
Labels: open-source-contribution

#32552 Cleaning up base.in: Remove unused dependencies, separate optional ones
  lms/djangoapps/learner_recommendations/utils.py
  lms/djangoapps/utils.py
  requirements/edx/base.in
  requirements/edx/base.txt
  requirements/edx/bundled.in
  requirements/edx/development.txt
  requirements/edx/github.in
  requirements/edx/kernel.in
  requirements/edx/testing.txt
  xmodule/modulestore/tests/utils.py
  xmodule/static_content.py
Labels: open-source-contribution, core committer
