Repository openedx/edx-platform, pull requests merged in 2023-08, with the labels that each got.

#32812 [FC-0009] Studio backend APIs to support copying and pasting of entire Units
  cms/djangoapps/contentstore/helpers.py
  cms/djangoapps/contentstore/views/tests/test_clipboard_paste.py
  openedx/core/djangoapps/content_staging/tests/test_clipboard.py
  xmodule/xml_block.py
Labels: open-source-contribution, core committer, FC

#32998 feat: use feature setting for beta tester notify
  lms/templates/instructor/instructor_dashboard_2/membership.html
Labels: open-source-contribution

#32891 [FC-0009] New actions menu for copy/pasting units in Studio (behind waffle flag)
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/js/factories/outline.js
  cms/static/js/views/course_outline.js
  cms/static/js/views/pages/course_outline.js
  cms/static/js/views/xblock_outline.js
  cms/static/sass/elements/_modules.scss
  cms/templates/course_outline.html
  cms/templates/js/course-outline.underscore
Labels: open-source-contribution

#33015 fix: error on course outline in Studio due to browser caching old JS file [FC-0009]
  cms/templates/js/course-outline.underscore
Labels: FC

#32578 fix: remove language_session_key usage
  cms/urls.py
  lms/urls.py
  openedx/core/djangoapps/dark_lang/middleware.py
  openedx/core/djangoapps/dark_lang/tests.py
  openedx/core/djangoapps/dark_lang/views.py
  openedx/core/djangoapps/lang_pref/middleware.py
  openedx/core/djangoapps/lang_pref/tests/test_middleware.py
  openedx/core/djangoapps/lang_pref/tests/test_views.py
  openedx/core/djangoapps/lang_pref/views.py
Labels: ready to merge

#32782 feat: Create DRF for course team
  cms/djangoapps/contentstore/rest_api/v1/serializers/__init__.py
  cms/djangoapps/contentstore/rest_api/v1/serializers/course_team.py
  cms/djangoapps/contentstore/rest_api/v1/urls.py
  cms/djangoapps/contentstore/rest_api/v1/views/__init__.py
  cms/djangoapps/contentstore/rest_api/v1/views/course_team.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_course_team.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/user.py
Labels: open-source-contribution

#33046 [FC-0009] fix: Prevent multiple dropdowns opening at once
  cms/static/js/views/course_outline.js
  cms/static/js/views/pages/container.js
Labels: open-source-contribution

#32980 [FC-0009] feat: Remove component-level copy/paste feature flag
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/contentstore/views/preview.py
  cms/djangoapps/contentstore/views/tests/test_unit_page.py
  cms/djangoapps/contentstore/views/tests/utils.py
  cms/templates/studio_xblock_wrapper.html
Labels: open-source-contribution

#32971 feanil/api docs
  docs/concepts/index.rst
  docs/concepts/rest_apis.rst
  docs/how-tos/use_the_api.rst
  docs/references/auth_code_samples.rst
  docs/references/index.rst
  docs/references/lms_apis.rst
Labels: waiting for eng review

#33061 fix: refactor MakoService to allow specifying namespace per template
  cms/djangoapps/contentstore/views/tests/test_preview.py
  cms/lib/xblock/authoring_mixin.py
  cms/templates/library-block-author-preview-header.html
  common/djangoapps/edxmako/services.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  xmodule/annotatable_block.py
  xmodule/capa_block.py
  xmodule/conditional_block.py
  xmodule/discussion_block.py
  xmodule/error_block.py
  xmodule/html_block.py
  xmodule/library_content_block.py
  xmodule/library_root_xblock.py
  xmodule/lti_block.py
  xmodule/poll_block.py
  xmodule/seq_block.py
  xmodule/split_test_block.py
  xmodule/studio_editable.py
  xmodule/template_block.py
  xmodule/tests/helpers.py
  xmodule/tests/test_conditional.py
  xmodule/tests/test_html_block.py
  xmodule/vertical_block.py
  xmodule/video_block/video_block.py
  xmodule/word_cloud_block.py
Labels: open-source-contribution

#32977 feat: remove the registration.enable_failure_logging temporary Waffle…
  openedx/core/djangoapps/user_authn/views/register.py
  openedx/core/djangoapps/user_authn/views/tests/test_register.py
Labels: open-source-contribution

#30954 Add the default enrollment start date on course creation
  openedx/core/djangoapps/models/tests/test_course_details.py
  xmodule/course_block.py
  xmodule/modulestore/tests/factories.py
  xmodule/tests/test_course_block.py
Labels: open-source-contribution, product review

#32496 feat: BLOCK_STRUCTURES_SETTINGS['PRUNING_ACTIVE'] toggle removed depr31
  cms/envs/common.py
  cms/envs/devstack-experimental.yml
  cms/envs/test.py
  lms/envs/common.py
  lms/envs/devstack-experimental.yml
  lms/envs/test.py
  openedx/core/djangoapps/content/block_structure/models.py
  openedx/core/djangoapps/content/block_structure/tests/test_models.py
Labels: open-source-contribution

#33073 feat: add api for help tokens
  cms/djangoapps/contentstore/rest_api/v1/urls.py
  cms/djangoapps/contentstore/rest_api/v1/views/__init__.py
  cms/djangoapps/contentstore/rest_api/v1/views/help_urls.py
  cms/djangoapps/contentstore/utils.py
Labels: open-source-contribution

#32988 chore: run js tests on all pull requests
  .github/workflows/js-tests.yml
Labels: open-source-contribution

#33077 fix: refactor MakoService to allow specifying template more explicitly (Take 2)
  cms/djangoapps/contentstore/views/tests/test_preview.py
  cms/lib/xblock/authoring_mixin.py
  cms/templates/library-block-author-preview-header.html
  common/djangoapps/edxmako/services.py
  lms/djangoapps/courseware/tests/test_video_mongo.py
  lms/djangoapps/instructor/views/instructor_dashboard.py
  xmodule/annotatable_block.py
  xmodule/capa_block.py
  xmodule/conditional_block.py
  xmodule/discussion_block.py
  xmodule/error_block.py
  xmodule/html_block.py
  xmodule/library_content_block.py
  xmodule/library_root_xblock.py
  xmodule/lti_block.py
  xmodule/poll_block.py
  xmodule/seq_block.py
  xmodule/split_test_block.py
  xmodule/studio_editable.py
  xmodule/template_block.py
  xmodule/tests/helpers.py
  xmodule/tests/test_conditional.py
  xmodule/tests/test_html_block.py
  xmodule/vertical_block.py
  xmodule/video_block/video_block.py
  xmodule/word_cloud_block.py
Labels: open-source-contribution

#32484 fix: float "&nbsp;" symbol in the preview_body
  lms/djangoapps/discussion/rest_api/serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_serializers.py
Labels: open-source-contribution

#32743 fix: TypeError exception during student.send_activation_email task
  openedx/core/djangoapps/user_authn/tasks.py
Labels: open-source-contribution

#32623 fix: TypeError exception during student.send_activation_email task
  openedx/core/djangoapps/user_authn/tasks.py
Labels: open-source-contribution

#33104 fix: incorrect type hints in a few places
  openedx/core/djangoapps/content/learning_sequences/api/processors/schedule.py
  openedx/core/djangoapps/content_staging/data.py
  xmodule/partitions/partitions_service.py
Labels: open-source-contribution

#32736 chore: upgrade Django to 3.2.20
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/django.txt
Labels: open-source-contribution
