Repository openedx/edx-platform, pull requests merged in 2024-07, with the labels that each got.

#35027 refactor: extract `save_xblock_to_user_clipboard` Python API
  openedx/core/djangoapps/content_staging/api.py
  openedx/core/djangoapps/content_staging/data.py
  openedx/core/djangoapps/content_staging/serializers.py
  openedx/core/djangoapps/content_staging/views.py
Labels: create-sandbox

#35005 [FC-0059] feat: Add `order` query param to lib v2 API
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: open-source-contribution, needs reviewer assigned

#34848 feat: [FC-0047] Extend mobile API with course progress and primary courses on dashboard view
  common/djangoapps/student/models/course_enrollment.py
  lms/djangoapps/course_api/blocks/tests/test_views.py
  lms/djangoapps/courseware/courses.py
  lms/djangoapps/mobile_api/course_info/constants.py
  lms/djangoapps/mobile_api/course_info/serializers.py
  lms/djangoapps/mobile_api/course_info/views.py
  lms/djangoapps/mobile_api/tests/test_course_info_serializers.py
  lms/djangoapps/mobile_api/tests/test_course_info_views.py
  lms/djangoapps/mobile_api/users/enums.py
  lms/djangoapps/mobile_api/users/serializers.py
  lms/djangoapps/mobile_api/users/tests.py
  lms/djangoapps/mobile_api/users/views.py
  lms/djangoapps/mobile_api/utils.py
  lms/urls.py
  openedx/features/course_duration_limits/access.py
Labels: open-source-contribution

#35120 chore: update Django to 4.2.14 for Redwood - Security Patch
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
  scripts/user_retirement/requirements/base.txt
  scripts/user_retirement/requirements/testing.txt
Labels: open-source-contribution

#34344 fix: course progress url based on whether the user has learning MFE enabled (for master)
  lms/djangoapps/learner_home/serializers.py
  lms/djangoapps/learner_home/test_serializers.py
  lms/djangoapps/learner_home/utils.py
Labels: open-source-contribution, needs maintainer attention

#34343 fix: course progress url based on whether the user has learning MFE enabled (for Quince)
  lms/djangoapps/learner_home/serializers.py
  lms/djangoapps/learner_home/test_serializers.py
  lms/djangoapps/learner_home/utils.py
Labels: open-source-contribution

#35117 feat: modify PhoneNumberSerializer regex to allow plus symbol at the …
  common/djangoapps/student/migrations/0046_alter_userprofile_phone_number.py
  common/djangoapps/student/models/user.py
  common/djangoapps/student/tests/test_user_profile_properties.py
  openedx/core/djangoapps/user_api/accounts/serializers.py
Labels: open-source-contribution, changes requested, needs maintainer attention

#35092 fix: DiscussionsConfigurations admin error
  openedx/core/djangoapps/discussions/admin.py
  openedx/core/djangoapps/discussions/tests/test_admin.py
Labels: open-source-contribution

#35139 fix: skip block indexing if it raises an error while loading
  openedx/core/djangoapps/content/search/api.py
  openedx/core/djangoapps/content/search/tests/test_api.py
Labels: open-source-contribution, needs reviewer assigned

#33756 refactor: inheritable authoring mixin callbacks for editing & duplication
  cms/djangoapps/contentstore/views/block.py
  cms/djangoapps/contentstore/views/preview.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/lib/xblock/authoring_mixin.py
  xmodule/studio_editable.py
Labels: open-source-contribution

#35103 feat: adds sortable fields to studio content search index [FC-0059]
  openedx/core/djangoapps/content/search/api.py
  openedx/core/djangoapps/content/search/documents.py
  openedx/core/djangoapps/content/search/handlers.py
  openedx/core/djangoapps/content/search/tests/test_api.py
  openedx/core/djangoapps/content/search/tests/test_handlers.py
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/library_context.py
  openedx/core/djangoapps/content_tagging/tests/test_objecttag_export_helpers.py
  openedx/core/djangoapps/xblock/learning_context/learning_context.py
  openedx/core/djangoapps/xblock/rest_api/views.py
Labels: open-source-contribution, FC

#35182 feat: removing djangoapp `demographics`, step 1
  openedx/core/djangoapps/demographics/admin.py
  openedx/core/djangoapps/demographics/api/status.py
  openedx/core/djangoapps/demographics/migrations/0005_remove_demographics_models.py
  openedx/core/djangoapps/demographics/models.py
  openedx/core/djangoapps/demographics/rest_api/v1/views.py
  openedx/core/djangoapps/demographics/tests/__init__.py
  openedx/core/djangoapps/demographics/tests/factories.py
  openedx/core/djangoapps/demographics/tests/test_status.py
Labels: needs maintainer attention

#34920 fix: disable submit button for archived courses
  xmodule/capa_block.py
  xmodule/tests/test_capa_block.py
Labels: open-source-contribution

#35186 feat: removing the application stage 2
  .github/workflows/pylint-checks.yml
  .github/workflows/unit-test-shards.json
  lms/envs/common.py
  lms/urls.py
  openedx/core/djangoapps/demographics/README.rst
  openedx/core/djangoapps/demographics/__init__.py
  openedx/core/djangoapps/demographics/admin.py
  openedx/core/djangoapps/demographics/api/__init__.py
  openedx/core/djangoapps/demographics/api/status.py
  openedx/core/djangoapps/demographics/docs/decisions/0001-demographics-djangoapp-api.rst
  openedx/core/djangoapps/demographics/migrations/0001_initial.py
  openedx/core/djangoapps/demographics/migrations/0002_clean_duplicate_entries.py
  openedx/core/djangoapps/demographics/migrations/0003_auto_20200827_1949.py
  openedx/core/djangoapps/demographics/migrations/0004_alter_historicaluserdemographics_options.py
  openedx/core/djangoapps/demographics/migrations/0005_remove_demographics_models.py
  openedx/core/djangoapps/demographics/migrations/__init__.py
  openedx/core/djangoapps/demographics/models.py
  openedx/core/djangoapps/demographics/rest_api/__init__.py
  openedx/core/djangoapps/demographics/rest_api/urls.py
  openedx/core/djangoapps/demographics/rest_api/v1/__init__.py
  openedx/core/djangoapps/demographics/rest_api/v1/urls.py
  openedx/core/djangoapps/demographics/rest_api/v1/views.py
  scripts/user_retirement/retire_one_learner.py
  scripts/user_retirement/utils/helpers.py
Labels: needs maintainer attention
