Repository openedx/edx-platform, pull requests merged in 2024-10, with the labels that each got.

#35033 33589: Updated mako_block.py to use MakoService
  xmodule/mako_block.py
Labels: open-source-contribution, needs reviewer assigned

#35491 fix: receive XBlock visibility from the Learning MFE
  lms/static/completion/js/ViewedEvent.js
Labels: open-source-contribution

#35572 fix: remove 'toggle_status: unsupported' from COURSES_INVITE_ONLY
  lms/djangoapps/courseware/toggles.py
Labels: open-source-contribution

#35580 feat: rework idv cert trigger
  common/djangoapps/third_party_auth/tests/test_pipeline_integration.py
  lms/djangoapps/certificates/docs/diagrams/certificate_generation.dsl
  lms/djangoapps/certificates/signals.py
  lms/djangoapps/certificates/tests/test_filters.py
  lms/djangoapps/verify_student/management/commands/tests/test_backfill_sso_verifications_for_old_account_links.py
  lms/djangoapps/verify_student/models.py
  openedx/core/djangoapps/signals/signals.py
Labels: waiting for eng review

#35598 Improve v2 library block permissions checks for read-only authors
  common/templates/xblock_v2/xblock_iframe.html
  lms/templates/xblock_v2/xblock_iframe.html
  openedx/core/djangoapps/content_libraries/library_context.py
  openedx/core/djangoapps/content_libraries/permissions.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/views.py
  openedx/core/djangoapps/xblock/api.py
  openedx/core/djangoapps/xblock/learning_context/learning_context.py
  openedx/core/djangoapps/xblock/rest_api/views.py
Labels: open-source-contribution

#35624 refactor: get rid of XBlockRuntimeSystem
  openedx/core/djangoapps/xblock/api.py
  openedx/core/djangoapps/xblock/apps.py
  openedx/core/djangoapps/xblock/runtime/learning_core_runtime.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
Labels: open-source-contribution

#35644 feat!: Remove outdated Libraries Relaunch cruft
  cms/djangoapps/contentstore/config/waffle.py
  cms/djangoapps/contentstore/rest_api/v1/serializers/home.py
  cms/djangoapps/contentstore/rest_api/v1/views/home.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_home.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/library.py
  cms/djangoapps/contentstore/views/tests/test_block.py
  cms/djangoapps/contentstore/views/tests/test_clipboard_paste.py
  cms/envs/common.py
  cms/envs/devstack.py
  cms/templates/index.html
  docs/docs_settings.py
  lms/djangoapps/course_blocks/transformers/library_content.py
  lms/djangoapps/courseware/block_render.py
  lms/djangoapps/grades/rest_api/v1/views.py
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/tasks.py
  openedx/core/lib/xblock_utils/__init__.py
  openedx/tests/completion_integration/test_services.py
  setup.py
  webpack.builtinblocks.config.js
  xmodule/assets/library_content/public/js/library_content_edit_helpers.js
  xmodule/library_content_block.py
  xmodule/library_tools.py
  xmodule/modulestore/mixed.py
  xmodule/modulestore/split_mongo/caching_descriptor_system.py
  xmodule/modulestore/split_mongo/split.py
  xmodule/tests/test_library_content.py
  xmodule/tests/test_library_tools.py
  xmodule/tests/test_randomize_block.py
  xmodule/vertical_block.py
Labels: create-sandbox

#34432 feat: adaptive display of links 'Learn more' and 'Share feedback'
  cms/templates/course_outline.html
Labels: open-source-contribution

#35626 feat: Allow specifying a version when loading a v2 XBlock
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/fields_test_block.py
  openedx/core/djangoapps/content_libraries/tests/test_embed_block.py
  openedx/core/djangoapps/content_libraries/views.py
  openedx/core/djangoapps/waffle_utils/__init__.py
  openedx/core/djangoapps/xblock/api.py
  openedx/core/djangoapps/xblock/apps.py
  openedx/core/djangoapps/xblock/data.py
  openedx/core/djangoapps/xblock/rest_api/urls.py
  openedx/core/djangoapps/xblock/rest_api/views.py
  openedx/core/djangoapps/xblock/runtime/learning_core_runtime.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
Labels: open-source-contribution

#35637 chore: delete unused requirements.txt file
  requirements.txt
Labels: open-source-contribution

#35458 chore: update Django to 4.2.16 for Redwood - Security Patch
  requirements/common_constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
  requirements/pip-tools.txt
  scripts/user_retirement/requirements/base.txt
  scripts/user_retirement/requirements/testing.txt
Labels: open-source-contribution

#35474 Revert "fix: Open Responses Styling and Layout (#33717)"
  lms/static/sass/course/instructor/_instructor_2.scss
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, needs reviewer assigned

#35142 feat: adds CourseAboutPageURLRequested and LMSPageURLRequested filters
  cms/djangoapps/contentstore/asset_storage_handlers.py
  cms/djangoapps/contentstore/tests/test_filters.py
  common/djangoapps/util/course.py
  common/djangoapps/util/tests/test_filters.py
Labels: open-source-contribution

#35676 Fix versioned URLs for XBlock handlers in v2 runtime [FC-0062]
  cms/static/js/views/modals/preview_v2_library_changes.js
  cms/static/sass/views/_container.scss
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/tests/test_versioned_apis.py
  openedx/core/djangoapps/content_libraries/views.py
  openedx/core/djangoapps/xblock/api.py
  openedx/core/djangoapps/xblock/rest_api/url_converters.py
  openedx/core/djangoapps/xblock/rest_api/urls.py
  openedx/core/djangoapps/xblock/rest_api/views.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
Labels: open-source-contribution, FC

#35670 feat: adds Library Content button to Studio Unit page [FC-0062]
  cms/djangoapps/contentstore/helpers.py
  cms/djangoapps/contentstore/rest_api/v1/serializers/vertical_block.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/block.py
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/images/large-library_v2-icon.png
  cms/static/js/views/components/add_library_content.js
  cms/static/js/views/components/add_xblock.js
  cms/static/js/views/pages/container.js
  cms/static/sass/assets/_graphics.scss
  cms/static/sass/elements/_drawer.scss
  cms/static/sass/views/_container.scss
  cms/templates/container.html
  openedx/core/djangoapps/content_staging/api.py
Labels: open-source-contribution

#35677 feat: endpoint to publish single library component
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/urls.py
  openedx/core/djangoapps/content_libraries/views.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#35681 feat: add endpoint to get draft version of a library component asset
  openedx/core/djangoapps/content_libraries/tests/test_embed_block.py
  openedx/core/djangoapps/content_libraries/tests/test_static_assets.py
  openedx/core/djangoapps/content_libraries/urls.py
  openedx/core/djangoapps/content_libraries/views.py
  openedx/core/djangoapps/xblock/runtime/learning_core_runtime.py
Labels: open-source-contribution

#35690 feat: add "beta" label to libraries v2 content + item bank buttons
  cms/static/sass/elements/_modules.scss
  cms/templates/js/add-xblock-component-button.underscore
Labels: open-source-contribution

#35679 "Bare Bones" UI for Problem Bank [FC-0062]
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/preview.py
  cms/envs/common.py
  cms/static/js/views/modals/select_v2_library_content.js
  cms/static/js/views/pages/container.js
  cms/templates/studio_xblock_wrapper.html
  xmodule/item_bank_block.py
  xmodule/templates/item_bank/author_view.html
  xmodule/templates/item_bank/author_view_add.html
  xmodule/tests/test_item_bank.py
Labels: open-source-contribution, FC

#35706 feat: itembank green button
  cms/djangoapps/contentstore/helpers.py
  cms/djangoapps/contentstore/views/component.py
  cms/static/images/large-itembank-icon.png
  cms/static/sass/assets/_graphics.scss
Labels: open-source-contribution

#35711 feat: freeze edx-sandbox requirements for sumac
  requirements/edx-sandbox/README.rst
  requirements/edx-sandbox/releases/sumac.txt
Labels: open-source-contribution

#35700 feat: show alert while editing v2 library content [FC-0062]
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/lib/xblock/upstream_sync.py
  cms/static/js/spec_helpers/edit_helpers.js
  cms/static/js/views/modals/edit_xblock.js
  cms/static/js/views/pages/container.js
  cms/static/sass/views/_container.scss
  cms/templates/js/edit-upstream-alert.underscore
Labels: open-source-contribution, FC

#35506 feat! Dropping Sass support from builtin video block
  cms/envs/common.py
  common/static/sass/_builtin-block-variables.scss
  lms/envs/common.py
  xmodule/assets/VideoBlockDisplay.scss
  xmodule/assets/VideoBlockEditor.scss
  xmodule/assets/tabs/_tabs.scss
  xmodule/assets/video/_accessible_menu.scss
  xmodule/assets/video/_display.scss
  xmodule/static/css-builtin-blocks/VideoBlockDisplay.css
  xmodule/static/css-builtin-blocks/VideoBlockEditor.css
  xmodule/tests/test_util_builtin_assets.py
  xmodule/util/builtin_assets.py
  xmodule/video_block/video_block.py
Labels: hacktoberfest-accepted, create-sandbox

#35726 chore: remove all references to content library types
  cms/djangoapps/contentstore/views/tests/test_clipboard_paste.py
  openedx/core/djangoapps/content/search/tests/test_api.py
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/constants.py
  openedx/core/djangoapps/content_libraries/migrations/0011_remove_contentlibrary_bundle_uuid_and_more.py
  openedx/core/djangoapps/content_libraries/models.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/tests/test_models.py
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/content_libraries/tests/test_views_lti.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: open-source-contribution

#35716 Dropping Sass support from builtin annotatable block
  xmodule/annotatable_block.py
  xmodule/assets/AnnotatableBlockDisplay.scss
  xmodule/assets/AnnotatableBlockEditor.scss
  xmodule/assets/annotatable/_display.scss
  xmodule/static/css-builtin-blocks/AnnotatableBlockDisplay.css
  xmodule/static/css-builtin-blocks/AnnotatableBlockEditor.css
Labels: hacktoberfest-accepted

#35717 feat!: Dropping Sass support from builtin word cloud block
  xmodule/assets/WordCloudBlockDisplay.scss
  xmodule/assets/word_cloud/_display.scss
  xmodule/static/css-builtin-blocks/WordCloudBlockDisplay.css
  xmodule/word_cloud_block.py
Labels: hacktoberfest-accepted

#35728 fix: do not open mfe editors automatically on block paste [FC-0062]
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
Labels: open-source-contribution

#35718 Dropping Sass support from builtin poll block
  xmodule/assets/PollBlockDisplay.scss
  xmodule/assets/poll/_display.scss
  xmodule/poll_block.py
  xmodule/static/css-builtin-blocks/PollBlockDisplay.css
Labels: hacktoberfest-accepted

#35675 fix: certificate display behavior not showing date-picker for end-with-date
  cms/static/js/factories/settings.js
  cms/static/js/models/settings/course_details.js
  cms/static/js/views/settings/main.js
Labels: open-source-contribution, needs maintainer attention, needs reviewer assigned

#35719 Dropping Sass support from builtin html block
  xmodule/assets/HtmlBlockDisplay.scss
  xmodule/assets/HtmlBlockEditor.scss
  xmodule/assets/editor/_edit.scss
  xmodule/assets/html/_display.scss
  xmodule/assets/html/_edit.scss
  xmodule/html_block.py
  xmodule/static/css-builtin-blocks/HtmlBlockDisplay.css
  xmodule/static/css-builtin-blocks/HtmlBlockEditor.css
Labels: hacktoberfest-accepted, create-sandbox

#35729 fix: do not open mfe editors automatically on block paste
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
Labels: open-source-contribution, needs reviewer assigned
