Repository openedx/edx-platform, pull requests merged in 2024-02, with the labels that each got.

#33922 feat: atlas pull plugins translation | FC-0012
  Makefile
  common/djangoapps/xblock_django/management/commands/pull_xblock_translations.py
  openedx/core/djangoapps/plugins/api.py
  openedx/core/djangoapps/plugins/apps.py
  openedx/core/djangoapps/plugins/constants.py
  openedx/core/djangoapps/plugins/i18n_api.py
  openedx/core/djangoapps/plugins/management/__init__.py
  openedx/core/djangoapps/plugins/management/commands/__init__.py
  openedx/core/djangoapps/plugins/management/commands/compile_plugin_translations.py
  openedx/core/djangoapps/plugins/management/commands/pull_plugin_translations.py
  openedx/core/djangoapps/plugins/settings/__init__.py
  openedx/core/djangoapps/plugins/settings/production.py
  openedx/core/djangoapps/plugins/tests/test_commands.py
  openedx/core/djangoapps/plugins/tests/test_i18n_api.py
Labels: open-source-contribution

#34153 feat: add auth JWKS endpoint
  openedx/core/djangoapps/user_authn/urls.py
  openedx/core/djangoapps/user_authn/views/auth.py
  openedx/core/djangoapps/user_authn/views/tests/test_auth.py
Labels: open-source-contribution, needs test run

#34174 feat: add discussion settings to course index api
  cms/djangoapps/contentstore/rest_api/v1/serializers/course_index.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_course_index.py
  cms/djangoapps/contentstore/utils.py
Labels: open-source-contribution

#34171 fix: add missing function import in certificate template (#33904)
  lms/djangoapps/certificates/tests/test_views.py
  lms/templates/certificates/accomplishment-base.html
Labels: open-source-contribution

#34170 fix: add missing function import in certificate template (#33904)
  lms/djangoapps/certificates/tests/test_views.py
  lms/templates/certificates/accomplishment-base.html
Labels: open-source-contribution

#33649 fix: youtube race condition when GTM loads
  xmodule/js/src/video/01_initialize.js
Labels: open-source-contribution, waiting for eng review

#33650 fix: youtube race condition when GTM loads
  xmodule/js/src/video/01_initialize.js
Labels: open-source-contribution, backport

#33677 fix: ORA response with attached file (for master)
  lms/djangoapps/ora_staff_grader/serializers.py
  lms/djangoapps/ora_staff_grader/tests/test_serializers.py
Labels: open-source-contribution

#33647 feat: filter courses by user language by default
  lms/djangoapps/courseware/toggles.py
  lms/djangoapps/courseware/views/views.py
  lms/static/js/discovery/discovery_factory.js
  lms/static/js/discovery/views/search_form.js
  lms/static/js/spec/discovery/discovery_factory_spec.js
  lms/static/js/spec/discovery/views/search_form_spec.js
  lms/templates/courseware/courses.html
Labels: open-source-contribution, waiting for eng review

#33676 fix: ORA response with attached file (for Quince)
  lms/djangoapps/ora_staff_grader/serializers.py
  lms/djangoapps/ora_staff_grader/tests/test_serializers.py
Labels: open-source-contribution, backport

#34181 fix: handle countries not recognized by geoip2 DB
  openedx/core/djangoapps/geoinfo/api.py
Labels: open-source-contribution

#34182 feat: allow disabling user tours
  lms/djangoapps/user_tours/toggles.py
  lms/djangoapps/user_tours/v1/tests/test_views.py
  lms/djangoapps/user_tours/v1/views.py
Labels: open-source-contribution

#34177 fix: change deprecated defusedxml.lxml to defusedxml.common
  openedx/core/lib/safe_lxml/tests.py
  openedx/core/lib/safe_lxml/xmlparser.py
Labels: open-source-contribution

#34209 fix: fixing the prompt view cancel button style for color and cursor …
  cms/static/sass/elements/_system-feedback.scss
Labels: open-source-contribution

#34143 feat: Export ID on Taxonomy
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#34146 refactor: remove ContentObjectTag model and related functions
  cms/djangoapps/contentstore/views/component.py
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/migrations/0008_remove_content_object_tag.py
  openedx/core/djangoapps/content_tagging/models/__init__.py
  openedx/core/djangoapps/content_tagging/models/base.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rules.py
  openedx/core/djangoapps/content_tagging/tasks.py
  openedx/core/djangoapps/content_tagging/tests/test_api.py
  openedx/core/djangoapps/content_tagging/tests/test_rules.py
  openedx/core/djangoapps/content_tagging/tests/test_tasks.py
  openedx/core/djangoapps/content_tagging/types.py
  openedx/core/djangoapps/content_tagging/utils.py
Labels: open-source-contribution

#34203 fix: survey xblock styling issues on mobile app
  lms/static/sass/lms-course.scss
Labels: open-source-contribution

#34214 chore: Use preferred Collection method `delete_one`
  xmodule/modulestore/split_mongo/mongo_connection.py
Labels: open-source-contribution

#33672 feat: add open_managed team type
  cms/djangoapps/models/settings/course_metadata.py
  cms/djangoapps/models/settings/tests/test_settings.py
  lms/djangoapps/teams/static/teams/js/views/team_profile.js
  lms/djangoapps/teams/static/teams/js/views/team_profile_header_actions.js
  lms/djangoapps/teams/static/teams/js/views/team_utils.js
  lms/djangoapps/teams/tests/test_api.py
  lms/djangoapps/teams/views.py
  openedx/core/lib/teams_config.py
Labels: open-source-contribution

#34145 [FC-0049] feat: Serialize tag data in OLX for blocks
  cms/envs/common.py
  cms/lib/xblock/tagging/tagged_block_mixin.py
  openedx/core/lib/xblock_serializer/block_serializer.py
  openedx/core/lib/xblock_serializer/test_api.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
  xmodule/tests/test_export.py
  xmodule/xml_block.py
Labels: open-source-contribution

#33955 feat: expose `hide_from_toc` field in course blocks
  lms/djangoapps/course_api/blocks/serializers.py
  lms/djangoapps/course_home_api/outline/serializers.py
  lms/djangoapps/course_home_api/outline/tests/test_view.py
  openedx/features/course_experience/utils.py
Labels: open-source-contribution

#34160 feat: add dismiss button to survey report banner
  lms/templates/admin/base_site.html
  openedx/features/survey_report/static/survey_report/js/admin_banner.js
  openedx/features/survey_report/templates/survey_report/admin_banner.html
Labels: open-source-contribution

#34091 feat: export tagged course as csv
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/objecttag_export_helpers.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_objecttag_export_helpers.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/urls.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/views.py
  openedx/core/djangoapps/content_tagging/tests/test_api.py
  openedx/core/djangoapps/content_tagging/types.py
Labels: open-source-contribution

#34257 chore: pull_translations: use less Makefile commands and move it to Python | FC-0012
  Makefile
  openedx/core/djangoapps/plugins/i18n_api.py
Labels: open-source-contribution

#34020 fix: use non_atomic_requests decorator in handle_block view
  cms/djangoapps/contentstore/views/block.py
Labels: open-source-contribution, core contributor

#34066 Switch v2 libraries to Learning Core data models
  cms/djangoapps/contentstore/management/commands/backfill_orgs_and_org_courses.py
  cms/djangoapps/contentstore/tasks.py
  cms/djangoapps/contentstore/views/tests/test_clipboard_paste.py
  cms/envs/common.py
  lms/envs/common.py
  openedx/core/djangoapps/content_libraries/admin.py
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/library_bundle.py
  openedx/core/djangoapps/content_libraries/library_context.py
  openedx/core/djangoapps/content_libraries/migrations/0010_contentlibrary_learning_package_and_more.py
  openedx/core/djangoapps/content_libraries/models.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tasks.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/tests/test_models.py
  openedx/core/djangoapps/content_libraries/tests/test_runtime.py
  openedx/core/djangoapps/content_libraries/tests/test_static_assets.py
  openedx/core/djangoapps/content_libraries/urls.py
  openedx/core/djangoapps/content_libraries/views.py
  openedx/core/djangoapps/content_tagging/rest_api/v1/tests/test_views.py
  openedx/core/djangoapps/content_tagging/tests/test_tasks.py
  openedx/core/djangoapps/content_tagging/utils.py
  openedx/core/djangoapps/xblock/api.py
  openedx/core/djangoapps/xblock/learning_context/learning_context.py
  openedx/core/djangoapps/xblock/rest_api/views.py
  openedx/core/djangoapps/xblock/runtime/blockstore_field_data.py
  openedx/core/djangoapps/xblock/runtime/blockstore_runtime.py
  openedx/core/djangoapps/xblock/runtime/id_managers.py
  openedx/core/djangoapps/xblock/runtime/learning_core_runtime.py
  openedx/core/djangoapps/xblock/runtime/olx_parsing.py
  openedx/core/djangoapps/xblock/runtime/runtime.py
  openedx/core/djangolib/blockstore_cache.py
  openedx/core/djangolib/tests/test_blockstore_cache.py
  openedx/core/lib/blockstore_api/__init__.py
  openedx/core/lib/xblock_serializer/api.py
  xmodule/tests/test_library_tools.py
  xmodule/video_block/transcripts_utils.py
Labels: Content Libraries

#34227 feat: add auto generated username field
  openedx/core/djangoapps/user_api/accounts/serializers.py
  openedx/core/djangoapps/user_api/accounts/tests/test_views.py
  openedx/core/djangoapps/user_authn/toggles.py
Labels: needs maintainer attention

#31976 feat: Remove edX branding on account deletion
  lms/static/js/student_account/components/StudentAccountDeletion.jsx
  lms/static/js/student_account/components/StudentAccountDeletionModal.jsx
Labels: open-source-contribution, core committer

#34249 fix: hide help button in unauthenticated studio header when ENABLE_HELP_LINK is set to False
  cms/templates/widgets/header.html
Labels: open-source-contribution

#33952 feat: make hide from TOC a visibility section setting
  cms/djangoapps/contentstore/rest_api/v0/serializers/xblock.py
  cms/djangoapps/contentstore/tests/test_contentstore.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/js/models/xblock_info.js
  cms/static/js/spec/views/pages/course_outline_spec.js
  cms/static/js/views/modals/course_outline_modals.js
  cms/static/js/views/pages/container_subviews.js
  cms/static/js/views/utils/xblock_utils.js
  cms/static/js/views/xblock_outline.js
  cms/static/sass/elements/_modules.scss
  cms/static/sass/partials/cms/theme/_variables-v1.scss
  cms/static/sass/views/_container.scss
  cms/templates/js/course-outline.underscore
  cms/templates/js/staff-lock-editor.underscore
  xmodule/modulestore/inheritance.py
Labels: open-source-contribution, product review, core contributor, product review complete

#33690 fix: course mode added to the metadata
  lms/djangoapps/course_home_api/course_metadata/serializers.py
  lms/djangoapps/course_home_api/course_metadata/views.py
Labels: open-source-contribution, product review

#33691 fix: course mode added to the metadata
  lms/djangoapps/course_home_api/course_metadata/serializers.py
  lms/djangoapps/course_home_api/course_metadata/views.py
Labels: open-source-contribution, backport
