Repository openedx/edx-platform, pull requests merged in 2024-05, with the labels that each got.

#34682 [FC-0036] fix: Update tag counts when changes are saved in the tag drawer
  cms/static/js/views/pages/container_subviews.js
  cms/static/js/views/tag_count.js
Labels: open-source-contribution

#32436 fix: enroll users when added to a forum role
  lms/djangoapps/instructor/tests/test_api.py
  lms/djangoapps/instructor/views/api.py
  lms/templates/instructor/instructor_dashboard_2/membership.html
Labels: open-source-contribution, waiting on author, product review, core contributor

#34643 fix: add support to Group Configuration view for Teams partitions
  cms/djangoapps/contentstore/utils.py
  cms/static/js/views/pages/group_configurations.js
  cms/templates/group_configurations.html
  lms/djangoapps/teams/team_partition_scheme.py
Labels: open-source-contribution, create-sandbox

#34690 [FC-0036] feat: Tag sections, subsections, and the whole course
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/js/views/course_manage_tags.js
  cms/static/js/views/course_outline.js
  cms/static/js/views/pages/course_outline.js
  cms/static/sass/views/_outline.scss
  cms/templates/course_outline.html
  cms/templates/js/course-manage-tags.underscore
  cms/templates/js/course-outline.underscore
Labels: open-source-contribution

#34627 [FC-0040] fix: Stop autotagging the course base XBlock id
  openedx/core/djangoapps/content/search/api.py
  openedx/core/djangoapps/content/search/tests/test_api.py
  openedx/core/djangoapps/content_tagging/handlers.py
  openedx/core/djangoapps/content_tagging/tests/test_tasks.py
Labels: open-source-contribution

#32406 feat: default grade designations configurable from settings
  cms/djangoapps/contentstore/rest_api/v1/serializers/grading.py
  cms/djangoapps/contentstore/rest_api/v1/views/grading.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_grading.py
  cms/djangoapps/contentstore/utils.py
  cms/envs/common.py
  cms/static/js/factories/settings_graders.js
  cms/static/js/views/settings/grading.js
  cms/static/sass/views/_settings.scss
  cms/templates/settings_graders.html
Labels: open-source-contribution, waiting for eng review, product review complete

#34735 chore: update Django to 4.2.13
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
  scripts/user_retirement/requirements/base.txt
  scripts/user_retirement/requirements/testing.txt
Labels: open-source-contribution

#34742 feat: Always enable the "copy-paste units" functionality
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
Labels: open-source-contribution

#34747 docs: [FC-0056] change default value for a Navigation sidebar toggle
  lms/djangoapps/courseware/toggles.py
Labels: open-source-contribution

#34740 feat: Avoid to close tag drawer when click outside
  cms/static/js/views/utils/tagging_drawer_utils.js
Labels: open-source-contribution

#34728 [FC-0049] feat: Update remove object-tag permission
  openedx/core/djangoapps/content_tagging/rules.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#34633 feat: Enable taxonomy/tagging feature in MFE by default
  cms/djangoapps/contentstore/rest_api/v1/serializers/vertical_block.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_course_index.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_home.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_vertical_block.py
  cms/djangoapps/contentstore/toggles.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/views/block.py
  cms/djangoapps/contentstore/views/tests/test_block.py
  cms/djangoapps/contentstore/views/tests/test_course_index.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/js/views/course_outline.js
  cms/static/js/views/pages/container.js
  cms/static/js/views/pages/course_outline.js
  cms/static/js/views/xblock_outline.js
  cms/templates/js/course-outline.underscore
  cms/templates/studio_xblock_wrapper.html
  openedx/core/djangoapps/content_tagging/toggles.py
Labels: open-source-contribution

#34752 feat: freeze edx-sandbox requirements for redwood
  requirements/edx-sandbox/README.rst
  requirements/edx-sandbox/releases/redwood.txt
Labels: open-source-contribution

#34757 feat: freeze edx-sandbox requirements for redwood
  requirements/edx-sandbox/README.rst
  requirements/edx-sandbox/releases/redwood.txt
Labels: open-source-contribution, backport

#34424 fix: Course blocks API with param return_type=list
  lms/djangoapps/course_api/blocks/tests/test_views.py
  lms/djangoapps/course_api/blocks/utils.py
Labels: open-source-contribution

#34426 fix: Course blocks API with param return_type=list 34379
  lms/djangoapps/course_api/blocks/utils.py
Labels: open-source-contribution, backport

#33939 fix: disable video status translation for JSON endpoint
  cms/djangoapps/contentstore/video_storage_handlers.py
  cms/djangoapps/contentstore/views/tests/test_videos.py
Labels: open-source-contribution, waiting for eng review

#34782 test: Update tagged openassessment test
  openedx/core/lib/xblock_serializer/test_api.py
Labels: open-source-contribution

#34817 fix: use the correct environment variable in watch_sass [redwood backport]
  scripts/watch_sass.sh
Labels: backport

#34688 fix: make `lis_person_contact_email_primary` matching case-insensitive (LTI Providers)
  lms/djangoapps/lti_provider/tests/test_users.py
  lms/djangoapps/lti_provider/users.py
Labels: open-source-contribution

#34529 refactor: rename minimum partition ID constant to be more generic
  cms/djangoapps/contentstore/course_group_config.py
  cms/djangoapps/contentstore/views/tests/test_block.py
  cms/djangoapps/models/settings/course_metadata.py
  cms/lib/xblock/test/test_authoring_mixin.py
  lms/djangoapps/courseware/tests/test_access.py
  lms/djangoapps/teams/team_partition_scheme.py
  openedx/core/djangoapps/verified_track_content/tests/test_partition_scheme.py
  xmodule/partitions/partitions.py
  xmodule/tests/test_split_test_block.py
Labels: open-source-contribution

#34783 fix: add in-line docs correct namespace for content_groups_for_teams
  openedx/core/lib/teams_config.py
Labels: open-source-contribution

#34523 Fix libraries performance problem
  cms/djangoapps/contentstore/rest_api/v1/views/home.py
  cms/djangoapps/contentstore/views/course.py
  common/djangoapps/student/auth.py
  common/djangoapps/student/role_helpers.py
  common/djangoapps/student/roles.py
  common/djangoapps/student/tests/test_roles.py
Labels: Content Libraries

#34796 [FC-0049] chore: Bump version of openedx-learning for taxonomy import improvements
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#34800 Fix: sometimes, changes to subsections are not reflected in the Studio Search Index
  xmodule/modulestore/__init__.py
  xmodule/modulestore/mixed.py
Labels: open-source-contribution

#34846 [Cherry-pick] [FC-0049] chore: Bump version of openedx-learning for taxonomy import improvements
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#34807 build: nudge devs about Redwood release in github
  .github/pull_request_template.md
Labels: open-source-contribution

#34806 feat: emit passing status updated events for badging
  cms/envs/common.py
  lms/djangoapps/grades/events.py
  lms/djangoapps/grades/tests/test_events.py
  lms/envs/common.py
Labels: open-source-contribution

#34417 [DEPR]: Remove Neo4J Support #34342
  .github/workflows/unit-test-shards.json
  cms/djangoapps/contentstore/signals/handlers.py
  cms/djangoapps/coursegraph/README.rst
  cms/djangoapps/coursegraph/__init__.py
  cms/djangoapps/coursegraph/admin.py
  cms/djangoapps/coursegraph/apps.py
  cms/djangoapps/coursegraph/management/__init__.py
  cms/djangoapps/coursegraph/management/commands/__init__.py
  cms/djangoapps/coursegraph/management/commands/dump_to_neo4j.py
  cms/djangoapps/coursegraph/management/commands/tests/__init__.py
  cms/djangoapps/coursegraph/management/commands/tests/test_dump_to_neo4j.py
  cms/djangoapps/coursegraph/management/commands/tests/utils.py
  cms/djangoapps/coursegraph/models.py
  cms/djangoapps/coursegraph/tasks.py
  cms/djangoapps/coursegraph/tests/__init__.py
  cms/djangoapps/coursegraph/tests/test_admin.py
  cms/envs/common.py
  cms/envs/devstack.py
  cms/envs/production.py
  setup.cfg
Labels: open-source-contribution

#34851 fix: make lis_person_contact_email_primary matching case-insensitive (LTI Providers)
  lms/djangoapps/lti_provider/tests/test_users.py
  lms/djangoapps/lti_provider/users.py
Labels: open-source-contribution

#34856 feat: include units when calculating completion percentage (#34816)
  lms/djangoapps/course_home_api/outline/serializers.py
  lms/djangoapps/course_home_api/outline/tests/test_view.py
  lms/djangoapps/course_home_api/outline/views.py
Labels: open-source-contribution

#33575 fix: open new editors from non-unit Studio container page
  cms/static/js/views/pages/container.js
  cms/templates/container.html
Labels: open-source-contribution, waiting for eng review, jira:2u
