Repository openedx/edx-platform, pull requests merged in 2024-08, with the labels that each got.

#35091 [FC-0059] feat: New fields in library details API view
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: open-source-contribution, FC

#35189 feat: added custom setting attribute for gradebook freeze timedelta
  lms/djangoapps/grades/grade_utils.py
  lms/envs/common.py
Labels: open-source-contribution

#35217 fix: error when saving changes to a v2 library block [FC-0059]
  openedx/core/djangoapps/xblock/rest_api/views.py
Labels: open-source-contribution

#35240 chore: update Django to 4.2.15 for Redwood - Security Patch
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
  scripts/user_retirement/requirements/base.txt
  scripts/user_retirement/requirements/testing.txt
Labels: open-source-contribution

#35225 backport fix: disable submit button for archived courses (#34920) to quince
  xmodule/capa_block.py
  xmodule/tests/test_capa_block.py
Labels: open-source-contribution

#35248 backport fix: disable submit button for archived courses (#34920) to redwood
  xmodule/capa_block.py
  xmodule/tests/test_capa_block.py
Labels: open-source-contribution

#35211 [FC-0059] feat: allow copy library v2 xblock
  openedx/core/djangoapps/content_staging/views.py
Labels: open-source-contribution

#35259 [Backport] fix: Prevent error page recursion (#35209)
  lms/djangoapps/static_template_view/views.py
Labels: open-source-contribution

#35199 feat: Library Home Paste Content [FC-0059]
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/serializers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/urls.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: open-source-contribution, FC

#35239 fix: Respect the authsource kwarg for MongoDB connections
  xmodule/mongo_utils.py
Labels: open-source-contribution

#35312 feat: add collections app from openedx-learning [FC-0059]
  cms/envs/common.py
  lms/envs/common.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, FC

#35138 chore: provide logo url from backend for batch enrollment email
  lms/djangoapps/instructor/enrollment.py
  lms/djangoapps/instructor/tests/test_enrollment.py
  themes/red-theme/lms/templates/ace_common/edx_ace/common/base_body.html
Labels: open-source-contribution, needs reviewer assigned

#35378 backport chore: provide logo url from backend for batch enrollment email (#35138)
  lms/djangoapps/instructor/enrollment.py
  lms/djangoapps/instructor/tests/test_enrollment.py
  themes/red-theme/lms/templates/ace_common/edx_ace/common/base_body.html
Labels: open-source-contribution, backport, needs reviewer assigned

#35242 feat: Problem types added as filterable attribute [FC-0059]
  openedx/core/djangoapps/content/search/api.py
  openedx/core/djangoapps/content/search/documents.py
Labels: open-source-contribution, FC

#35320 feat: allow update xblock fields without passing data [FC-0062]
  openedx/core/djangoapps/xblock/rest_api/views.py
Labels: open-source-contribution, FC

#35324 feat: index library collections in meilisearch [FC-0062]
  openedx/core/djangoapps/content/search/api.py
  openedx/core/djangoapps/content/search/documents.py
  openedx/core/djangoapps/content/search/tests/test_api.py
  openedx/core/djangoapps/content/search/tests/test_documents.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, FC

#35390 fix: renamed DatabaseNotReadyError for better code clarity
  lms/djangoapps/grades/exceptions.py
  lms/djangoapps/grades/tasks.py
Labels: open-source-contribution, needs reviewer assigned

#35402 Update CORS allowed headers for compatibility w/ axios-cache-interceptor
  lms/envs/common.py
Labels: open-source-contribution

#35367 fix: update library index synchronously [FC-0062]
  openedx/core/djangoapps/content/search/handlers.py
Labels: open-source-contribution, FC
