Repository openedx/edx-platform, pull requests merged in 2025-09, with the labels that each got.

#37307 feat: Add support for using LTI data to populate user profile
  lms/djangoapps/lti_provider/migrations/0005_lticonsumer_use_lti_pii.py
  lms/djangoapps/lti_provider/models.py
  lms/djangoapps/lti_provider/tests/test_users.py
  lms/djangoapps/lti_provider/users.py
  lms/djangoapps/lti_provider/views.py
Labels: open-source-contribution, core contributor

#37312 chore: change release line from 'master' to 'teak'
  openedx/core/release.py
Labels: open-source-contribution, core contributor

#37002 chore: remove deprecated DEFAULT_FILE_STORAGE and STATICFILES_STORAGE…
  cms/djangoapps/contentstore/tests/test_import.py
  cms/djangoapps/export_course_metadata/test_signals.py
  cms/envs/common.py
  cms/envs/devstack.py
  cms/envs/mock.yml
  cms/envs/production.py
  cms/envs/test.py
  common/djangoapps/util/file.py
  common/djangoapps/util/storage.py
  common/djangoapps/util/tests/test_resolve_storage_backend.py
  lms/djangoapps/instructor_task/models.py
  lms/envs/common.py
  lms/envs/devstack.py
  lms/envs/mock.yml
  lms/envs/production.py
  lms/envs/test.py
  openedx/core/djangoapps/theming/tests/test_views.py
  openedx/core/djangoapps/user_api/accounts/tests/test_views.py
  openedx/core/storage.py
  openedx/core/tests/test_storage.py
Labels: open-source-contribution, mao-onboarding

#37329 fix: unlink broken link
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
Labels: open-source-contribution

#37256 Backport #36958 check enterprise app is enabled
  common/djangoapps/third_party_auth/pipeline.py
Labels: open-source-contribution, backport, needs reviewer assigned

#37166 build: Upgrade to Node 24
  .nvmrc
  package-lock.json
Labels: create-sandbox

#37125 feat!: remove cs_comments_service support for forum's content APIs
  lms/djangoapps/discussion/django_comment_client/base/tests.py
  lms/djangoapps/discussion/django_comment_client/base/tests_v2.py
  lms/djangoapps/discussion/django_comment_client/tests/group_id.py
  lms/djangoapps/discussion/django_comment_client/tests/mixins.py
  lms/djangoapps/discussion/rest_api/tests/test_api.py
  lms/djangoapps/discussion/rest_api/tests/test_api_v2.py
  lms/djangoapps/discussion/rest_api/tests/test_serializers.py
  lms/djangoapps/discussion/rest_api/tests/test_serializers_v2.py
  lms/djangoapps/discussion/rest_api/tests/test_tasks.py
  lms/djangoapps/discussion/rest_api/tests/test_tasks_v2.py
  lms/djangoapps/discussion/rest_api/tests/test_views.py
  lms/djangoapps/discussion/rest_api/tests/utils.py
  lms/djangoapps/discussion/tests/test_tasks.py
  lms/djangoapps/discussion/tests/test_tasks_v2.py
  lms/djangoapps/discussion/tests/test_views.py
  lms/djangoapps/discussion/tests/test_views_v2.py
  openedx/core/djangoapps/django_comment_common/comment_client/models.py
  openedx/core/djangoapps/django_comment_common/comment_client/thread.py
  openedx/core/djangoapps/django_comment_common/comment_client/user.py
Labels: open-source-contribution

#37344 Backport #37320
  requirements/common_constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/semgrep.txt
  requirements/edx/testing.txt
  scripts/user_retirement/requirements/base.txt
  scripts/xblock/requirements.txt
Labels: open-source-contribution, backport

#37067 refactor: flatten FEATURES dictionary with backward compatible proxy
  cms/envs/common.py
  cms/envs/devstack.py
  cms/envs/production.py
  cms/envs/test.py
  lms/djangoapps/discussion/settings/common.py
  lms/djangoapps/instructor/settings/common.py
  lms/djangoapps/instructor/settings/production.py
  lms/djangoapps/instructor/settings/test.py
  lms/envs/common.py
  lms/envs/devstack.py
  lms/envs/production.py
  lms/envs/test.py
  openedx/core/djangoapps/ace_common/settings/common.py
  openedx/core/djangoapps/models/course_details.py
  openedx/core/lib/features_setting_proxy.py
  openedx/envs/common.py
  openedx/features/announcements/settings/common.py
  openedx/features/announcements/settings/test.py
Labels: open-source-contribution, create-sandbox, mao-onboarding

#37373 chore: remove outdated JWT auth related settings
  cms/envs/mock.yml
  lms/envs/mock.yml
  openedx/envs/common.py
Labels: open-source-contribution, mao-onboarding

#37375 refactor: course container children api
  cms/djangoapps/contentstore/rest_api/v1/serializers/__init__.py
  cms/djangoapps/contentstore/rest_api/v1/serializers/vertical_block.py
  cms/djangoapps/contentstore/rest_api/v1/urls.py
  cms/djangoapps/contentstore/rest_api/v1/views/__init__.py
  cms/djangoapps/contentstore/rest_api/v1/views/course_index.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_vertical_block.py
  cms/djangoapps/contentstore/rest_api/v1/views/vertical_block.py
  cms/lib/xblock/upstream_sync.py
Labels: open-source-contribution, FC, core contributor

#36856 docs: ADR for Visually Configure Course Components
  docs/decisions/0024-course-component-types.rst
  docs/images/сourse_сomponent_types_api_diagram.png
  docs/images/сourse_сomponent_types_page_design.png
  docs/images/сourse_сomponent_types_system_diagram.png
Labels: open-source-contribution

#37342 feat [FC-86]: update course_about & catalog link generation
  cms/djangoapps/contentstore/tests/test_course_settings.py
  cms/envs/test.py
  common/djangoapps/util/course.py
  common/djangoapps/util/tests/test_course.py
  lms/djangoapps/branding/test_toggles.py
  lms/djangoapps/branding/toggles.py
  lms/djangoapps/learner_home/test_views.py
  lms/djangoapps/learner_home/views.py
  lms/envs/common.py
  lms/envs/devstack.py
  lms/envs/test.py
Labels: open-source-contribution, FC
