Repository openedx/edx-platform, pull requests merged in 2025-03, with the labels that each got.

#36289 fix: Remove duplicate imports of js files in instructor dashboard pages
  lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html
Labels: open-source-contribution

#35751 feat: [FC-0070] Manage Tags interoperation
  cms/static/js/views/pages/container.js
  cms/static/sass/course-unit-mfe-iframe-bundle.scss
Labels: open-source-contribution, FC

#36302 fix: remove custom startup to fix dev reloading
  cms/conftest.py
  cms/startup.py
  cms/wsgi.py
  lms/startup.py
  lms/wsgi.py
  lms/wsgi_apache_lms.py
  manage.py
  openedx/core/djangoapps/catalog/models.py
  openedx/core/djangoapps/monkey_patch/__init__.py
Labels: create-sandbox

#36322 build: Regenerate package-lock.json
  package-lock.json
Labels: create-sandbox

#36306 refactor: Clean up CMS production settings cruft
  cms/envs/production.py
  lms/envs/production.py
Labels: create-sandbox

#36292 feat: Enable library blocks using settings [FC-0076]
  cms/envs/common.py
  openedx/core/djangoapps/content_libraries/api.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
Labels: open-source-contribution, FC

#36265 fix: allow LTI blocks to be loaded in a Library v2 context [FC-0076]
  xmodule/editing_block.py
  xmodule/lti_block.py
  xmodule/word_cloud_block.py
Labels: open-source-contribution, FC

#36333 feat: preserve image alt text while converting html to text
  xmodule/annotator_mixin.py
  xmodule/tests/test_annotator_mixin.py
Labels: open-source-contribution, needs reviewer assigned

#36341 feat!: Drop usage of the picturefill polyfill.
  lms/envs/common.py
  lms/static/js/learner_dashboard/views/program_card_view.js
  lms/static/lms/js/require-config.js
  lms/static/lms/js/spec/main.js
  package-lock.json
  package.json
  scripts/copy-node-modules.sh
Labels: create-sandbox

#36338 fix: pasted component search index document missing `breadcrumbs` [FC-0076]
  cms/djangoapps/contentstore/helpers.py
Labels: open-source-contribution, FC

#36353 fix: pasted component search index document missing breadcrumbs [sumac] [FC-0076]
  cms/djangoapps/contentstore/helpers.py
Labels: open-source-contribution, FC

#36318 fix: Show tag count when paste a component in a course [FC-0046]
  cms/djangoapps/contentstore/views/block.py
  cms/djangoapps/contentstore/xblock_storage_handlers/xblock_helpers.py
Labels: open-source-contribution, FC

#36311 refactor: downstream entity links api [FC-0076]
  cms/djangoapps/contentstore/models.py
  cms/djangoapps/contentstore/rest_api/v2/serializers/__init__.py
  cms/djangoapps/contentstore/rest_api/v2/serializers/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/urls.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
  cms/djangoapps/contentstore/utils.py
Labels: open-source-contribution, FC

#36177 chore: fix indentation and JSDoc comments that eslint is warning about
  cms/static/cms/js/require-config.js
  cms/static/js/models/xblock_info.js
  cms/static/js/spec/views/pages/container_subviews_spec.js
  cms/static/js/spec/views/pages/course_outline_spec.js
  cms/static/js/utils/copy_to_clipboard.js
  cms/static/js/views/course_outline.js
  scripts/eslint.py
Labels: open-source-contribution

#36355 docs: add event_type inline code annotation for events
  cms/djangoapps/contentstore/utils.py
  common/djangoapps/student/models/course_enrollment.py
  lms/djangoapps/certificates/models.py
  lms/djangoapps/grades/models.py
  lms/djangoapps/verify_student/signals/signals.py
  openedx/core/djangoapps/course_groups/models.py
  openedx/core/djangoapps/user_authn/views/login.py
  openedx/core/djangoapps/user_authn/views/register.py
  xmodule/modulestore/mixed.py
  xmodule/modulestore/xml_importer.py
Labels: open-source-contribution

#36385 feat: upgrade enterprise to 5.10.1, removing braze-client
  .github/workflows/check_python_dependencies.yml
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/bundled.in
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#36381 refactor: convert content libraries python API from attr.s to dataclass, fix types [FC-0083]
  openedx/core/djangoapps/content/search/api.py
  openedx/core/djangoapps/content/search/tests/test_documents.py
  openedx/core/djangoapps/content_libraries/api.py
Labels: open-source-contribution

#36315 fix: discussion xblock not compatible with forum v2
  lms/djangoapps/discussion/django_comment_client/base/tests.py
  lms/djangoapps/discussion/django_comment_client/base/views.py
  lms/djangoapps/discussion/views.py
  openedx/core/djangoapps/django_comment_common/comment_client/comment.py
  openedx/core/djangoapps/django_comment_common/comment_client/models.py
  openedx/core/djangoapps/django_comment_common/comment_client/thread.py
  openedx/core/djangoapps/django_comment_common/comment_client/user.py
Labels: open-source-contribution

#36236 Edx platform 35175 deprecate assert dict contains subset
  cms/djangoapps/api/v1/tests/test_views/test_course_runs.py
Labels: open-source-contribution, needs reviewer assigned

#36371 Basic CRUD REST Endpoints for units in content libraries [FC-0083]
  cms/envs/common.py
  lms/envs/common.py
  openedx/core/djangoapps/content/search/api.py
  openedx/core/djangoapps/content/search/documents.py
  openedx/core/djangoapps/content/search/handlers.py
  openedx/core/djangoapps/content/search/tasks.py
  openedx/core/djangoapps/content/search/tests/test_api.py
  openedx/core/djangoapps/content/search/tests/test_documents.py
  openedx/core/djangoapps/content_libraries/api/__init__.py
  openedx/core/djangoapps/content_libraries/api/blocks.py
  openedx/core/djangoapps/content_libraries/api/containers.py
  openedx/core/djangoapps/content_libraries/api/libraries.py
  openedx/core/djangoapps/content_libraries/api/permissions.py
  openedx/core/djangoapps/content_libraries/models.py
  openedx/core/djangoapps/content_libraries/rest_api/__init__.py
  openedx/core/djangoapps/content_libraries/rest_api/blocks.py
  openedx/core/djangoapps/content_libraries/rest_api/collections.py
  openedx/core/djangoapps/content_libraries/rest_api/containers.py
  openedx/core/djangoapps/content_libraries/rest_api/libraries.py
  openedx/core/djangoapps/content_libraries/rest_api/serializers.py
  openedx/core/djangoapps/content_libraries/rest_api/url_converters.py
  openedx/core/djangoapps/content_libraries/rest_api/utils.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_api.py
  openedx/core/djangoapps/content_libraries/tests/test_containers.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/urls.py
  openedx/core/djangoapps/content_tagging/api.py
  openedx/core/djangoapps/content_tagging/tests/test_api.py
  openedx/core/djangoapps/content_tagging/types.py
  openedx/core/djangoapps/content_tagging/utils.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/kernel.in
  requirements/edx/testing.txt
Labels: open-source-contribution, FC

#35813 feat: [FC-0070] add events and style for rendering Split xblock in chromeless template
  cms/djangoapps/contentstore/helpers.py
  cms/djangoapps/contentstore/views/component.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/static/images/advanced-icon.svg
  cms/static/images/drag-and-drop-v2-icon.svg
  cms/static/images/itembank-icon.svg
  cms/static/images/library-icon.svg
  cms/static/images/library_v2-icon.svg
  cms/static/images/openassessment-icon.svg
  cms/static/images/problem-icon.svg
  cms/static/images/text-icon.svg
  cms/static/images/video-icon.svg
  cms/static/js/views/components/add_xblock.js
  cms/static/js/views/pages/container.js
  cms/static/sass/course-unit-mfe-iframe-bundle.scss
  cms/static/sass/elements/_course-unit-mfe-iframe.scss
  cms/static/sass/partials/cms/theme/_variables-v1.scss
  cms/templates/container_chromeless.html
  lms/templates/split_test_author_view.html
Labels: open-source-contribution, FC
