Repository openedx/edx-platform, pull requests merged in 2025-08, with the labels that each got.

#37088 feat: disallow adding children to containers imported from library [FC-0097]
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
Labels: open-source-contribution, core contributor

#37131 feat!: update finder method to work with django 42 and 52
  openedx/core/djangoapps/theming/finders.py
  openedx/core/djangoapps/theming/tests/test_finders.py
  openedx/core/lib/xblock_pipeline/finder.py
Labels: create-sandbox

#36756 feat: new event to track LTI Launches via LTI Provider
  lms/djangoapps/lti_provider/tests/test_views.py
  lms/djangoapps/lti_provider/views.py
Labels: open-source-contribution, core contributor

#35983 Allow for Extracted Word Cloud Block | Fix Test Cases
  lms/djangoapps/courseware/tests/helpers.py
  lms/djangoapps/courseware/tests/test_word_cloud.py
  xmodule/tests/test_word_cloud.py
  xmodule/word_cloud_block.py
Labels: create-sandbox

#36566 Test PR | Enable Extracted Poll XBlock
  xmodule/poll_block.py
  xmodule/tests/test_poll.py
Labels: open-source-contribution, create-sandbox

#37187 fix: fix pylint quality warnings
  common/djangoapps/student/models/course_enrollment.py
Labels: open-source-contribution, core contributor

#37130 feat: Extend MFE Config API for `frontend-app-catalog` [FC-0086]
  lms/djangoapps/mfe_config_api/tests/test_views.py
  lms/djangoapps/mfe_config_api/views.py
Labels: open-source-contribution, FC

#37208 refactor: Refactor upstream links summary to add the top-level parent logic [FC-0097]
  cms/djangoapps/contentstore/models.py
  cms/djangoapps/contentstore/rest_api/v2/serializers/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstream_sync_integration.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
Labels: open-source-contribution

#36813 feat: adds api to retrieve library block/container hierarchy [FC-0090]
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstream_sync_integration.py
  openedx/core/djangoapps/content_libraries/api/container_metadata.py
  openedx/core/djangoapps/content_libraries/api/containers.py
  openedx/core/djangoapps/content_libraries/api/libraries.py
  openedx/core/djangoapps/content_libraries/rest_api/blocks.py
  openedx/core/djangoapps/content_libraries/rest_api/containers.py
  openedx/core/djangoapps/content_libraries/rest_api/serializers.py
  openedx/core/djangoapps/content_libraries/tests/base.py
  openedx/core/djangoapps/content_libraries/tests/test_containers.py
  openedx/core/djangoapps/content_libraries/tests/test_course_to_library.py
  openedx/core/djangoapps/content_libraries/urls.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, FC

#37234 fix: pylint warning arguments-differ
  openedx/core/djangoapps/course_groups/models.py
Labels: open-source-contribution, core contributor

#36803 feat: Use dropdown for units when there are more than would fit in the UI
  lms/templates/seq_block.html
  xmodule/js/src/sequence/display.js
  xmodule/static/css-builtin-blocks/SequenceBlockDisplay.css
Labels: open-source-contribution, core contributor

#37258 Updating pin for openedx-forum
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, core contributor

#35586 feat: add a POST endpoint for listing courses
  docs/lms-openapi.yaml
  lms/djangoapps/course_api/tests/test_views.py
  lms/djangoapps/course_api/views.py
Labels: open-source-contribution, waiting on author

#37217 feat: Top-level parent logic in `UpstreamLink.ready_to_sync` [FC-0097]
  cms/djangoapps/contentstore/rest_api/v2/urls.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstream_sync_integration.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
  cms/lib/xblock/upstream_sync.py
Labels: open-source-contribution, FC

#37262 feat: Allow adding custom LTI parameters via LTI_CUSTOM_PARAMS django setting
  lms/djangoapps/lti_provider/tests/test_views.py
  lms/djangoapps/lti_provider/views.py
  lms/envs/common.py
Labels: open-source-contribution, core contributor

#37257 Backport #37080 task path fixed
  lms/envs/production.py
Labels: open-source-contribution, backport

#37282 [Teak] feat: Show disabled edit button and tooltip to component in units from libraries [FC-0097]
  cms/static/sass/course-unit-mfe-iframe-bundle.scss
  cms/templates/studio_xblock_wrapper.html
Labels: open-source-contribution, FC

#37215 feat: Add `unlinkable` to xblock actions and update `top_level_parent_key` on unlink [FC-0097]
  cms/djangoapps/contentstore/models.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
  cms/djangoapps/contentstore/tasks.py
  cms/djangoapps/contentstore/utils.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/lib/xblock/upstream_sync.py
  cms/static/js/views/pages/container.js
  cms/templates/studio_xblock_wrapper.html
Labels: open-source-contribution, FC

#37306 Backport "fix: intermittent "utils attribute not found" issue in webpack_loader (#37109)" in Teak
  xmodule/util/builtin_assets.py
Labels: open-source-contribution
