Repository openedx/edx-platform, pull requests merged in 2025-02, with the labels that each got.

#36196 fix: enable pylint warnings
  cms/djangoapps/contentstore/video_storage_handlers.py
  common/djangoapps/student/models/user.py
  common/djangoapps/student/tests/test_parental_controls.py
  common/djangoapps/student/tests/test_views.py
  common/djangoapps/third_party_auth/api/tests/test_views.py
  common/djangoapps/third_party_auth/lti.py
  lms/djangoapps/bulk_email/models.py
  lms/djangoapps/course_blocks/transformers/tests/test_visibility.py
  lms/djangoapps/course_goals/management/commands/goal_reminder_email.py
  lms/djangoapps/courseware/tests/test_date_summary.py
  lms/djangoapps/discussion/tasks.py
  openedx/core/djangoapps/credit/models.py
  openedx/core/djangoapps/notifications/views.py
  pylintrc
  pylintrc_tweaks
Labels: open-source-contribution

#36031 feat: add publish status to library meilisearch index
  openedx/core/djangoapps/content/search/documents.py
  openedx/core/djangoapps/content/search/index_config.py
  openedx/core/djangoapps/content/search/tests/test_api.py
  openedx/core/djangoapps/content/search/tests/test_documents.py
  openedx/core/djangoapps/content/search/tests/test_handlers.py
Labels: open-source-contribution

#36173 fix: static assets in problem bank and library content block
  cms/djangoapps/contentstore/helpers.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/lib/xblock/upstream_sync.py
  openedx/core/djangoapps/content_staging/api.py
  openedx/core/djangoapps/content_staging/data.py
Labels: open-source-contribution

#36111 feat: upstream-downstream entity linking [FC-0076]
  cms/djangoapps/contentstore/admin.py
  cms/djangoapps/contentstore/management/commands/recreate_upstream_links.py
  cms/djangoapps/contentstore/migrations/0009_learningcontextlinksstatus_publishableentitylink.py
  cms/djangoapps/contentstore/models.py
  cms/djangoapps/contentstore/signals/handlers.py
  cms/djangoapps/contentstore/tasks.py
  cms/djangoapps/contentstore/tests/test_upstream_downstream_links.py
  cms/djangoapps/contentstore/tests/test_utils.py
  cms/djangoapps/contentstore/utils.py
  openedx/core/djangoapps/content_libraries/signal_handlers.py
  openedx/core/djangoapps/content_libraries/tasks.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
  xmodule/modulestore/tests/test_mixed_modulestore.py
  xmodule/modulestore/xml_importer.py
Labels: open-source-contribution

#35959 chore: iframe rendering optimization
  cms/static/js/views/pages/container.js
Labels: open-source-contribution

#36240 [backport] fix: static assets used in problem bank and library content block
  cms/djangoapps/contentstore/helpers.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
  cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py
  cms/lib/xblock/upstream_sync.py
  openedx/core/djangoapps/content_libraries/tests/test_static_assets.py
  openedx/core/djangoapps/content_libraries/views.py
  openedx/core/djangoapps/content_staging/api.py
  openedx/core/djangoapps/content_staging/data.py
  openedx/core/djangoapps/xblock/runtime/learning_core_runtime.py
Labels: open-source-contribution, backport

#36234 chore: update Django to 4.2.19 for Sumac - Security Patch
  requirements/common_constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/paver.txt
  requirements/edx/semgrep.txt
  requirements/edx/testing.txt
  scripts/user_retirement/requirements/base.txt
  scripts/user_retirement/requirements/testing.txt
  scripts/xblock/requirements.txt
Labels: open-source-contribution

#36226 fix: always define a student_data_store to prevent errors on XBlock load [FC-0076]
  openedx/core/djangoapps/xblock/runtime/runtime.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, FC

#36213 Replace pkg_resources with importlib.resources
  cms/djangoapps/contentstore/tasks.py
  cms/pytest.ini
  common/djangoapps/edxmako/paths.py
  common/test/pytest.ini
  openedx/core/lib/logsettings.py
  openedx/core/lib/xblock_pipeline/finder.py
  openedx/tests/xblock_integration/test_external_xblocks.py
  scripts/xblock/list-installed.py
  setup.cfg
  xmodule/modulestore/django.py
  xmodule/modulestore/tests/test_django_utils.py
  xmodule/x_module.py
Labels: create-sandbox

#36221 fix: Advanced editor styles [FC-0076]
  cms/static/sass/course-unit-mfe-iframe-bundle.scss
Labels: open-source-contribution, FC

#36228 Make copied tags editable again after breaking the upstream link to library content [FC-0076]
  cms/djangoapps/contentstore/signals/handlers.py
  cms/djangoapps/contentstore/tasks.py
  cms/djangoapps/contentstore/views/tests/test_clipboard_paste.py
  openedx/core/djangoapps/content_tagging/api.py
  requirements/constraints.txt
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#36227 chore: Update requirements to use new version of xblock-google-drive
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#36252 chore: Bump version of xblock-poll to 1.14.1 [FC-0076]
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#36256 chore: update edx-proctoring package version
  lms/djangoapps/support/tests/test_views.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution, needs reviewer assigned

#36190 feat: entity link view and api
  cms/djangoapps/contentstore/models.py
  cms/djangoapps/contentstore/rest_api/v2/serializers/__init__.py
  cms/djangoapps/contentstore/rest_api/v2/serializers/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/urls.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
  cms/djangoapps/contentstore/utils.py
  cms/templates/widgets/header.html
Labels: open-source-contribution

#35777 feat: [FC-0044] Course unit - Edit iframe modal window
  cms/djangoapps/contentstore/views/block.py
  cms/djangoapps/contentstore/views/tests/test_block.py
  cms/static/cms/js/main.js
  cms/static/js/views/container.js
  cms/static/js/views/modals/base_modal.js
  cms/static/js/views/modals/edit_xblock.js
  cms/static/js/views/pages/container.js
  cms/static/js/views/pages/container_subviews.js
  cms/static/sass/course-unit-mfe-iframe-bundle.scss
  cms/templates/container_editor.html
  cms/urls.py
Labels: open-source-contribution, FC

#36109 fix: import authoring filter from content_authoring instead
  cms/djangoapps/contentstore/asset_storage_handlers.py
  cms/djangoapps/contentstore/tests/test_filters.py
  requirements/edx/base.txt
  requirements/edx/development.txt
  requirements/edx/doc.txt
  requirements/edx/testing.txt
Labels: open-source-contribution

#36058 feat: Video editor supports transcripts [FC-0076]
  cms/djangoapps/contentstore/helpers.py
  cms/djangoapps/contentstore/rest_api/v2/views/downstreams.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_downstreams.py
  cms/djangoapps/contentstore/views/tests/test_transcripts.py
  cms/djangoapps/contentstore/views/transcripts_ajax.py
  cms/lib/xblock/test/test_upstream_sync.py
  cms/lib/xblock/upstream_sync.py
  openedx/core/djangoapps/xblock/rest_api/views.py
  xmodule/tests/test_video.py
  xmodule/video_block/transcripts_utils.py
  xmodule/video_block/video_block.py
  xmodule/video_block/video_handlers.py
Labels: open-source-contribution, FC

#36181 refactor!: remove `ENABLE_HOME_PAGE_COURSE_API_V2` feature toggle
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_home.py
  cms/djangoapps/contentstore/rest_api/v2/views/home.py
  cms/djangoapps/contentstore/rest_api/v2/views/tests/test_home.py
  cms/djangoapps/contentstore/tests/test_course_listing.py
  cms/djangoapps/contentstore/views/course.py
  cms/djangoapps/contentstore/views/tests/test_course_index.py
  cms/envs/common.py
Labels: open-source-contribution

#36288 [sumac] fix: allow_to_create_new_org checks org autocreate [FC-0076]
  cms/djangoapps/contentstore/rest_api/v1/serializers/home.py
  cms/djangoapps/contentstore/rest_api/v1/views/home.py
  cms/djangoapps/contentstore/rest_api/v1/views/tests/test_home.py
  openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
  openedx/core/djangoapps/content_libraries/views.py
Labels: open-source-contribution, FC
